### ISSUE TITLE
Conceal Feature

### ISSUE THREAD

**Issue by amadeus** [pangloss/vim-javascript#101]
~~The recent commit that removed a bunch of stuff from the README also removed the section documenting the `javascript_conceal` variable.~~ This was actually a mistaken merge, however I still question how it is implemented.

I personally don't really care for this feature, and think it's somewhat arbitrarily silly. In my opinion it should be something people would apply using an `after` or `ftplugin` or something. I don't think it belongs within the syntax file.

With that said however, it might be a very popular feature so just pulling it may not be an option.

Anyone else care to weigh in on this?

**Comment by dreki** [comment]
@PatrickHail's suggestion worked for me.

**Comment by Anzumana** [comment]
@PatrickHail same for me

**Comment by HiCodin** [comment]
The feature is working in inline js but not in external js file itself. :(

**Comment by megapctr** [comment]
IMO @PatrickHail's solution is worth mentioning in the README

**Comment by LvChengbin** [comment]
the `concealing` feature is still not working in my Vim.

**Comment by deniskabana** [comment]
@LvChengbin Try this:
>EDIT: feature now works, did not have "set cole=1" in my vimrc
https://github.com/pangloss/vim-javascript/issues/101#issuecomment-45543789

**Comment by LvChengbin** [comment]
@deniskabana Thank you a lot, but it can't solve my problem.
