### ISSUE TITLE
FlowType: generic syntax bug

### ISSUE THREAD

**Issue by unclechu** [pangloss/vim-javascript#1011]
An example:
```javascript
// @flow
import {Record} from 'immutable';
import type {IRecord} from 'generic/flowtype';
export default <T: Object>(defaults: T): IRecord<T> => Record(defaults)();
```
Screenshot:
![vim-javascript-flowtype-issue](https://user-images.githubusercontent.com/799353/28783011-5edc1758-7628-11e7-86b0-d138cacd89b3.png)

I realized that it happens because of generic:
```javascript
// @flow
import {Record} from 'immutable';
import type {IRecord} from 'generic/flowtype';
export default (defaults: T): IRecord<T> => Record(defaults)();
```
![vim-javascript-flowtype-issue-without-generic](https://user-images.githubusercontent.com/799353/28783034-6d0a3a30-7628-11e7-9e40-162e2bf8c309.png)

**Comment by unclechu** [comment]
Another example of the issue:
```javascript
declare class IRecord<T: Object> extends Record<T> {
	get<K: $Keys<T>, V>(key: K): V;
	getIn<K: $Keys<T>, V>(keys: Array<string>, d: ?string): V; // keys: Array<$Keys<T> + ?>
	merge<K: $Keys<T>>(obj: $Shape<T> | Map<K, any> | IRecord<T>): this;
	mergeDeep<K: $Keys<T>>(obj: $Shape<T> | Map<K, any>): this;
	mergeDeepWith(Function, obj: $Shape<T>): this;
	set<K: $Keys<T>, V>(key: K, value: V): this;
	toJS(): {[key: $Keys<T>]: mixed};
	toJSON(): T;
	toObject(): T;
	update<K: $Keys<T>, V>(key: K, updater: (value: V) => V): this;
	withMutations(mutator: (mutable: this) => mixed): this;
}
```
Screenshot (demonstrates broken method name highlighting and syntax error in `update` method):
![vim-javascript-flowtype-issue-2](https://user-images.githubusercontent.com/799353/28787606-4a0a4b70-7636-11e7-9833-c9c18bfc768f.png)

**Comment by amadeus** [comment]
This should be fixed now.
