### ISSUE TITLE
`yield` keyword highlighting bug when it inside brackets

### ISSUE THREAD

**Issue by unclechu** [pangloss/vim-javascript#1014]
I believe it was working fine few months ago.

An example:
```javascript
function* () {
	const token = (yield select()).getIn(['account', 'auth', 'account', 'token'], '');
	const token2 = yield select().getIn(['account', 'auth', 'account', 'token'], '');
}
```

Screenshot:

![vim-javascript-syntax-bug-yield-inside-brackets](https://user-images.githubusercontent.com/799353/28871965-66960886-77a0-11e7-912a-c9f047d8aecf.png)

**Comment by amadeus** [comment]
Should be fixed in `master`, thanks!
