### ISSUE TITLE
Word `console` in a color of string

### ISSUE THREAD

**Issue by vitaly-zdanevich** [pangloss/vim-javascript#1019]
Hi, please look at this screenshot - `console.log()` - is it correct color for `console`?

![screen shot 2017-08-07 at 8 59 20 am](https://user-images.githubusercontent.com/3514015/29014002-694a7c80-7b4f-11e7-8617-b09fe99ec71b.png)

**Comment by bounceme** [comment]
yes. we don't control color themes, only proper syntax recognition. that console got highlighted pink is incidental

**Comment by vitaly-zdanevich** [comment]
Can you recommend some theme for this plugin?

**Comment by bounceme** [comment]
i use https://github.com/justinmk/molokai
