### ISSUE TITLE
Highlight problem after "class"

### ISSUE THREAD

**Issue by den-s** [pangloss/vim-javascript#1027]
<img width="840" alt="screen shot 2017-08-16 at 1 08 08 pm" src="https://user-images.githubusercontent.com/4224714/29358720-b76a5b6a-8284-11e7-9d66-733b618a7c14.png">
After line 80 - highlight is broken.
If remove "class" or change it everything is ok!

**Comment by amadeus** [comment]
![please follow instructions](https://dl.dropboxusercontent.com/s/ezvniff9zdlfneu/New_Issue__panglossvim-javascript_2017-08-17_01-28-10.png?dl=0)

**Comment by den-s** [comment]
```
        const classes = travellers.map(traveller => traveller.pass.class);
        const classType = classes.reduce((type, classesItem) => (classesItem === 2 ? 2 : type), 1);

        if (notes) {
          reservationAvailable = notes.reduce((available, note) => {
            const key = note.key.toLowerCase();
            if (key.indexOf('rp') !== -1 || key.indexOf('rq') !== -1 || key.indexOf('rm') !== -1) {
              return true;
            }
            return available;
          }, false);
        }
```
