### ISSUE TITLE
Highlight problem after "class" again

### ISSUE THREAD

**Issue by den-s** [pangloss/vim-javascript#1028]
<img width="840" alt="screen shot 2017-08-16 at 1 08 08 pm" src="https://user-images.githubusercontent.com/4224714/29403879-4d3ff74a-8342-11e7-975c-d5aa84b3c1f3.png">

```
        const classes = travellers.map(traveller => traveller.pass.class);
        const classType = classes.reduce((type, classesItem) => (classesItem === 2 ? 2 : type), 1);

        if (notes) {
          reservationAvailable = notes.reduce((available, note) => {
            const key = note.key.toLowerCase();
            if (key.indexOf('rp') !== -1 || key.indexOf('rq') !== -1 || key.indexOf('rm') !== -1) {
              return true;
            }
            return available;
          }, false);
        }
```

**Comment by fatso83** [comment]
I don't see the problem in the screenshot? Care to explain? Is it the wrong color? What did you expect?

**Comment by den-s** [comment]
if change class to class_ for example:
![screen shot 2017-08-23 at 12 09 56 pm](https://user-images.githubusercontent.com/4224714/29608224-3fb057c8-87fc-11e7-8ce7-a98e2127b9fd.png)

**Comment by den-s** [comment]
more code:
![screen shot 2017-08-23 at 12 21 57 pm](https://user-images.githubusercontent.com/4224714/29608755-c6bdf800-87fd-11e7-9a7d-8bb2b084aa33.png)

![screen shot 2017-08-23 at 12 22 17 pm](https://user-images.githubusercontent.com/4224714/29608766-cc486bac-87fd-11e7-9e67-a915b3d6fad1.png)

      ```
  const classes = travellers.map(traveller => traveller.pass.class);
        const classType = classes.reduce((type, classesItem) => (classesItem === 2 ? 2 : type), 1);

        if (notes) {
          reservationAvailable = notes.reduce((available, note) => {
            const key = note.key.toLowerCase();
            if (key.indexOf('rp') !== -1 || key.indexOf('rq') !== -1 || key.indexOf('rm') !== -1) {
              return true;
            }
            return available;
          }, false);
        }

        if (reservationAvailable) {
          this.props.actions.fetchLegReservation({
            currency: variables.CURRENCY,
            numOfPassengers: travellers.length,
            travellerCount: travellers.length,
            reservation: 'RQ',
            originId: `00${leg.Origin.extId}`,
            destId: `00${leg.Destination.extId}`,
            departDatetime: departDatetime.format(isoFormat),
            arrivalDatetime: arrivalDatetime.format(isoFormat),
            countryList: travellers.map(traveller => traveller.pass.countries),
            class: classType,
            tripIdx,
            legIdx,
          });
        } else {
          this.props.actions.fetchLegReservationSuccess({
            tripIdx,
            legIdx,
            reservation: {
              error: { code: 'no-reservation' },
            },
          });
        }
      }
    }

```

**Comment by fatso83** [comment]
I think pushing more snippets is less helpful than writing two lines of text actually describing the problem you have. I'll have a guess at what you would write:

> _What did I expect would happen?_
> That a field with any reserved word, such as `class`, would be highlighted in the same color as any other field
> _What actually happened?_
> The field with a reserved name got a different color
> _How to reproduce?_
> See snippets and screenshots

**Comment by den-s** [comment]
I hope this will be enough:
![screen shot 2017-08-23 at 12 21 57 pm](https://user-images.githubusercontent.com/4224714/29610163-0a5a1ae0-8802-11e7-91cf-fc159ad14507.png)

**Comment by amadeus** [comment]
I can't seem to reproduce this.

![example](https://dl.dropboxusercontent.com/s/o3rqj2x7kcsltvv/_2017-08-25_15-34-20.png?dl=0)

Are you sure another plugin you have installed is messing with things?

**Comment by den-s** [comment]
removed all plugins...
I found it - javascript-libraries-syntax.vim
