### ISSUE TITLE
How to install this plugin with vundle?

### ISSUE THREAD

**Issue by yang286** [pangloss/vim-javascript#1029]
Hi Sir, is there any way to install this plugin with vundle??
thanks a lot.

**Comment by bounceme** [comment]
https://github.com/VundleVim/Vundle.vim#quick-start

**Comment by sam3k** [comment]
Created a PR for adding docs for Vundle installation for those of us using it but not too familiar with Vundle. https://github.com/pangloss/vim-javascript/pull/1056
