### ISSUE TITLE
Syntax highlighting breaks after use of a multi-line template string

### ISSUE THREAD

**Issue by scull7** [pangloss/vim-javascript#1032]
Hi, whenever I use a multiple line template string the syntax highlighting breaks. See the following screen shots:

1. Broken when using the multi-line template string in the `IsUnique` function.
![screenshot 2017-08-23 11 33 30](https://user-images.githubusercontent.com/234352/29632212-231083cc-87f7-11e7-9ded-3870d7934b92.png)

2. Fixed when I convert it to a single quoted string with escaping. But you can see the other broken template strings below.
![screenshot 2017-08-23 11 34 19](https://user-images.githubusercontent.com/234352/29632284-67dfb48c-87f7-11e7-85c0-f8027b47f91d.png)

**Comment by rsternagel** [comment]
I have the same issue and would appreciate a fix very much! Keep up the good work! 👍

**Comment by amadeus** [comment]
Please post a snippet of code that we can copy and paste that reproduces the issue. Based on the screenshot I think you don't have flow support enabled, which is probably causing your bug. Please see the readme for details

**Comment by scull7** [comment]
@amadeus That was the issue, sorry I missed that configuration option.  Thank you for the pointer in the right direction.[Readme.md](https://github.com/pangloss/vim-javascript/blob/master/README.md#configuration-variables).  Hopefully at least this will help anyone else with the same issue.
