### ISSUE TITLE
Uneven indenting past 2000 lines of code

### ISSUE THREAD

**Issue by Limegrass** [pangloss/vim-javascript#1034]
Editing a large object such as the one found in this JS file causes uneven indenting.

This can be seen in the following screenshot, where lines past 2000 had an extra level of indention relative to the expected level. The two objects 有 and 左 shown in this image are enclosed as part of a larger object called database.
https://puu.sh/xmRPx/a050914101.png

The file I was attempting to modify was a modified version of this file (same issue occurs)
https://github.com/retrazil/kanji_order/blob/master/database.js

Reported as requested in this Reddit thread.
https://www.reddit.com/r/vim/comments/6wv73k/weird_windows_indention_issue/

**Comment by bounceme** [comment]
try this : https://github.com/pangloss/vim-javascript/pull/1031
