### ISSUE TITLE
Indent wrong js file

### ISSUE THREAD

**Issue by chimung** [pangloss/vim-javascript#1037]
Hi,
I got a problem about indent source code by command "gg=G". Everything work great except this file
![vim-javascript](https://user-images.githubusercontent.com/7089484/30158981-488efdda-93f1-11e7-9268-539227597aa8.png)
this is my vimrc [https://pastebin.com/qjbF7X8U](url)
and version of vim [https://pastebin.com/d51w7WFt](url)

**Comment by bounceme** [comment]
need text to reproduce

**Comment by chimung** [comment]
It's [https://pastebin.com/L4jxpfzm](url)
Thank you for the quick reply!

**Comment by bounceme** [comment]
<img width="799" alt="screen shot 2017-09-07 at 9 27 06 pm" src="https://user-images.githubusercontent.com/9332107/30196189-7dcc3af4-9413-11e7-9bd9-66b97588f982.png">


My first guess is this is a syntax problem. second guess is (may be pastebin raw) the inconsistent tabs, line endings. Eslint is marking the whole file red for me, but im not using windows

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/commit/7198f32def8c9e5850e07a731faf673d045c5424
