### ISSUE TITLE
Which glyphs are the suggested underscore and noarg arrow func concealers meant to be

### ISSUE THREAD

**Issue by itsravenous-sky** [pangloss/vim-javascript#1040]
![screen shot 2017-09-08 at 09 05 54](https://user-images.githubusercontent.com/30408139/30202091-10abc05e-9475-11e7-98ee-548a31102d30.png)

They both appear in the README as ["Medium Bold White Circle"](http://graphemica.com/%F0%9F%9E%85)

**Comment by bounceme** [comment]
that website needs a more comprehensive font.

http://www.fileformat.info/info/unicode/char/1f785/index.htm

**Comment by bounceme** [comment]
symbola has those glyphs

**Comment by Billy-** [comment]
Weird.. I am using [Roboto Mono NerdFont](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Regular/complete/Roboto%20Mono%20Nerd%20Font%20Complete.ttf) and I'm seeing the same boxes as in @itsravenous-sky's screenshot (but in the terminal). I use this exact same font on my Ubuntu machine and it works fine (I am having this issue on a Mac).

I have little to no knowledge of fonts, but if this exact font works on Ubuntu how come those glyphs are missing on Mac? Or am I missing something?
