### ISSUE TITLE
Syntax messed up

### ISSUE THREAD

**Issue by kristijanhusak** [pangloss/vim-javascript#1055]
Hi,

I'm using https://github.com/sheerun/vim-polyglot, which uses this package internally for JS syntax.
From yesterday syntax messed up. Here's a screenshot from before:

![screenshot-before](https://i.imgur.com/Mc2lPXZ.png)

And after:
![screenshot-after](https://i.imgur.com/G6oQNoo.png)

When i checkout vim polyglot to this commit https://github.com/sheerun/vim-polyglot/commit/9bfde7574aa89a91b80ed9c993fc000cfc11aae7 everything works fine.

**Comment by bounceme** [comment]
we dont provide for anything outside of this repo
