### ISSUE TITLE
Indentation not working on OSX

### ISSUE THREAD

**Issue by Ellmen** [pangloss/vim-javascript#1066]
**vim:** 8.0.1050
**OS:** OSX 10.12.6
**vim-javascript:** e5769400addcc952032d90d5b751b2a794089c1d

As far as I can tell the indentation is not working at all. Indenting gives the default 8 space width tab. I am on OSX 10.12.6 using vim 8.0.1050 with pathogen and the only package in my bundle is vim-javascript. My vimrc looks like:

```
execute pathogen#infect()
syntax on
filetype plugin indent on
set backspace=indent,eol,start
set number
```

Also, vim-elixir's indentation works if I put it in my bundle and I have confirmed vim-javascript is being loaded through `:scriptnames` and `:verbose set autoindent?`

EDIT (with screen cap):

![vim-javascript indentation](https://user-images.githubusercontent.com/11081684/31833654-476fc302-b599-11e7-800d-fb1f76d5713c.gif)

**Comment by bounceme** [comment]
need a repro example

**Comment by Ellmen** [comment]
I added a screen cap to the description

**Comment by bounceme** [comment]
what does `:echom &indentexpr` =

**Comment by Ellmen** [comment]
GetJavascriptIndent()

**Comment by bounceme** [comment]
`:echom &indentkeys` ?

**Comment by bounceme** [comment]
also, your gif doesen't show anything wrong. The closing brace is indented to 0, then you open a newline, which gets indented...

**Comment by bounceme** [comment]
try putting the example text into another function or block

**Comment by bounceme** [comment]
you can tell me what you expect to happen aswell, meantime, there isnt anything wrong apparently

**Comment by Ellmen** [comment]
Alright - I assumed it would default to a 2-space tab like vim-elixir does but I guess that's configurable. If this the expected behaviour, closing is fine. Thanks!
