### ISSUE TITLE
Highlight is not good

### ISSUE THREAD

**Issue by juanibiapina** [pangloss/vim-javascript#1067]
Here's what my highlight looks like. There are barely any colors.

<img width="814" alt="screen shot 2017-10-22 at 10 38 33" src="https://user-images.githubusercontent.com/568764/31860913-c85f7be4-b722-11e7-9a63-c748acd05f2d.png">

I think I have everything configured correctly. So much that MacVim, terminal vim8 and neovim give the exact same result. True colors, etc etc. Everything is set properly. JSX highlight also works really well. I've also tried other colorschemes and they highlight the same pieces.

Am I missing something for javascript syntax only? Or does anyone adds extra config for the highlight groups?

Something similar also happens with vim-ruby: https://github.com/vim-ruby/vim-ruby/issues/355

**Comment by bounceme** [comment]
<img width="271" alt="screen shot 2017-10-22 at 11 43 10 am" src="https://user-images.githubusercontent.com/9332107/31865124-397efade-b71e-11e7-99ed-f51309835a51.png">


shows with `nord.vim` theme. it is hard to tell but the keys and vars have a different color than normal text. basicaly, every single token in my photo can has the potential to be highlighted in some way, may be hard to find a colorscheme author that desires such a thing tho

**Comment by juanibiapina** [comment]
I did not mean it is not possible. I just find hard to believe people are working like this all day long, so there must be a common solution out there that I can't find. Something that adds extra hi mappings to javascript or ruby groups.

**Comment by bounceme** [comment]
> Something that adds extra hi mappings to javascript or ruby groups.

that thing is the vimrc, unless u are assuming every possible combination of colors can be exactly the way u want in someone elses colorscheme. appearance is subjective
