### ISSUE TITLE
Vim occasionally freezes

### ISSUE THREAD

**Issue by jonsmithers** [pangloss/vim-javascript#1072]
I work with a lot of js code embedded in html. There are certain instances where vim just freezes forever (and maxes out 1 of my cpu cores). I reproduced it in a minimal vimrc, where vim-javascript is the only plugin. I believe I'm always able to unfreeze it simply by pressing `ctrl-c`.

Replicating this reliably seems a little difficult, but here's an attempt:

```html
<script>

Stuff.Stuff = {
    stuff: {
    otherstuff: Object,
    justmorestuff: Object,
};

</script>
```

Open this file as the _second_ html buffer. So, you could do something like `vim something-other-file.html this-file.html` and then `:bnext`. The `some-other-file.html` doesn't need to contain any javascript, but it appears that it _does_ need to be an html file. Then go to the `justmorestuff` line and press `cc` or `o` in normal mode or `=` in visual-line mode. In each case (`cc` or `o` or `=`), vim should freeze.

(using vim 8.0.1100 on MacOS, with vim-javascript at 3b21b5bade24c)

**Comment by bounceme** [comment]
change `L32` of indent/html.vim to:
`if !exists('*GetJavascriptIndent') || !exists('b:js_cache')`

**Comment by bounceme** [comment]
fixed in https://github.com/pangloss/vim-javascript/commit/158977b81525b19558fb1b2491f0eb92623ae265 (sorry, too lazy to fix this either in `indent/html.vim` or a seperate pr)

**Comment by bounceme** [comment]
fixed in master

**Comment by jonsmithers** [comment]
Awesome, thanks for the quick fix!
