### ISSUE TITLE
property initializers + template strings = broken syntax highlighting

### ISSUE THREAD

**Issue by mcjohnalds** [pangloss/vim-javascript#1075]
Template literal strings don't highlight correctly with the following code:

```js
class Foo {
  bar =
     `${x}`;
}

console.log(1)
```

<img width="115" alt="screen shot 2017-11-11 at 11 19 01 am" src="https://user-images.githubusercontent.com/4696749/32684711-2a26e786-c6d2-11e7-9f3a-2bed54354535.png">

This happens when only https://github.com/pangloss/vim-javascript is loaded.

Removing the newline after the `=` fixes things.

**Comment by bounceme** [comment]
property initializers aren't supported well here, mainly due to noone contributing proper support, and because they are just a proposal. I'd wait and see whether that proposal ever improves before using them even, as they are very loosely defined


closing because there are several related issues
