### ISSUE TITLE
Backticks not highlighting

### ISSUE THREAD

**Issue by Hayleyfire** [pangloss/vim-javascript#1077]
Since ES6, you can `surround your text in backticks` to declare a multiline string constant. Regular ordinary vim doesn't seem to implement this in its JS parser, which this plugin seems to say it adds. It doesn't seem to be working, though...

![backtick](https://user-images.githubusercontent.com/6166069/32762462-51a3b200-c8f1-11e7-8b12-d724ffcc4a16.png)

**Comment by bounceme** [comment]
not reproducible. there is a problem with your vim config
