### ISSUE TITLE
Is not loaded properly with vim native packages 

### ISSUE THREAD

**Issue by ahmedelgabri** [pangloss/vim-javascript#1080]
here is a minimal config trying to use [`minpac`](https://github.com/k-takata/minpac), but this doesn't work for some reason. All works fine with `vim-plug` though.

```vim
set packpath^=~/.vim
silent! packadd minpac

if !exists('*minpac#init')
  finish
endif

call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
call minpac#add('pangloss/vim-javascript')
```

**Edit:**
This is not related to `minpac` check this comment for more info https://github.com/pangloss/vim-javascript/issues/1080#issuecomment-352418599

**Comment by amadeus** [comment]
Not sure this is an issue for us since we work fine in every other package manager out there?

**Comment by ahmedelgabri** [comment]
@amadeus true, I was hoping maybe I can get some pointers on the issue. Especially that as far as I know minpac, is just a light abstraction on top of vim's packages feature.

**Comment by ahmedelgabri** [comment]
It's loaded but for some reason, not working properly

<img width="642" alt="screen shot 2017-12-06 at 21 21 23" src="https://user-images.githubusercontent.com/63876/33683585-a90281c0-dacb-11e7-8a4e-c862a394b9d2.png">

**Comment by ahmedelgabri** [comment]
@amadeus any pointers? `:scriptnames` looks fine?

**Comment by bounceme** [comment]
use a different plugin manager?

**Comment by ahmedelgabri** [comment]
@bounceme :) I'm already using a different one but wanted to move to minpac

**Comment by ahmedelgabri** [comment]
I did some more investigations & it seems that this has nothing to do with `minpac`, I have the exact same issue when by just using `vim`/`nvim` `:h packages` feature. And I think the problem is the order of which the plugins are loaded with `packages` vs `vim-plug` in my case, not sure to be honest if this is a `vim-javascript` issue or `vim-plug` issue to be honest.

Here is a screenshot side-by-side where I use vanilla `packages` _left_ vs `vim-plug` _right_ with only `vim-javascript` loaded with both. 

<img width="1679" alt="screen shot 2017-12-18 at 13 45 02" src="https://user-images.githubusercontent.com/63876/34106836-148c0786-e3fa-11e7-84d9-59425b15279a.png">

You can already see the difference. Here is how I tested this

## Vanilla `packages`

`packages.vimrc`
```vim
set runtimepath+=~/.vim-packages
set packpath^=~/.vim-packages
```
and installed `vim-javascript` as follows

```
git clone https://github.com/pangloss/vim-javascript.git ~/.vim-packages/pack/test/start/vim-javascript
```

and ran neovim

```
$ nvim -u ~/packages.vimrc
```

and `:scriptnames` 

```
 1: ~/packages.vimrc
 2: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/filetype.vim
 3: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/ftplugin.vim
 4: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/indent.vim
 5: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/syntax.vim
 6: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/synload.vim
 7: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/syncolor.vim
 8: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/gui_shim.vim
 9: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/gzip.vim
10: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/health.vim
11: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/man.vim
12: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/matchit.vim
13: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/matchparen.vim
14: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/netrwPlugin.vim
15: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/rplugin.vim
16: ~/.local/share/nvim/rplugin.vim
17: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/rrhelper.vim
18: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/shada.vim
19: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/spellfile.vim
20: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/tarPlugin.vim
21: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/tohtml.vim
22: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/tutor.vim
23: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/zipPlugin.vim
24: ~/.vim-packages/pack/test/start/vim-javascript/ftdetect/javascript.vim
25: ~/.vim-packages/after/plugin/javascript.vim
26: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/ftplugin/javascript.vim
27: ~/.vim-packages/pack/test/start/vim-javascript/after/ftplugin/javascript.vim
28: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/indent/javascript.vim
29: ~/.vim-packages/pack/test/start/vim-javascript/indent/javascript.vim
30: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/javascript.vim
31: ~/.vim-packages/pack/test/start/vim-javascript/syntax/javascript.vim
```

## `vim-plug`
`plug.vimrc`
```vim
set runtimepath+=~/.vim-plug
call plug#begin('~/.vim-plug/plugged')
Plug 'pangloss/vim-javascript'
call plug#end()
```

and ran neovim

```
$ nvim -u ~/plug.vimrc
```

and `:scriptnames` 

```
 1: ~/plug.vimrc
 2: ~/.vim-plug/autoload/plug.vim
 3: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/filetype.vim
 4: ~/.vim-plug/plugged/vim-javascript/ftdetect/javascript.vim
 5: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/ftplugin.vim
 6: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/indent.vim
 7: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/syntax.vim
 8: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/synload.vim
 9: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/syncolor.vim
10: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/gui_shim.vim
11: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/gzip.vim
12: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/health.vim
13: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/man.vim
14: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/matchit.vim
15: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/matchparen.vim
16: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/netrwPlugin.vim
17: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/rplugin.vim
18: ~/.local/share/nvim/rplugin.vim
19: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/rrhelper.vim
20: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/shada.vim
21: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/spellfile.vim
22: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/tarPlugin.vim
23: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/tohtml.vim
24: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/tutor.vim
25: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/plugin/zipPlugin.vim
26: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/ftplugin/javascript.vim
27: ~/.vim-plug/plugged/vim-javascript/after/ftplugin/javascript.vim
28: ~/.vim-plug/plugged/vim-javascript/indent/javascript.vim
29: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/indent/javascript.vim
30: ~/.vim-plug/plugged/vim-javascript/syntax/javascript.vim
31: /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime/syntax/javascript.vim
```

**Comment by bounceme** [comment]
line 30 and 31  ^^^ are the prob

**Comment by ahmedelgabri** [comment]
So vanilla `packages` has a bug or the plugin depends on a wrong behavior from `vim-plug`?

**Comment by bounceme** [comment]
dont know much about `packages` but you want to have the load order reversed, so this plugin is in effect

**Comment by ahmedelgabri** [comment]
Actually now I wonder if the current behavior that I'm used to is wrong (`vim-plug`, left in the screenshot)

because in the `packages` case, the loading order is right (builtin vim `syntax` first, then the plugin's `syntax` file) but it doesn't look right still. You can check `:h load-plugins` & `:h packages` for more info on the loading order.

**Comment by bounceme** [comment]
not really, because the first file loaded set `b:did_{syntax,indent}` which ftplugins are supposed to check and early exit, which is what we do too

**Comment by ahmedelgabri** [comment]
Ok, I'm closing this for now. Thanks very much @bounceme for the help.

**Comment by ahmedelgabri** [comment]
Here is an update on this & it's more complicated than what I thought. https://github.com/neovim/neovim/issues/8144 but still it confuses me that this is the only plugin that I'm having this problem with. Maybe something can be done?

**Comment by joshdick** [comment]
@ahmedelgabri @bounceme FWIW I am having this issue with Neovim 0.3.0 when trying to load as a native Vim 8 package. I can't tell whether the issue is with this plugin or with Neovim, but it might be worth checking out https://github.com/neovim/neovim/issues/8144 that @ahmedelgabri filed and linked above.

**Comment by shabbyrobe** [comment]
I had this problem too; this thread helped me: https://vi.stackexchange.com/questions/7598/how-can-i-run-a-ft-plugin-with-the-new-built-in-package-manager-in-vim

    set runtimepath^=~/path/to/dotfiles/vim
