### ISSUE TITLE
Highlights broken with template string when object key is a number.

### ISSUE THREAD

**Issue by gera2ld** [pangloss/vim-javascript#1082]
With JavaScript below:
```js
const b = true;
const a = {
  1: `/aaa/${b ? 'b' : 'a'}`,
};

a.b = b;
```

If the object key is a number, the template string in value will be broken.
![image](https://user-images.githubusercontent.com/3139113/33247581-1636a966-d35a-11e7-9ce9-2ec4103f6497.png)

**Comment by amadeus** [comment]
Cannot reproduce, perhaps another plugin is getting in the way?

![example](http://wtf.amadeus.wtf/monosnap/_2017-11-27_11-13-05.png)

**Comment by bounceme** [comment]
hmmm, it only works with the flow extension enabled tho

**Comment by amadeus** [comment]
Oh woah, good point. Weeeeird. I'll check it out.

**Comment by amadeus** [comment]
ez fix, thanks!
