### ISSUE TITLE
ES6 object literal function highlighting not working

### ISSUE THREAD

**Issue by korylprince** [pangloss/vim-javascript#1084]
The third part of this code doesn't highlight the function `b` like the others:

```
const thing1 = {
    a:{
        b() {
            return this === 1
        }
    }
}

const thing2 = new Object({
    a:{
        b: function() {
            return this === 1
        }
    }
})

const thing3 = new Object({
    a:{
        b() {
            return this === 1
        }
    }
})
```

This only seems to occur when the function is in a nested object and is in a parameter to a function.

![image](https://user-images.githubusercontent.com/559762/33296508-ae93389a-d3a1-11e7-9733-b152979e51c7.png)

**Comment by amadeus** [comment]
![example](http://wtf.amadeus.wtf/monosnap/_2017-11-27_16-47-02.png)

Seems ok on my end, any other plugins that might be getting in the way?

**Comment by korylprince** [comment]
Sorry! In trying to debug the issue, I realized that yes, `kien/rainbow_parentheses.vim` is causing this issue. Sorry for the noise, but hopefully this will help someone in the future. If I can get the two working together (or an alternative), I'll post it here.

Thanks for this plugin!

**Comment by korylprince** [comment]
So I was unable to make any of the popular rainbow syntax highlight plugins work. Then I stumbled across the pre-existing issue: https://github.com/pangloss/vim-javascript/issues/184 which I think covers the issue pretty well. Sorry for the noise.
