### ISSUE TITLE
Synax file is blocked by the default vim syntax file

### ISSUE THREAD

**Issue by WscriChy** [pangloss/vim-javascript#1089]
I have troubles starting the javascript syntax, because seems it is blocked by the default vim javascript syntax file.

/usr/local/share/vim/vim80/syntax/javascript.vim
~/vim/vim-javascript/Plugin/syntax/javascript.vim

How can I avoid this?

**Comment by amadeus** [comment]
Technically both files will source, but it should be the plugin first, and the the built in one will detect this and noop.

**Comment by WscriChy** [comment]
The order is defined by the `runtimepath` variable.
