### ISSUE TITLE
problem with backquotes usage (template literals)

### ISSUE THREAD

**Issue by arcollector** [pangloss/vim-javascript#1093]
This code 
```javscript
  hourArr = Array(12)
    .fill(0)
    .map((val: number, i: number): string =>
      i+1 < 10 ? `0${i+1}` : (i+1).toString()
  )

  minutesArr = Array(12)
    .fill(0)
    .map((val: number, i: number): string =>
      i*5 < 10 ? `0${i*5}` : (i*5).toString()
  )
```
looks like this

![screenshot at 2017-12-24 15-39-382](https://user-images.githubusercontent.com/1631140/34328577-fdcf80e2-e8c0-11e7-84ae-40a6baa0c488.png)

my `.vimrc`: https://gist.github.com/arcollector/4a0ffc2cc99fe609bcffa7647a5c2b7d

**Comment by amadeus** [comment]
Hmm, it appears to be working fine for me:

![example](http://wtf.amadeus.wtf/monosnap/_2017-12-24_13-51-49.png)

It's hard to say what exactly could be causing it, but perhaps try removing Rainbow Parenthesis and see if that help?

**Comment by arcollector** [comment]
hi

if i put the code inside a class,  the syntax hightlight dont work

```javascript
class Hello {

  hourArr = Array(12)
    .fill(0)
    .map((val: number, i: number): string =>
      i+1 < 10 ? `0${i+1}` : (i+1).toString()
  )

  minutesArr = Array(12)
    .fill(0)
    .map((val: number, i: number): string =>
      i*5 < 10 ? `0${i*5}` : (i*5).toString()
  )

}
```
