### ISSUE TITLE
Error with indentation inside script tags.

### ISSUE THREAD

**Issue by rmzg** [pangloss/vim-javascript#1098]
Given the following text in a .html file:
```
<html>
  <head>
    <style>
      .foo {
        width: 100px;
        height: 100px;

        //background-color: rgb(250,100,0);
      }
    </style>
  </head>
  <body>

    <script>
      let d = document.createElement('div');
      d.className = 'foo';
      document.body.appendChild(d);
    </script>

  </body>
</html>
```
If I place the cursor on the line `d.className = 'foo';` then press `o` a new line is added below and my cursor is placed at the very left edge of the buffer, position 0, instead of indented to the same spot as the rest of the lines inside the script tag.

Note that the `<script>` is indented twice with two tabs, the body with three tabs.
Vim is: `version 8.0.1401` and I'm using `vim-javascript` via the `Vundle` plugin manager. Reproducible with only the `vim-javascript` plugin loaded.

**Comment by bounceme** [comment]
I'll fix it soon, for now you can wrap your `js` in a block ( `{}` )

**Comment by bounceme** [comment]
fixed
