### ISSUE TITLE
"/*" in template literal causes all following lines to be formatted as comment

### ISSUE THREAD

**Issue by katylava** [pangloss/vim-javascript#1101]
```
const = `some/url/pattern/*`;

function thisLineIsFormattedAsComment() {
  const thisLineIs = 'stuff';
}
```
<img width="631" alt="_test_js_ _dsktp" src="https://user-images.githubusercontent.com/10575/36109287-8df9a5a4-0fe4-11e8-870a-0a686b12f5bf.png">

I am also using the plugin mxw/vim-jsx, with `let g:jsx_ext_required = 0`. When I open a .js file, the filetype is set to `javascript.jsx`. If I do `:set ft=javascript`, the template literal is then formatted correctly.

**Comment by amadeus** [comment]
Unfortunately I cannot reproduce using your snippet (I too also use `mxw/vim-jsx`

![example](http://wtf.amadeus.wtf/monosnap/_2018-02-12_11-35-41.png)

**Comment by katylava** [comment]
Ok, I'll dig deeper and see if it's another plugin. I did disable all other javascript-related plugins though.

**Comment by amadeus** [comment]
Upon further thought, it looks like something in your config is breaking template strings - I don't know your syntax color scheme, however I would imagine that that template string should be highlighted as a string. Thus the `/*` is being interpreted as a comment

**Comment by katylava** [comment]
Ok, it turns out I don't know how to disable other plugins 😛 when I'm using Plugged. It is vim-javascript-syntax causing the problem.
