### ISSUE TITLE
Syntax highlighting breaks when destructuring objects using computed properties

### ISSUE THREAD

**Issue by mikeycgto** [pangloss/vim-javascript#1105]
Consider the following JavaScript:

```js
function extract(type, obj) {
  const { [type]: { property } } = obj;

  return property;
}

// will return: 1
extract('foo', { foo: { property: 1 } });
```

#### Results

<img width="325" alt="screen shot 2018-02-21 at 11 06 55 am" src="https://user-images.githubusercontent.com/82063/36490887-5cb50690-16f7-11e8-8614-45d0ce3088da.png">

The `return` is not properly highlighted and code appearing after the destructuring fails to highlight correctly.

**Comment by wzrdtales** [comment]
Same issue exists with

```javascript
const [ { some: [thing] }] = [ { some: [ '123' ] } ];
```

**Comment by amadeus** [comment]
Thanks for the report, this issue should be fixed noe!

**Comment by amadeus** [comment]
The second comment is a separate issue tho

**Comment by wzrdtales** [comment]
you need me tp open a new one? Or will you do it by yourself?

**Comment by amadeus** [comment]
Is fixed in master now

**Comment by wzrdtales** [comment]
Thanks :) works.
