### ISSUE TITLE
Flow syntax issue with generic type params on class methods

### ISSUE THREAD

**Issue by nvie** [pangloss/vim-javascript#1107]
Minimal example to replicate:

```
class Foo {
  foo<T>(arg: T): boolean {
    // ...
  }
}
```

<hr>

<img width="514" alt="screen shot 2018-02-28 at 00 45 32" src="https://user-images.githubusercontent.com/83844/36761805-18b3777c-1c21-11e8-9873-d5e3c92fb26b.png">

**Comment by loyd** [comment]
Related:
https://github.com/pangloss/vim-javascript/issues/1004
https://github.com/pangloss/vim-javascript/issues/1011

**Comment by amadeus** [comment]
This should be fixed now.
