### ISSUE TITLE
Broken HTML highlighting

### ISSUE THREAD

**Issue by robertjk** [pangloss/vim-javascript#1111]
## The problem

This plugin breaks highlighting of HTML for which I rely on [*othree/html5.vim*](https://github.com/othree/html5.vim) plugin.

`data-*` attributes are highlighted only partially by Vim - only `data` prefix is styled as the other attributes, while the rest of the attribute name is styled like a tag name. See screenshot below.

![plugin-enabled](https://user-images.githubusercontent.com/12070821/37092678-045c07ca-220d-11e8-8ccc-347ffdd69858.png)

Below is screenshot of how it looks with *vim-javascript* plugin **disabled**. Everything looks fine now.

![plugin-disabled](https://user-images.githubusercontent.com/12070821/37089785-09fe53be-2202-11e8-87d2-546d8f2b95f2.png)

I tested it disabling all the plugins but *pangloss/vim-javascript*, *othree/html5.vim* and [*nanotech/jellybeans*](https://github.com/nanotech/jellybeans.vim) (color theme).

## Expected behaviour

I would expect *vim-javascript* plugin to not change in any way how HTML syntax is highlighted.

**Comment by jsit** [comment]
I can confirm this happens even with no other plugins loaded:

```
$ vim -u NONE
```
then:
```
:so ~/.vim/plugin/vim-javascript/syntax/javascript.vim
:set ft=html
:syntax on
```

Then enter the following HTML code:
```html
<html>
	<div data-foo-bar="test">
	</div>
</html>
```

`-foo-bar` is a different color from `data`.

`data` is identified as an `htmlArg`, which is linked to `Type`;
`-foo-bar` is identified as `htmlTag`, which is linked to `Identifier`

<img width="349" alt="screen shot 2018-04-22 at 6 09 13 pm" src="https://user-images.githubusercontent.com/643417/39100421-4fea3b34-4658-11e8-8734-8441b48fd17d.png">
