### ISSUE TITLE
Invalid highlighting after /* in quotes

### ISSUE THREAD

**Issue by barmaglot92** [pangloss/vim-javascript#1113]
![image](https://user-images.githubusercontent.com/3037173/37424143-d3210e66-27d0-11e8-950c-aa6c527da168.png)

Really `.../*` isn't comment.

**Comment by amadeus** [comment]
It looks like you got another plugin getting in the way, I cannot replicate this:

![example](http://wtf.amadeus.wtf/monosnap/_2018-03-14_12-00-13.png)

Also if possible, it's nice to include a copy-paste-able snippet so we don't have to type these out manually to try to replicate.

**Comment by barmaglot92** [comment]
Sorry for that, i agree with you.
I try to check you idea soon, thank you!

**Comment by barmaglot92** [comment]
I'm disabing all plugins

` const Koa = require('koa');
 const app = new Koa();
 const bodyParser = require('koa-bodyparser');
 const cors = require('koa-cors');
 const Router = require('koa-router');

 const router = new Router();

 // middlewares
 app.use(bodyParser({
     jsonLimit: '50mb'
 });
 app.use(cors());
 if (process.env.NODE_ENV !== 'DEV') {
   app.use(`${config.get('apiBaseUrl')}/*`, umsAuth());
 }

 // app.use();
 // add config and baseUrl

 app
   .use(router.routes())
   .use(router.allowedMethods());

 app.use(async ctx => {
   ctx.body = 'Hello World';
 });

 module.exports = app;
`

**Comment by barmaglot92** [comment]
sorry its my mistake
