### ISSUE TITLE
Make concealed characters respect syntax colors

### ISSUE THREAD

**Issue by filipekiss** [pangloss/vim-javascript#1120]
Is there a way to make the concealed characters respect the syntax coloring from the keyword they're concealing? I'd like for the `return` concealed below, for example, to be red:

| Concealed | Not Concealed |
|---|---|
| ![image](https://user-images.githubusercontent.com/48519/38512828-adb95c6e-3c02-11e8-91ba-55afa74f8070.png) | ![image](https://user-images.githubusercontent.com/48519/38512859-c91fd6b8-3c02-11e8-8e83-2293b326bcf4.png) |

I know about the `Conceal` highlight group, but that changes all the concealed chars. I wanted to make them the same colors as their respective keywords.

Thanks!

**Comment by amadeus** [comment]
I believe this is a limitation of vim. Gonna close this since I don't think there's much I can do :/
