### ISSUE TITLE
Indentation breaks in long function blocks

### ISSUE THREAD

**Issue by jdmnd** [pangloss/vim-javascript#1121]
Vim version: MacVim Custom Version 8.0.1522 (145) (installed via homebrew)

### Steps to reproduce:
- Open a javascript file
- declare a function at the top of the file
- insert 2000 lines in the function block (`2000o<ESC>`).
- insert a statement at the bottom of the function block. eg. `const x = 1;`
- re-indent the statement (`==`)

### What should happen:
The line is re-indented to 1 tab in from the left.

### What happens:
The indent is discarded.

This always seems to happen at ~2000 lines or more into a function definition, regardless of the function content. In my case, I have a very long IIFE containing a class definition.

**Comment by bounceme** [comment]
that is intentional, giant 'shallow' functions can be pathologically slow otherwise
