### ISSUE TITLE
String class fields mess up highlighting of when omitting semicolons

### ISSUE THREAD

**Issue by adrianhelvik** [pangloss/vim-javascript#1123]
*Requisite minimal reproducible example, formatted as plain text :*

    class Faulty {
      foo = 'bar'
      static doesNotWork1 = 'bar'
      static doesNotWork2 = "bar"
      static x
    }

In the class above, static is never highlighted.

<hr>

String properties without a trailing semicolon messes up the coloring of the next line.

**Comment by adrianhelvik** [comment]
Another case where strings mess things up:

    class Foo {
      bar = 'baz'
      method() {}
    }

method is not highlighted

**Comment by amadeus** [comment]
Interesting bug actually. If you add a blank line between the items, the syntax fixes itself. Thanks for the report, hopefully I can look into this soon

**Comment by adrianhelvik** [comment]
Awesome! :)

**Comment by adrianhelvik** [comment]
syntax region  jsClassValue             contained start=/=/ end=/\_[;}]\@=/ contains=@jsExpression

Another affected case is method decorators I believe.

**Comment by adrianhelvik** [comment]
Found the source of the bug.
This line swallows the newline:
`syntax region  jsString           start=+\z(["']\)+  skip=+\\\%(\z1\|$\)+  end=+\z1\|$+  contains=jsSpecial,@Spell extend`

**Comment by adrianhelvik** [comment]
Changing the line to this solved the problem:
`syntax region  jsString           start=+\z(["']\)+  skip=+\\\%(\z1\|$\)+ end=+$+ end=+\z1+  contains=jsSpecial,@Spell extend`

Notice that I added an extra end and removed `\|$` from the existing end regex.

**Comment by adrianhelvik** [comment]
I have submitted a pull request. This is a really strange issue though.
