### ISSUE TITLE
show line number for javascript files

### ISSUE THREAD

**Issue by bochen2014** [pangloss/vim-javascript#1124]
at the moment I have to do `:set number` to display line number;
I know I can call it in `vimrc` but I only want it for `javascirpt` files (ideally any file that has javascript syntax)

any suggestions? thanks

**Comment by bochen2014** [comment]
ok. I hacked it thru by adding `set number` to  `vim-javascript/after/ftplugin/javascript.vim`  and it works as intendend;

is there a way to do it without the hack? what's the recommended way to do so?

**Comment by amadeus** [comment]
This is not really something in scope of this plugin, but something you would add to your own .vimrc file.

Probably the best way to do is is something like this:

```
augroup javascriptsettings
  autocmd!
  autocmd FileType javascript,javascript.js setlocal number
augroup END
```
