### ISSUE TITLE
Highlighting breaks when return type colon has no space before it

### ISSUE THREAD

**Issue by mblarsen** [pangloss/vim-javascript#1125]
It happens only for ES6 functions shorthand in objects like in this example:

*Note: no space before return type colon is the default eslint value*

```
/** @flow */
const something = {
  doItForDenmark(): Object {
    return {
      key: 'value'
    }
  }
}
```

Everything inside the function block is now `jsFlowObject`; no matter what the return type is. (see first screenshot in the statusline)

<img width="912" alt="screen shot 2018-05-16 at 11 03 55 pm" src="https://user-images.githubusercontent.com/247048/40125638-f8343368-595d-11e8-8ad6-043dfc82f8a2.png">

When inserting a space before the colon it works:

<img width="912" alt="screen shot 2018-05-16 at 11 04 12 pm" src="https://user-images.githubusercontent.com/247048/40125748-3cbcd0d0-595e-11e8-8f26-ff0893c92cf4.png">

### Settings

```
let g:javascript_plugin_flow = 1
```

Theme used `nord`

**Comment by amadeus** [comment]
First off, thanks a ton for the thorough bug report with screenshots and a nice copy-pasta snippet!

Unfortunately I cannot seem to reproduce. You sure another plugin isn't breaking something?

![example](http://wtf.amadeus.wtf/monosnap/_2018-05-16_15-04-50.png)

**Comment by mblarsen** [comment]
Thanks for your sanity check. After reinstalling vim-javascript and polyglot I can no longer reproduce the error. Odd think is that I cannot get correct coloring with polyglot alone and AFAIK your plugin is the javascript plugin in polyglot no? At least it links to here https://github.com/sheerun/vim-polyglot

**Comment by mblarsen** [comment]
Ps: I love your 🐱s — I have a dachshund that helps me debug
