### ISSUE TITLE
`if` after `return` is highlighted as jsFuncCall

### ISSUE THREAD

**Issue by romgrk** [pangloss/vim-javascript#1126]
```javascript
function name(args) {
    if (condition)
        return

    if (condition)
        return
}
```
<hr>

![screenshot from 2018-05-22 12-12-43](https://user-images.githubusercontent.com/1423607/40375458-a3ddd412-5db9-11e8-9e0c-e2b9bad39f7e.png)

**Comment by bounceme** [comment]
can't believe you're the first to hit this bug haha,

**Comment by amadeus** [comment]
I have a fix that I think should work here, lmk if you notice any other issues
