### ISSUE TITLE
Handle indentation for mixed parens/braces

### ISSUE THREAD

**Issue by agriffis** [pangloss/vim-javascript#1132]
This is the indentation I'm trying to achieve:

```javascript
const r = myFunctionCall(longParameter1,
                         longParameter2)

const o1 = {
    k: v,
}

const o2 = Object.freeze({
    k: v,
})
```

The third case is the problematic one. I can mostly get what I want with `cino=(0,Ws` but the third case always indents as:

```javascript
const o2 = Object.freeze({
                         k: v,
})
```

Is there a combination of `cinoptions` that I'm missing to achieve the desired result?

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/issues/1114

**Comment by agriffis** [comment]
Oh, I have `Ws` but I need `W1s`, thanks
