### ISSUE TITLE
Syntax highlighting with template literals inside objects

### ISSUE THREAD

**Issue by mcqj** [pangloss/vim-javascript#1138]
*Requisite minimal reproducible example, formatted as plain text :*

const x = {
  test = `${SIMPLE}`,
  testb = 'very ordinary',
  testc = 'case';
};

Screenshot shows how syntax breaks after the template literal string.

<img width="200" alt="screen shot 2018-08-12 at 21 51 19" src="https://user-images.githubusercontent.com/5565612/44006288-eab81766-9e79-11e8-9509-bb6d0b2b1cf5.png">

**Comment by NoahTheDuke** [comment]
This is pretty annoying. I don't mind diving in myself, but I don't have any knowledge of how the syntax highlighting works for javascript. Any direction?

**Comment by amadeus** [comment]
Ummm, don’t you need to be using `:` not `”` inside an object?

**Comment by NoahTheDuke** [comment]
That example is wonky and broken, but here's a real-world example:
![screen shot 2019-02-05 at 1 20 15 pm](https://user-images.githubusercontent.com/603677/52295060-d9cd3800-2948-11e9-8771-6e173471f8a3.png)
If I [view the highlighting group](http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor) at the \`, it's a `jsObject`.

With my PR applied, it's a `jsTemplateString` and the syntax highlighting is correct again:
![screen shot 2019-02-05 at 1 23 38 pm](https://user-images.githubusercontent.com/603677/52295232-45170a00-2949-11e9-8799-59cc6278d37c.png)

**Comment by amadeus** [comment]
It looks like you are using flow annotations, do you have the flow setting on?

Also, do you have this plugin installed? https://github.com/mxw/vim-jsx

You'll need both at the very least.

**Comment by NoahTheDuke** [comment]
As I said in the PR, I did have my configuration messed up and in fixing that the highlighting corrected itself. Thanks so much.
