### ISSUE TITLE
Syntax highlighting issue with spread operator and condition

### ISSUE THREAD

**Issue by cdimitroulas** [pangloss/vim-javascript#1139]
*Requisite minimal reproducible example, formatted as plain text :*
![image](https://user-images.githubusercontent.com/20640274/44212306-e96e7f80-a162-11e8-9ff3-684f8b89eda5.png)

In plain text:
```js
const addProperty = true

const something = {
  ...(addProperty && { property: 'something' })
}
```

Additional info:
When running `:syntax list` the following are highlighted as errors:
- jsParensError
- xmlError
- xmlCommentError
- dtdError

Not sure if this is useful but though it might help!

**Comment by amadeus** [comment]
I can't seem to repro:

![image](https://user-images.githubusercontent.com/83376/68572411-2a168080-041a-11ea-9b6a-24b974b1b189.png)

If you can come up with another repro, feel free to comment again and possibly open this issue up again.

**Comment by cdimitroulas** [comment]
I can't reproduce this anymore either, it seems that some update has fixed it :) 

Thanks for looking into it though
