### ISSUE TITLE
Consider highlighting rule on method calls/definitions & overwrite rule not working

### ISSUE THREAD

**Issue by avocadoras** [pangloss/vim-javascript#1142]
I am trying to set this rule on `.vim/after/syntax/javascript.vim`

`" to hl '.' in between methods`
`hi MethodDot ctermfg=Red cterm=bold guifg=Red gui=bold`
`syn match MethodDot "\(\w\)\@<=\.\(\w\)\@="`

However, I cannot get it to work inside code blocks, only at the top level.
![screenshot 2018-08-29 15 09 35](https://user-images.githubusercontent.com/36335687/44818163-39a70200-aba5-11e8-98fb-8feaac69cfce.png)

Can this be added? I'm not sure why I cannot overwrite this rule. https://github.com/pangloss/vim-javascript/issues/410 asks for something similar but I am asking for the periods in between an object and method.

**Comment by amadeus** [comment]
Perhaps try changing the MethodDot line to:

```
syn match MethodDot "\(\w\)\@<=\.\(\w\)\@=" containedin=@jsExpression
```

**Comment by avocadoras** [comment]
yes, works very well. Thanks.
