### ISSUE TITLE
Period at end of comment causes next line to indent

### ISSUE THREAD

**Issue by agriffis** [pangloss/vim-javascript#1146]
If I end a comment with a period, then it causes the next line to indent:

```javascript
function foo() {
  // This is a comment.
    return 42
}
```

NVIM v0.3.1-1-g489d32f2b
vim-javascript dd84369

**Comment by bounceme** [comment]
can't reproduce

**Comment by agriffis** [comment]
@bounceme Thanks for checking. I bisected my vimrc and found that https://github.com/othree/javascript-libraries-syntax.vim causes the misbehavior.
