### ISSUE TITLE
Bad highlighting

### ISSUE THREAD

**Issue by CristoAMH** [pangloss/vim-javascript#1153]
## Edit
My terminal doesn`t support Italic.

## Main problem
As you can see arrows, parenthesis and brackets are wrong highlighted.

![captura de pantalla 2018-12-14 a las 16 10 14](https://user-images.githubusercontent.com/39212295/50014500-09e90200-ffbc-11e8-9dd3-b3e6ef24c0bd.png)

**Comment by bounceme** [comment]
i don't see any parentheses or brackets highlighted... or is there any thing i'm not seeing? if not it's your colorscheme which doesn't take advantage of the highlight groups provided by this repo
