### ISSUE TITLE
no setting for concealing tripple equals or tripple not equals

### ISSUE THREAD

**Issue by 1ak31sha** [pangloss/vim-javascript#1154]
*Requisite minimal reproducible example, formatted as plain text :*

<hr>

#### Optional: concerning jsx.
PLEASE PLEASE PLEASE make sure you have properly
setup and are sourcing this plugin https://github.com/mxw/vim-jsx

WE DO NOT support JSX automatically, you need another plugin to add get this
functionality.

Make sure the bug still exists if you disable all other javascript plugins
except the one noted above, mxw/vim-jsx

**Comment by 1ak31sha** [comment]
@bounceme i agree, this is a feature request

**Comment by cabaalexander** [comment]
@bounceme I think I can take this one 😬

**Comment by 1ak31sha** [comment]
update: i now use fira font which supports ligatures, such as triple equals, so i dont need to conceal anymore!
