### ISSUE TITLE
Nullish coalescing operator confuses surrounding syntax highlighting

### ISSUE THREAD

**Issue by jeffvandyke** [pangloss/vim-javascript#1164]
When working with syntax using <https://github.com/tc39/proposal-nullish-coalescing> (a `??` operator as a better alternative to `||`), highlighting gets confused on surrounding parentheses and braces. My best guess is that it's expecting a ternary statement to follow.

I gave fixing it a stab, but I'm not familiar enough with vim syntax highlighting to know what to do. Any help would be appreciated!

Example:
```
function nullishTest() {
    const obj = { a: 'a' };
    console.log(obj.b ?? 'empty');
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/6729124/55430146-50f30700-555b-11e9-8e3c-38dde1c53805.png)

**Comment by pbondoer** [comment]
I'm experiencing this as well, I'd be happy to look into it with some direction :)

**Comment by jeffvandyke** [comment]
@pbondoer As far as a stab at it, I think the problem lies somewhere in the "syntax/javascript.vim" file. My suspicion is the regexes around `jsTernaryIf` and `jsTernaryIfOperator`, but I'm unfamiliar with the vim syntax rules.

**Comment by amadeus** [comment]
Added in #1165
