### ISSUE TITLE
jsDestructuringNoise should include commas inside array destructuring

### ISSUE THREAD

**Issue by tandrewnichols** [pangloss/vim-javascript#1166]
I'm messing around with overriding some highlight groups and I'm noticing that `jsDestructuringBraces` _does_ include array destructuring symbols (`[` and `]`), which is fine, but `jsDestructuringNoise` _only_ includes `,` for object destructuring and not array destructuring.

E.g. if I do

`HiLink jsDestructuringBraces Delimiter`
`HiLink jsDestructuringNoise Delimiter`

Then

```js
function({ foo, bar }) {

}
```

has the braces and commas highlighted as "delimiter" but in

```js
function([ foo, bar ]) {

}
```

only the brackets are highlighted and not the comma. Small thing really since they're marked as "noise" by default, but it seems like they should be the same.

**Comment by amadeus** [comment]
Good catch! Fixed!
