### ISSUE TITLE
Javascript highlighting broken in recent update?

### ISSUE THREAD

**Issue by mcmillion** [pangloss/vim-javascript#1173]
Just noticed this after a recent update (maybe in the past week or so?):

<img width="155" alt="Screen Shot 2019-06-18 at 10 05 20 PM" src="https://user-images.githubusercontent.com/717799/59733937-30ab1e00-9215-11e9-8640-9e45ffdefd4c.png">

Notice the key highlighting. It changes in and out as you scroll. This happens with vim-polyglot but not with just vim-javascript. No other plugins are enabled, and I've tried other colorschemes as well.

**Comment by amadeus** [comment]
This happens with vim-polyglot but not vim-javascript? If that's the case then this issue should probably be raised on vim-polyglot?

**Comment by amadeus** [comment]
Also this plugin hasn't been updated since April...

**Comment by mcmillion** [comment]
Actually, I've narrowed this down to styled-components and have opened an issue there: https://github.com/styled-components/vim-styled-components/issues/64

I've had that plugin enabled for a while alongside polyglot with no issue, so it must be a recent change on their end.

**Comment by amadeus** [comment]
Styled components is probably sourcing a syntax file when javascript loads, therefore the issue is most certainly on their end.

If there's something they need from us to better support styled components, then have them open up an issue here and we can go from there.
