### ISSUE TITLE
No whitespace before less-than (<) symbol breaks highlighting

### ISSUE THREAD

**Issue by EthanRBrown** [pangloss/vim-javascript#1182]
Whenever the less-than symbol is used without a preceding whitespace (this includes both the less-than operator and bitwise left shift operator), syntax highlighting breaks.  All of the following break:

```js
const a = 3<x && x<10
const b = i<<3 && i>0
const c = i<10 && i>0
if(i<10) conole.log('boo')
do {} while(i<10)
for(let i=0; i<10; i++) {
  console.log('boo')
}
```

And adding a space before the `<` fixes the problem:

```js
const a = 3 <x && x<10
const b = i <<3 && i>0
const c = i <10 && i>0
if(i <10) conole.log('boo')
do {} while(i <10)
for(let i=0; i <10; i++) {
  console.log('boo')
}
```

(Note: I'm not suggesting it looks nice to have a space before the operator but not after, just demonstrating the minimal case to reproduce)

**Comment by amadeus** [comment]
This is most likely due to using jsx plugin as well?

**Comment by EthanRBrown** [comment]
I can reproduce with only `pangloss/vim-javascript` enabled.

**Comment by amadeus** [comment]
Forgot to mention - you probably have flow support on as well? I can't repro this issue without JSX and without Flow.

Unfortunately there's no real fix for those issues, it's sort of a tradeoff you have to accept with those plugins/features

**Comment by EthanRBrown** [comment]
Right you are; I was just disabling plugins, but when I removed `let g:javascript_plugin_flow = 1`, the problem went away.  This adds to our mounting evidence that we should ditch Flow.  Closing this.

**Comment by amadeus** [comment]
heh, at least replace it with Typescript! xD
