### ISSUE TITLE
Disable spelling in Strings

### ISSUE THREAD

**Issue by LandonSchropp** [pangloss/vim-javascript#1204]
I originally opened this in sheerun/vim-polyglot#468, but @sheerun directed me here instead.

I recently enabled the `spell` option in Neovim, and boy was I surprised at the number of spelling errors I found in my strings. While it's very useful to have them inside of comments, I personally think the number of normal use cases where strings do not conform to the spelling rules makes these settings less than helpful. I'd propose removing spell from the following syntax clusters:

```
jsString
jsTemplateString
jsObjectKeyString
jsObjectStringKey
```

The comment spell checking is very helpful.

**To Reproduce:**

Try any of these strings that are normal in JavaScript code.

```
"ramda"
"json"
"https"
"http"
"lodash"
```

**Comment by amadeus** [comment]
This seems fairly reasonable and easy to fix - just pushed a fix

**Comment by LandonSchropp** [comment]
Thank you! You're awesome.
