### ISSUE TITLE
Try-catch-finally not properly highlighted

### ISSUE THREAD

**Issue by cyrus-and** [pangloss/vim-javascript#1222]
This valid JavaScript snippet is not highlighted properly in that `finally` is not considered a keyword like the former two are:

```js
try {} catch {} finally {}
```

This one instead is highlighted correctly:

```js
try {} catch() {} finally {}
```

**Comment by thomasstep** [comment]
@amadeus I'm not exactly sure how issue tracking goes, but I think this can be closed now?

**Comment by amadeus** [comment]
Oops, I thought there was a comment or whatevs that woulda auto closed this, thx for the bump
