### ISSUE TITLE
Numeric separators

### ISSUE THREAD

**Issue by 89z** [pangloss/vim-javascript#1232]
This is a valid program:

~~~js
let n = 0x5555_5555;
console.log(n);
~~~

However this repo does not recoginze the input as a number.

https://github.com/pangloss/vim-javascript/blob/c7593e69bf64c3157b50cd0aea257c5abb8ae6a0/syntax/javascript.vim#L57-L59

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Numeric_separators

**Comment by amadeus** [comment]
Thanks for the report!
