### ISSUE TITLE
Is it possible to have concealing on typescript?

### ISSUE THREAD

**Issue by chris542** [pangloss/vim-javascript#1240]
Is there any way to use concealing on typescript?
Also, when i use Yggdroot/indentLine 's indentLine toggle, concealing on javascript file gets messed up
Is there anyway to have javascript conceal to use conceallevel 2?

**Comment by amadeus** [comment]
This is a javascript plugin, not a typescript plugin, so not sure I have a good answer with regards to typescript - this plugin isn't really used under those circumstances.

As for the second question, not really sure - I don't know the details of indentLine
