### ISSUE TITLE
Highlight breaking when there is a -- inside template literals

### ISSUE THREAD

**Issue by Ziggoto** [pangloss/vim-javascript#1241]
Every time I have `--` inside a template literals, my highlight understand the whole row starting from that point is commented.

![Screenshot 2021-09-21 at 14 34 53](https://user-images.githubusercontent.com/4368391/134180717-d27895b1-f799-40de-a1e3-a5fbec5dd8f5.png)

**Comment by amadeus** [comment]
I see this is already closed, but just in case anyone else comes along, I cannot repro this problem: 
<img width="898" alt="CleanShot 2021-09-21 at 12 37 05" src="https://user-images.githubusercontent.com/83376/134236404-ce5efd7d-5e73-4222-bd31-99055548a1ab.png">
