### ISSUE TITLE
Destruct nested array

### ISSUE THREAD

**Issue by ForkKILLET** [pangloss/vim-javascript#1246]
```plain
const [[a]] = [[1]]
```

![图片](https://user-images.githubusercontent.com/35412022/161406386-a0b8c295-f787-448c-8015-af9710150af9.png)

**Comment by amadeus** [comment]
I can't repro unfortunately:

<img width="287" alt="CleanShot 2022-04-04 at 16 38 55" src="https://user-images.githubusercontent.com/83376/161649656-31058909-5db1-44aa-8861-2e75b1c9cc67.png">

**Comment by cpmsmith** [comment]
Strange, I'm seeing this as well. Worth noting that I'm using this syntax via [vim-polyglot](https://github.com/sheerun/vim-polyglot/), but [its copy](https://github.com/sheerun/vim-polyglot/blob/master/syntax/javascript.vim) doesn't appear to have any changes.
<img width="209" alt="image" src="https://user-images.githubusercontent.com/9437625/205735406-e22db1c4-2280-413d-addf-28a5cc8097df.png">

**Comment by amadeus** [comment]
This is definitely an issue with polyglot. It doesn't repro with just this plugin, sorry.
