### ISSUE TITLE
dot chained calls are not indented correctly

### ISSUE THREAD

**Issue by nisaacson** [pangloss/vim-javascript#139]
When chaining calls together via the `.` operator, the following lines are not indented correctly

# Desired
```javascript
one()
  .then(two)
  .then(function() {
  })
  .fail(failHandler)
```

# Current
```javascript
one()
.then(two)
.then(function() {
})
.fail(failHandler)
```

Is there a way I can add a custom regular expression to perform additional indentation after the standard vim-javascript indent plugin has finished? Adding an additional two spaces to any line that begins with `.` would be a vast improvement

**Comment by sukima** [comment]
I don't think there is any reliable way to do this and not force semi-colons (without tricks like syntax). Now for me that's totally okay since I like semi-colons (for this very reason) but many developers prefer the more renegade style of flexing JavaScript's [auto semi-colon insertion (ASI)](http://jamesallardice.com/understanding-automatic-semi-colon-insertion-in-javascript/).

Thoughts?

**Comment by goatslacker** [comment]
If it starts with a dot, indent. This is probably not bullet proof however.

**Comment by sukima** [comment]
@goatslacker good point. I guess I took for granted that the dot can also be trailing. Investigating...

**Comment by goatslacker** [comment]
So I did this for leading commas and it worked for 80% of the use cases, not sure if dot would be the same case or not. I haven't fully thought this through.

Trailing dot wouldn't work, but I guess if the dot is trailing you could also indent. I think this is the current behaviour actually.

**Comment by sukima** [comment]
@goatslacker see PR #248. My dev tests show this as working.

**Comment by devm33** [comment]
Any update on this? I'd be happy to spend some time getting this working.

**Comment by sukima** [comment]
@devm33 No progress, I've learned to live with the dot as a line prefix not a suffix.

**Comment by lvarayut** [comment]
Any progress on this issue? I'm having the same problem.

**Comment by chalmagean** [comment]
+1

**Comment by Skinney** [comment]
+1

**Comment by randunel** [comment]
Had to build my own fix for the dot start https://github.com/randunel/vim-javascript. Would be nice to include something similar in this lib though.

**Comment by djmccormick** [comment]
+1

**Comment by ksmithbaylor** [comment]
@randunel Is that something you could make a pull request out of? How well does it work?

**Comment by mistercrunch** [comment]
+1

**Comment by bounceme** [comment]
a problem no longer

**Comment by jeffrom** [comment]
A hero in our time

**Comment by floscr** [comment]
This is broken in the inside objects: e.g:

```javascript
const obj = {
  key: one()
  .then(two)
  .then(function() {

  })
}
```

**Comment by pgraham** [comment]
So is this a case of squeaky wheel get the grease? I liked the original behaviour better, can we restore it?

**Comment by bounceme** [comment]
let s:opfirst = '^\C\%([<>=,?^%|/&]\|\([-:+]\)\1\@!\|\*\+\|!=\|in\%(stanceof\)\=\>\)')
