### ISSUE TITLE
Very slow performance in large Js files

### ISSUE THREAD

**Issue by PaBLoX-CL** [pangloss/vim-javascript#140]
I've been seeing a very slow performance when using js files. I just created an empty yeoman app, I tried to open the default `Gruntfile.js` (12K) and when I try to start writing it barely responds. I've tried to look where it was, and I found that disabling the `vim-javascript` plugin it start working normally again. Using the `:profile` commands looks like the culprit is the `GetJavascriptIndent()` function.

I'm using::

+ vim 7.4 1-17
+ arch linux x64
+ last version of vim-javascript

**Comment by amadeus** [comment]
So according to the vim wiki, it seems that `foldmethod=syntax` is notoriously slow, period. And when you couple that with our syntax file that's far more fine grained than most, it's not surprising that it can cause slowdown in insert mode.

As this really becomes more of an issue with vim itself, I am posting here with a potential workaround, and closing this issue:

http://vim.wikia.com/wiki/Keep_folds_closed_while_inserting_text

**Comment by toraritte** [comment]
Whoever finds this issue again: @amadeus' closing comment seems to be indeed true (with other languages as well). For me the solution was using [FastFold](https://github.com/Konfekt/FastFold).
