### ISSUE TITLE
Include with Vim

### ISSUE THREAD

**Issue by tpope** [pangloss/vim-javascript#177]
Is there any reason the indent plugin hasn't been sent for inclusion in the standard set of runtime files? The existing file is basically just `:set cindent` and explicitly marked as unmaintained. One email to Bram and this could be solved out of the box for everyone!

**Comment by chrisbra** [comment]
If you really want to distribute this with Vim, you need to give explicit permission to include and distribute this with Vim. And you probably want to reply [here](https://groups.google.com/d/msg/vim_dev/OXPA5QxOq_I/oMvPJCoeyN4J)

**Comment by goatslacker** [comment]
cc @pangloss who still has a lot of code written. We should include a license with this repo.

**Comment by pangloss** [comment]
Thanks Christian for bringing that to our attention.

Josh, I agree that a license should be included. Presumably there is a
standard one for vim projects? Anyway, at this point I think we should just
wait and use whichever license it's given when it's included in the Vim
distribution (if it is) to prevent further confusion.

**Comment by flannelhead** [comment]
Is including this package to Vim still considered?

**Comment by ninrod** [comment]
any news on this?

**Comment by amadeus** [comment]
Honestly I don't think anyone has really looked into this further than what you see here. As the current indent file stands, I believe it actually depends on our syntax file which means we would need both included with Vim. Currently we have been working on a ton of new experimental stuff and I would not be yet comfortable having a specific version locked into mainline vim until there has been more time to eek out bugs and improve things.

**Comment by bounceme** [comment]
I have a few ideas about how to remove the dependency on the syntax file. I think this should only be in vim if the entire repo is entered as well, and that would end up being one of the most complex language bundles in vim. Not sure if this will happen

**Comment by bounceme** [comment]
the dev version of the indent script doesn't use any 'specific to this repo' syn items except to increase performance

**Comment by bounceme** [comment]
here is some more info https://github.com/vim/vim/issues/949 . I don't know whether @amadeus still feels the syntax side of things is unstable, but the indent is no longer dependent on it. I would like to see the whole repo ,or a slightly slimmed version, in vim at some point

**Comment by bounceme** [comment]
should I make a script entry on vim.org like Bram suggested. there are already several outdated versions put up by @pangloss though,I wouldn't like to have several separate scripts on vim.org which point to this repo. Anyways we likely get way more "testers" here haha

**Comment by chrisbra** [comment]
I would answer Bram, that the script is used already here and that it already got some testing and go ahead and send it to Bram for inclusion. It should mention a proper contact date and a license, but then you should be okay

**Comment by amadeus** [comment]
@bounceme I've still come across a couple small issues with it at various times. I think it's something to do with how you cache indent? It's not very reproducible yet, but I think it's still worth sitting on for a couple more weeks to see if we can iron those issues out.

**Comment by bounceme** [comment]
I plan to add a few tiny changes soon, so I am fine with waiting, we should get this out to master (of this repo) so we get lots more testers

**Comment by bounceme** [comment]
Well, now might be a good time to submit the indent file, any bug reports or other input is appreciated

**Comment by bounceme** [comment]
Also, since there are more bug fixes in the develop version I'll be submitting that one. I know some people are on the develop branch, and there aren't any reported bugs there either

**Comment by bounceme** [comment]
https://github.com/vim/vim/pull/977

**Comment by ninrod** [comment]
Seems that bram commited the indent file [here](https://github.com/vim/vim/commit/0952131376a517fc12dc5ae908a97018b4ee23f0#diff-737260430acbe76222505f784f2fcba8L2)

**Comment by bounceme** [comment]
well, it's in vim now. only about ten lines from the old version were kept during my rewrite though
