### ISSUE TITLE
avoid highlighting keyword when used as property name in object literal

### ISSUE THREAD

**Issue by davidchambers** [pangloss/vim-javascript#180]
I'm not sure whether this is possible, but it would be great if we could avoid highlighting "default" in the following snippet:

```javascript
var config = {
  production: {foo: 1, bar: 1},
  development: {foo: 1, bar: 2},
  default: {foo: 1, bar: 2},
};
```

Pygments is failing here, too. :)

`case` and `default` are particularly problematic, but perhaps other keywords could be handled with a negative lookahead assertion along the lines of `(?!\s*:)`.

**Comment by amadeus** [comment]
This should be fixed with the new ES6/7 refactor.
