### ISSUE TITLE
add more support for es6 features

### ISSUE THREAD

**Issue by mihaisucan** [pangloss/vim-javascript#181]
`Map`, `WeakMap`, `Set` are missing in `vim-javascript`, but they are supported by Firefox. Some of these es6 features are also in chrome, currently behind a flag.

see https://developer.mozilla.org/en-US/docs/Web/JavaScript/ECMAScript_6_support_in_Mozilla

**Comment by arian** [comment]
Also highlighting for the `from` keyword in ES6 module `import`s would be nice.

```js
import bar from 'foo';
```

**Comment by amadeus** [comment]
@arian see #233 I'll merge it in shortly.

**Comment by arian** [comment]
@amadeus, long time no see! Thanks.

**Comment by amadeus** [comment]
@arian for sure brother, just note, it will be going into the `develop` branch initially, so you'll have to have that branch checked out for the bleeding edge

**Comment by BerkeleyTrue** [comment]
I have noticed issues with indenting when using arrowFunctions. Any plans on supporting new indentations styles?

**Comment by chiedojohn** [comment]
Could you also add highlighting for string interpolation?

**Comment by goatslacker** [comment]
This is a bit of an old issue.
