### ISSUE TITLE
Cannot indent code

### ISSUE THREAD

**Issue by md2** [pangloss/vim-javascript#189]
vim-javascript fails to properly indent the following code:
```javascript
var obj = {
	"a": {"b":
		[f(c,
		   d),
		   g(e,
		     h)]},
		     "i": {"j": 0}
};
```

**Comment by amadeus** [comment]
So, this is a bit strange to me. If you actually create line breaks where they belong, everything seems to work as expected. This has very strange line break places, so I am not sure if this is something we could reasonably fix. If you have some follow up information that can shed a bit more light and give us a better reason to fix this, let me know, we can certainly discuss re-opening.
