### ISSUE TITLE
Wrong indent after semicolon-less if statement

### ISSUE THREAD

**Issue by moll** [pangloss/vim-javascript#192]
The line after the following gets an indent of one level. There shouldn't be any indenting:
```javascript
if (!foo) return false
```

This is with MacVim Snapshot 70 both with `&regexpengine` of `0` and `1`. Latest master commit.

Cheers

**Comment by FrankFang** [comment]
+1

**Comment by moll** [comment]
This seems to be still an issue.

**Comment by camsteffen** [comment]
This is fixed with #293

**Comment by davidchambers** [comment]
Thanks, @camsteffen!
