### ISSUE TITLE
Comma first indentation

### ISSUE THREAD

**Issue by jlong** [pangloss/vim-javascript#198]
This plugin seems to prefer comma-first indentation that looks like this:

    var a = 1
      , b = 2
      , c = 3
    ;

I like to line up my commas so that they are on the same level as the closing semi-colon:

    var a = 1
    ,   b = 2
    ,   c = 3
    ;

It would be great if the plugin just observed my indentation and followed it instead of adjusting it to the first form.

**Comment by Pompeu** [comment]
if i use const or let, my code cant ident T_T

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/issues/198#issuecomment-166802619
please update as this is fixed

**Comment by bounceme** [comment]
the reason someone would install the indent script in this repo is for a better indentation,so, that you see another level created is no surprise.the specific alignment after the comma is also going to have to be manually added
