### ISSUE TITLE
Indentation fails when there is a plus at the end of the previous line

### ISSUE THREAD

**Issue by JelteF** [pangloss/vim-javascript#202]
When writing #201 I found out that general indentation fails when there is a plus at the end of the previous line.

When you press return after typing this:
```javascript
randomFunctionCall('blaaaaaaaaaaaaaa ' + 
                  'and some more bla',
```
 you get send back to the indent of `randomFunctionCall` instead of the indent of the last line.

**Comment by amadeus** [comment]
Should be fixed in `develop`
