### ISSUE TITLE
indent failed

### ISSUE THREAD

**Issue by huangyg11** [pangloss/vim-javascript#212]
```javascript
attributes = [
	{ 
	name : 'name', 
	description : 'a'   ,
}
]
```

**Comment by dragn** [comment]
I'm also annoyed by this issue. I've managed to fix that by removing `[` and '(' from `s:msl_regex`. But I believe, that It will break some other style. Could someone comment on that?

**Comment by amadeus** [comment]
@dragn I will play around with that change for a bit and see if I can notice and adverse side effects, thanks!

**Comment by amadeus** [comment]
We have just merged @dragn's fix into `develop`. Thanks for the fix, @dragn!

It should make it into master soon, but you can use the `develop` branch in the meantime.
