### ISSUE TITLE
vim-javascript no longer lets gq breaks long comments

### ISSUE THREAD

**Issue by beaugunderson** [pangloss/vim-javascript#226]
Previous to commit ca201905da0b44b703cd744e65d29bb9d3a11926 vim-javascript would not interfere with `gq`'s breaking of comments that were longer than textwidth into multiple lines, so for example, prior to the commit this works:

```
:set textwidth=20
// a comment longer than 20 characters
shift-v
gq
// a comment longer
// than 20
// characters
```

but after ca201905da0b44b703cd744e65d29bb9d3a11926 `gq` has no effect on the first example, and on the second example `gq` actually merges the three lines into one (overflowing the textwidth).

**Comment by raine** [comment]
Would love a fix!

**Comment by amadeus** [comment]
A fix has been merged into develop (and will get into master over the next week or so most likely). Please test. Will close this for now. And if the issue persists, just post here and we can re-open.

**Comment by raine** [comment]
Thanks, will test.

**Comment by parkwherever** [comment]
Was this issue fixed?

**Comment by amadeus** [comment]
Yes, it should be
