### ISSUE TITLE
Tag v0.10.0 Release?

### ISSUE THREAD

**Issue by minznerjosh** [pangloss/vim-javascript#246]
I noticed the last commit updated ```README.md``` to report version ```v0.10.0```. Should a release tag also be made?

**Comment by amadeus** [comment]
I just added the tag for now. Don't have time right now to make an official release though, would need to backtrack and see what highlighted changes have occured since 0.9.0 (it's a ton actually..)

**Comment by goatslacker** [comment]
I can add the changelog to the tag later
