### ISSUE TITLE
No indent after for loop without braces, due to semicolons

### ISSUE THREAD

**Issue by michaelpg** [pangloss/vim-javascript#253]
Consider:

    if (1)
            foo();
    for (var i = 0; i < 10; i++) {
            foo();
    }
    for (var i = 0; i < 10; i++)
    foo();

The last line should be indented, but it seems the semicolons in the brace-less `for` loop prevent the next line from being indented. I suspect the semicolons cause this problem because, for instance, `for (;;)` prevents the next line from being indented, but `for(,,)` does not.

**Comment by amadeus** [comment]
This should currently be fixed in `develop`
