### ISSUE TITLE
Indentation tests

### ISSUE THREAD

**Issue by dragn** [pangloss/vim-javascript#254]
Following up #179 I'd like to propose a solution for regression tests.
Please, take a look at https://github.com/dragn/vim-javascript/tree/feature/tests
To run tests:
```
cd tests
npm i
node index.js
```
Actual tests are located in `tests/indent-tests`. The idea is simple: we take a piece of code with correct indent, pass it through plugin and check that nothing has changed. I've put up some basic tests (a lot of them are failing though :) ).
Adding new tests will be super simple - just add another example file in `tests/indent-tests`.
I'd like to know the community opinion on this solution. I don't want to create a PR yet, cause putting failing tests in upstream does not sound as a good idea. But I could leave the green test only and then all bugfixes could be accompanied with a test cases.
BTW, it does not work on node 0.10 (because of child_process).

**Comment by goatslacker** [comment]
That's clever, I like it.

**Comment by amadeus** [comment]
Closing this as something of a dupe/related to #179
