### ISSUE TITLE
export class MyClass { ... highlights closing brace as error (es6)

### ISSUE THREAD

**Issue by euoia** [pangloss/vim-javascript#256]
When using the following ES6 syntax:
```
export class MyClass {
...
}
```

The closing brace is highlighted as an error. See screenshot.

![image](https://cloud.githubusercontent.com/assets/1271216/6701560/cb7ce908-ccf4-11e4-8246-431ada8747a9.png)

Description of the export statement: http://www.2ality.com/2014/09/es6-modules-final.html.

**Comment by nemtsov** [comment]
Same thing with exporting objects:

![export_objects_vim_bug](https://cloud.githubusercontent.com/assets/39958/8366100/dd21293a-1b5f-11e5-9ad8-06d5065b9c4f.png)

**Comment by gf3** [comment]
being highlighted as a `jsParensError`

**Comment by SirCmpwn** [comment]
Does not seem to have been fixed by #275 so far as I can tell.

**Comment by ccarpita** [comment]
@SirCmpwn are you sure you're on develop branch?  Otherwise please post some sample code that generates incorrect syntax and I can test locally.

**Comment by SirCmpwn** [comment]
Oh, whoops, didn't realize this was only in develop.

**Comment by nemtsov** [comment]
#275 resolves the issue for me.

**Comment by gf3** [comment]
it didn't for me, tried it a couple days ago

**Comment by ccarpita** [comment]
@gf3 can you post a test case that fails?  Also, sorry to ask, but are you 100% sure you're using the current `develop` branch?

**Comment by toddw** [comment]
Latest `develop` branch resolved the problem for me

**Comment by gf3** [comment]
previous issue seems to be fixed since i last tried, looking good!
