### ISSUE TITLE
Wrong indentation with cron syntax in object literal

### ISSUE THREAD

**Issue by emilabraham** [pangloss/vim-javascript#257]
I'm having an issue with the auto-indentation when I attempt to write cron syntax in an object literal. I believe it has to do with the `/` character. When I remove the `/`, the indentation returns to normal. But if I keep it in, then the next line becomes unindented. Maybe it is being treated like a block comment? Here are some screenshots:

With the `/`:
![screen shot 2015-03-26 at 10 41 20 am](https://cloud.githubusercontent.com/assets/1449809/6848662/f01a6770-d3a4-11e4-8eb4-6421eb321702.png)

Without the `/`:
![screen shot 2015-03-26 at 10 42 38 am](https://cloud.githubusercontent.com/assets/1449809/6848668/fc5d7072-d3a4-11e4-91ad-7d67fd73c7f7.png)

**Comment by amadeus** [comment]
This should be fixed in `develop`
