### ISSUE TITLE
Incorrect highlight for Flow function param type annotation containing function parameter

### ISSUE THREAD

**Issue by wincent** [pangloss/vim-javascript#259]
The `})` in the following sample gets matched and highlighted as a `jsParensError`, but it's correct ES6 syntax with [Flow](http://flowtype.org/) annotations:

```javascript
function someFunction(other: {key: () => void}): void {
  // ...
}
```

As a workaround, I can declare a separate type alias:

```javascript
type Frobnizter = () => void;

function someFunction(other: {key: Frobnizter}): void {
  // ...
}
```

Any thoughts on how to resolve this without reducing the ability of the `jsParensError` rules to detect and highlight actual errors?

**Comment by goatslacker** [comment]
We don't have flow support just yet, but this will be nice.

**Comment by martin-svk** [comment]
Hello, I see this is pretty old post but I guess `flow` syntax is still not supported, right? 
If so, are there any plans of supporting it and what is the time-frame then. Thanks.

**Comment by amadeus** [comment]
Closing this issue because I don't think this is something any of the current collaborators are willing to take on.
