### ISSUE TITLE
Support for ES6 class / object functions

### ISSUE THREAD

**Issue by mikew** [pangloss/vim-javascript#261]
ES6 has another syntax for functions. What was `{ someProp: function () {} }` can now be written as `{ someProp () {} }`.

![screen shot 2015-04-03 at 6 18 09 pm](https://cloud.githubusercontent.com/assets/4729/6989143/8b39e5a2-da2e-11e4-8c65-c82487b77d15.png)

They should be `jsObjectKey`, but currently they get parsed as `jsFuncCall`. I tried my hand at adding support but couldn't grok vim's syntax highlighting.

**Comment by sagax** [comment]
i think, it is perhaps necessary to do separate high light of syntax for javascript es6

**Comment by sagax** [comment]
for example **javascript6**

**Comment by arthurvr** [comment]
> i think, it is perhaps necessary to do separate high light of syntax for javascript es6

Why? It's the same language lol

**Comment by sagax** [comment]
it's true, but
but syntax highlighting differs in vim

**Comment by octref** [comment]
+1. Hope this could get fixed.

**Comment by qstrahl** [comment]
+1 to remind myself to do this

**Comment by gf3** [comment]
currently being highlighted as `jsFuncCall`

**Comment by qstrahl** [comment]
I'm pretty sure this is relatively easy to implement. I'll see if I can do it this weekend.

**Comment by wallacyyy** [comment]
Someone is taking a look on this ?
Don't know if it's too early, because it's a ES7 feature I think but:

![http://i.imgur.com/TzkYoEe.png](http://i.imgur.com/TzkYoEe.png)

**Comment by octref** [comment]
@wallacyyy 
Do you mind opening another issue for your request?

**Comment by wallacyyy** [comment]
@octref No problem ! :)

**Comment by josemarluedke** [comment]
:+1

**Comment by rblakeley** [comment]
Is this just about patching syntax highlighting or indention also?

Within an ES6 class, when I use `return` to get to a new line, the previous line indent shifts to the left automatically. It's horrible.

**Comment by octref** [comment]
@qstrahl 
Just curious, any progress?

**Comment by qstrahl** [comment]
@octref Haven't had time -- too much work! :<

**Comment by axelson** [comment]
+1

**Comment by ahoym** [comment]
+1

**Comment by girvo** [comment]
+1

**Comment by nicohvi** [comment]
+1

**Comment by ucokfm** [comment]
Here my temporary quick fix, edit **vim-javascript/syntax/javascript.vim**:

**at line 118 insert:**
`syntax match   jsClassMethod      /\<\(function\)\@![a-zA-Z_$][0-9a-zA-Z_$]*\>\s*\((\(\s*\<[a-z, ]*\>\s*)\)*\)\@=/ contained`

**at line 197 add jsClassMethod to existing list:**
`syntax cluster jsExpression contains=jsComment,...,...,jsClassMethod`

**at line 312 insert:**
`HiLink jsClassMethod          Function`

But i'm not sure if it is right to name it jsClassMethod. Maybe we can also name it jsObjectMethod or jsMethod.

**Comment by amadeus** [comment]
Should be fixed in `develop`
