### ISSUE TITLE
inline javascript indentation not working

### ISSUE THREAD

**Issue by shangsunset** [pangloss/vim-javascript#262]
Hi,

the inline javascript indentation is not working. is there a configuration for this or inline javascript is not supported by vim-javascript?

thanks.

**Comment by qstrahl** [comment]
I believe it was decided that inline javascript is the responsibility of the html syntax... but I'm starting to wonder if that was the right decision. Maybe we should reconsider that. Can we get some other contributors and users here to voice their thoughts?

**Comment by rockydd** [comment]
+1 Need this to work in html.

**Comment by arifb** [comment]
html syntax in vim doesn't properly indent javascript, so would love to see it added to this plugin

**Comment by amadeus** [comment]
Not sure if anything has changed, but some quick tests seem to show indentation in HTML files are ok for me? If not, someone please comment and I can re-open.
