### ISSUE TITLE
Highlights for strings, numbers, doubles and function keys

### ISSUE THREAD

**Issue by dvcrn** [pangloss/vim-javascript#267]
Hello,

I just installed this extension and am in the process of poking a bit around with it. The first thing I noticed was that strings, doubles, numbers and keys (if it is a function) are not highlighted. I'm wondering if I did something wrong or if this behavior is just not yet implemented. 

![screen shot 2015-05-09 at 1 28 42 pm](https://cloud.githubusercontent.com/assets/688326/7548674/99cd5fda-f64f-11e4-84af-dde4bf330ba7.png)

Here is an example how things look in atom

![screen shot 2015-05-09 at 1 29 26 pm](https://cloud.githubusercontent.com/assets/688326/7548675/a656b530-f64f-11e4-90b0-4c1126fae0dc.png)

**Comment by goatslacker** [comment]
Must be your color scheme.

**Comment by dvcrn** [comment]
Yup it was my color scheme. Sorry for that.
