### ISSUE TITLE
Arrow function only works if surrounded by parentheses

### ISSUE THREAD

**Issue by rightaway** [pangloss/vim-javascript#272]
The arrow gets highlighted fine in this case
```
(arg) => {}
```

But not when the parentheses are omitted.
```
arg => {}
```

**Comment by davidchambers** [comment]
Do we close an issue when the relevant PR is accepted, or once the commit is pulled into master?

**Comment by qstrahl** [comment]
Eh, let's close them sooner to avoid forgetting they exist.
