### ISSUE TITLE
Support for ES6+ property initializer with arrow function

### ISSUE THREAD

**Issue by wallacyyy** [pangloss/vim-javascript#282]
Example:

![http://i.imgur.com/TzkYoEe.png](http://i.imgur.com/TzkYoEe.png)
 
I think the "togglePanel" above should be highlighted.

**Comment by spencer-brown** [comment]
@amadeus why was this closed?

**Comment by bounceme** [comment]
highlighted with what highlight group?

**Comment by spencer-brown** [comment]
@bounceme it makes sense to me that the names of functions defined like this should be highlighted in the same way as functions defined like:
```js
{
  myFuncName() {
    ...
  }
}
```

**Comment by bounceme** [comment]
so you mean class methods? `id = () => {}` makes `id` a reference to a function, not a function name. inside a class, it would be member of the class, again not a function name: `function ob.method(){}` syntax does not exist. method shorthand names, well, it's shorthand for: `{myFuncName: function myFuncName(){}}` i believe. either way they're already supported by the syntax file. maybe for simple cases a regex can infer the type the variable is being assigned as but that is basically impossible with all the extremely permissive and vaguely defined features now in es6/7/proposals

**Comment by amadeus** [comment]
This is related to #975 which I also closed. Basically what you've given as a code example is a class expression. You could theoretically write any expression after the `=` operator, which could, or could not evaluate to a function. It goes beyond the scope of this project I think to start making assumptions about expressions like this.

**Comment by spencer-brown** [comment]
got it, thanks!
