### ISSUE TITLE
Intro docs Vundle install error 

### ISSUE THREAD

**Issue by udaiveerS** [pangloss/vim-javascript#283]
Plugin "pangloss/vim-javascript"

Error detected while processing /Users/udaiveer/.vimrc:
line   15:
E471: Argument required: Plugin 
but if you change it to 

Plugin 'pangloss/vim-javascript'

The error goes away and Vundle :BundleInstall successfully installs. 

I am using a Mac v10.10 vim 7.4 latest 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 27 2015 16:57:27)
MacOS X (unix) version
Included patches: 1-797

Maybe a change should be made and give warning to MacOS users. I was able to replicate the error by change the single quite to double.

**Comment by davidchambers** [comment]
Did you get to the bottom of the issue, @udaiveerS?

**Comment by udaiveerS** [comment]
Well I just though that maybe my vim settings made me get an error and I closed the issue. But your comment made me do some more research and I think that maybe we should change the 
`Plugin "pangloss/vim-javascript"` 
to 
`Plugin 'pangloss/vim-javascript'` In the main documentation page. If you copy paste like I do you will get an error following main docs. If you look at the Vundle main page all __Plugins__ are installed using single quotes. 
 
I have re-run the tests on my own `.vimrc` and if you use double quotes around any Plugin name you will get 

`E471: Argument required: Plugin ` 

for more proof you can reference main Vundle page 

![687474703a2f2f692e696d6775722e636f6d2f527565683743632e706e67](https://cloud.githubusercontent.com/assets/12993700/9191105/0593c532-3fb2-11e5-971e-5e4f3369b68d.png)

where all Plugins are instantiated with single quotes. Do you suggest I re-open the issue?

**Comment by davidchambers** [comment]
Aha! Thanks for investigating. This was actually fixed in #252 (on the develop branch) but the master branch does not yet reflect the change.
