### ISSUE TITLE
Badly indented code with `:` on a new line does not get reindented

### ISSUE THREAD

**Issue by netei** [pangloss/vim-javascript#284]
When running `gg=G`

on a file containing the following content:

 ```
conf.payload = R.type(conf.payload) === 'Object' ? JSON.stringify(conf.payload)
  : conf.payload;

  debug("Sending request %s to %s with %j", method, uri, conf);
```

The debug statement doesnt get indented to level 0, despite it being clear it is not on the same level as conf.payload

**Comment by netei** [comment]
Putting the : conf.payload; on the same line fixes, it, but it is still a bug

**Comment by amadeus** [comment]
This appears to be fixed in `develop`
