### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by Shriken** [pangloss/vim-javascript#285]
I'm a little puzzled as to why this plugin overrides my existing color configs. Is there a way I can un-override them?

**Comment by amadeus** [comment]
It doesn't override your existing color configs. It assigns matches to different groups than what the default JS syntax file does.

Basically the way syntax highlighting works in Vim, you create regexes or special keyword matches, that you give a highlighting group name to.  Then you link those highlighting groups to standard built in groups that Vim has.

So for example, here's a regex for jsNumber (basically a match for a number):

```
syntax match jsNumber /\<-\=\d\+\(L\|[eE][+-]\=\d\+\)\=\>\|\<0[xX]\x\+\>/
```

Later on in the file, we then link that group, `jsNumber` to one of Vim's built in global groups:

```
HiLink jsNumber Number
```

Our syntax file has looked at the meaning of these default syntax groups, and tried to match based on their meaning and intent. The built in JS syntax file played pretty fast and loose with these matches.

To change colors, your best best is to simply use the groups we create - `jsNumber` or whatever, and assign new colors. You can do this in your .vimrc or some other file you source.

If you wanted to change the color of `jsNumber` you would do something like this:

```
hi jsNumber guifg=#c500ff guibg=NONE gui=NONE
```

(make sure this AFTER you set your colorscheme)

This would ensure that your new color ONLY applies to our `jsNumbers` and not the global Number style.

Hopefully this all makes sense.

**Comment by Shriken** [comment]
Hm. Thanks for your help.
