### ISSUE TITLE
indent after one-line if statement without semicolon

### ISSUE THREAD

**Issue by camsteffen** [pangloss/vim-javascript#291]
This is incorrectly indented

    if(1) return
        console.log('foo')

**Comment by qstrahl** [comment]
Oh man, I have a feeling this one is going to be absurdly difficult to solve. Thanks for the report.

**Comment by cambunctious** [comment]
Admittedly I am not familiar with the code, but shouldn't this be pretty simple? If there is anything after the parenthesis, then that is the if block and the next line is not.

**Comment by cambunctious** [comment]
I decided to get my hands dirty.

Looking at `indent/javascript.vim`...

The problem is that `s:InOneLineScope(lnum)` evaluates true (non-zero) with the line `if(1) return`. I believe the function would be better named `BeginsOneLineScope`. Fixing it will require changing `s:one_line_scope_regex` so that it does not match when there is a statement following the `if/for/while/...`. I'm not very good at Vim regular expressions but I will keep at it unless someone wants to step in.

**Comment by cambunctious** [comment]
Related to #192 and #253

**Comment by qstrahl** [comment]
Thanks for the detective work, @cambunctious!

Using regexes for this stuff makes me throw up in my mouth a bit, but unless/until we can make use of the underlying syntax groups to do this stuff, it's pretty unavoidable... I have a knack for vim regex so I'll take a crack at getting something in place that won't break under the smallest amount of pressure, and hopefully we'll be able to put this to bed for now.

**Comment by qstrahl** [comment]
Also, with regard to:

> Admittedly I am not familiar with the code, but shouldn't this be pretty simple? If there is anything after the parenthesis, then that is the if block and the next line is not.

Corner cases. Consider the following:

```javascript
if (something) { doLittle(); } else
    bigNamedVariable.doTonsOfStuffHolyCrapThisMethodNameIsSoConvenientlyDescriptive();
```

I don't have a very good idea of how all those indent-related functions operate, but I assume that cases like the above could throw it for a loop. We can ignore those cases, but only until somebody posts an issue here complaining that it doesn't work. :P

**Comment by cambunctious** [comment]
Maybe `s:InOneLineScope(lnum)` could work something like this:

1. if the line ends with `else`, return true
1. If the line ends with `if|while|for` followed by a parenthetical, return true
1. return false

I see the tricky part is the parenthetical with regex. Is it possible to use the `%` command to find matching parenthesis? If so, start step 2 by detecting a `)` at the end of the line.

**Comment by qstrahl** [comment]
I will have to take a look at it, but using normal commands/moving the
cursor around sounds like it could break stuff, if it's even possible.
Don't worry, I'll figure something out. Just gotta dive into the code. =)

**Comment by evgenyzinoviev** [comment]
Just faced this problem. I've never used regular expressions in vimscript before, so I'm almost sure that my solution is absolutely wrong and dirty, but it seems to work for me for now (tested for a few seconds lol)

```
let s:one_line_scope_regex = '\<\%(if\|for\|while\)\>\s*([^)]*)\s*' . s:line_term
let s:one_line_scope_regex_else = 'else\s*' . s:line_term

...

function s:InOneLineScope(lnum)
  let msl = s:GetMSL(a:lnum, 1)
  if msl > 0 && (s:Match(msl, s:one_line_scope_regex) || s:Match(msl, s:one_line_scope_regex_else))
    return msl
  endif
  return 0
endfunction
```

**Comment by cambunctious** [comment]
I already have a pull request submitted for this.
