### ISSUE TITLE
function parameters not being highlighted

### ISSUE THREAD

**Issue by gabrielflorit** [pangloss/vim-javascript#294]
Looks like function parameters aren't highlighted. Is this the expected behavior, or is something wrong with my setup?

**Comment by qstrahl** [comment]
I believe this is currently expected behaviour, though they are tied to the syntax group `jsFuncArgs`, so if you wanted to highlight them, you could do something like this:

```vim
"" after/syntax/javascript.vim:
highlight link jsFuncArgs Identifier
```

**Comment by gabrielflorit** [comment]
Cool, thanks. Will test it out.
