### ISSUE TITLE
Fix snippet for vundle installation

### ISSUE THREAD

**Issue by megapctr** [pangloss/vim-javascript#296]
This is a very little thing. The readme says:
> Add to vimrc:
> `Plugin "pangloss/vim-javascript"`

However, the double quote (") in an inline comment in vim syntax - the given snippet causes a syntax error. Please replace double quotes with single quotes :)

**Comment by davidchambers** [comment]
Thanks for raising this issue. This was fixed on the __develop__ branch via #252.

Collaborators: Should we make documentation corrections against __master__ in future to avoid confusion? (We'd then manually merge __master__ into __develop__ to ensure the latter remains a superset of the former.)

**Comment by qstrahl** [comment]
That sounds cool to me. Working on develop is just supposed to protect
against uncaught breakages, and docs can't really break anything.
