### ISSUE TITLE
JSDoc syntax hilight issues with types defining

### ISSUE THREAD

**Issue by unclechu** [pangloss/vim-javascript#299]
May be `getLatLng~opts` in `@type {Object} getLatLng~opts` should be hilighted as `address` in `@property {?string} address`?

And see `@callback getLatLng~cb`, — `~cb` isn't hilighted, any reason for that? Or it just syntax issue?

![Demonstration](http://i.imgur.com/A7kf88w.png)

**Comment by Vekat** [comment]
I looked it up, since @type is a tag that only takes a type (and no parameters), no further highlighting is done after it.

**Comment by amadeus** [comment]
@vekat so does that mean this should be filed as a non-issue since it's working as expected? If not, please comment and I will re-open.
