### ISSUE TITLE
gq formats more than selection in HTML files

### ISSUE THREAD

**Issue by spadgett** [pangloss/vim-javascript#303]
When I type `gqit` inside the first paragraph to format just the text inside the tag,

```
<p>
  Lorem ipsum dolor sit amet, ignota omittantur at vel. In usu nostro mollis accusamus. No pro mazim liber, invenire cotidieque nec no, pro insolens erroribus torquatos ex. In eum esse equidem phaedrum, probo praesent duo te, ei brute saepe usu.
</p>
<p>
  <a href="">Learn more</a>
</p>
```

This is the result I see:

```
<p> Lorem ipsum dolor sit amet, ignota omittantur at vel. In usu nostro mollis
  accusamus. No pro mazim liber, invenire cotidieque nec no, pro insolens
  erroribus torquatos ex. In eum esse equidem phaedrum, probo praesent duo te,
  ei brute saepe usu.  </p> <p> <a href="">Learn more</a>
</p>
```

This seems to be caused by a custom `formatexpr`, `Fixedgq`, which is formatting lines past where it should. I see similar results using a visual selection where `gq` formats past the end of the selection.

**Comment by amadeus** [comment]
I don't think we apply our indent stuff to HTML files anymore? I could be wrong though

**Comment by BobWhitelock** [comment]
I'm also seeing the same issue, in my case with JSX files within embedded XML in Javascript. I'm using [vim-jsx](https://github.com/mxw/vim-jsx) as well as this plugin with these files; however the issue occurs when just this plugin is enabled, and doesn't without it. Thanks.

**Comment by bounceme** [comment]
I think we should consider removing the gq code from the indent file, or do people actually make use of it? https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L552

**Comment by bounceme** [comment]
this also could ruin code if used, it will create unclosed strings. maybe it could be updated to insert slashes before the newline, but is this thought to be literal?to make literal line-breaking you need to use '\n'. One other issue i have with this is that the help for 'formatexpr' suggests using an autoload folder, maybe to only be loaded when someone uses gq?

**Comment by amadeus** [comment]
I would prefer not to break `gq`, i find it to be very helpful

**Comment by bounceme** [comment]
is the html issue caused by this plugin though?

**Comment by bounceme** [comment]
this line probably should be sourcing the syntax file from ```$VIMRUNTIME``` instead of ours,
https://github.com/neovim/neovim/blob/master/runtime/syntax/html.vim#L170
I think this may be related to all the html issues we have. can someone test this and maybe email whoever maintains the official html file?

**Comment by amadeus** [comment]
@bounceme in relation to your comment, there's an override system that takes place, so our file will be sourced on that line. In fact, it's sourced first, then it falls back to the built in system `syntax/javascript.vim`.

**Comment by bounceme** [comment]
can anyone please explain what not splitting lines at blank spaces is important for in js? the reason for the gq code?

**Comment by amadeus** [comment]
@bounceme not sure I follow what you are asking?

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/201
maybe it is a python thing?

**Comment by amadeus** [comment]
@bounceme well splitting a string is arguably suspect since it would require some level of code manipulation?

**Comment by bounceme** [comment]
yea, you can't split strings ( other than template strings i think). you can only have strings which are contained in one line unless you escape the newline within the string with a '\'.
example 
```
'see the \
backslash'
```
which just prints 'see the backslash'
