### ISSUE TITLE
Time For A Merge

### ISSUE THREAD

**Issue by qstrahl** [pangloss/vim-javascript#304]
It's been a few months since the last merge back into `master`; I think it's time. We've got some people waiting on some features, and it's been a week since the last change to `develop` and I haven't noticed any breakages. Y'all agree?

**Comment by utix** [comment]
+1

**Comment by netei** [comment]
+1

**Comment by Delapouite** [comment]
Absolutely!

**Comment by davidchambers** [comment]
Sounds good to me.
