### ISSUE TITLE
Dose not indent with multiline template string

### ISSUE THREAD

**Issue by nukr** [pangloss/vim-javascript#314]
I am writing GraphQL in javascript but got some trouble

I expect
```javascript
`
  {
    products {
      name,
      price,
      description
    }
  }
`
```

but I got

```javascript
`
{
products {
name,
price,
description
}
}
`
```

How to solve it ?

**Comment by chiedojohn** [comment]
Any follow up on this?

**Comment by lvarayut** [comment]
Having the same problem.

**Comment by amadeus** [comment]
This should be fixed in `develop`

**Comment by chiedo** [comment]
Great @amadeus 
Any idea when this will be merged to master?

**Comment by amadeus** [comment]
@chiedo not sure, but if you are using a plugin manager with vim and want to more easily stay up to date, just cd into the vim-javascript directory and checkout the `develop` branch. The plugin manager should just keep you up to date from there!

**Comment by chiedo** [comment]
Thanks @amadeus :)

**Comment by bounceme** [comment]
Sorry but I will be altering the behavior slightly, manual indentation will be possible,as it is in strings, but this will be the initial indent:
```
`
  {
  products {
  name,
  price,
  description
  }
  }
`
```
this is more accurate as semantic meaning from strings isn't helpful for indenting

**Comment by skosch** [comment]
@bounceme I wonder if it's possible to make this a configurable option? The only reason I ever have multiline strings at all is for GraphQL queries, and this would be really useful to have.

**Comment by bounceme** [comment]
see the comments added in the last pr for instructions

**Comment by skosch** [comment]
Amazing. Thanks so much. I'll give it a try asap!

**Comment by bounceme** [comment]
i would recommend omitting the commas since these are going to be indented like blocks, with indent after operators etc.

**Comment by skosch** [comment]
This is working perfectly by the way, and saving me so much time. Thanks a million.
