### ISSUE TITLE
Wrong highlighting with nested Template Strings

### ISSUE THREAD

**Issue by simono** [pangloss/vim-javascript#316]
See attached Screenshots (Vim and MacVim).

![screen shot 2015-10-12 at 11 51 33](https://cloud.githubusercontent.com/assets/874148/10425391/a2d310d6-70d7-11e5-914f-535991b3eb1d.png)
![screen shot 2015-10-12 at 11 50 12](https://cloud.githubusercontent.com/assets/874148/10425392/a2d605b6-70d7-11e5-9f5f-5d7477e993c6.png)

**Comment by lencioni** [comment]
I ran into this problem and noticed that it looks like it might already be fixed in the develop branch. Do you have any idea on when this will hit master?

**Comment by simono** [comment]
Yes, this was fixed in #342. I'm not sure if a release is planned.
