### ISSUE TITLE
Flow null annotations break everything

### ISSUE THREAD

**Issue by eapache** [pangloss/vim-javascript#318]
I realize there is no flow support here, but annotations still tend to be mostly ignored at least, without breaking the syntax. The one exception to this is flow null annotations (e.g. `?Foo`) which get interpreted as the start of a ternary operator and destroy highlighting/indentation for the rest of the file.

As a temporary workaround I've made the start of a ternary `+? +` instead of `+?+` but I was wondering if there was a more correct way to fix this issue?

**Comment by amadeus** [comment]
I am personally not in favor if trying to add Flow support. However if there is another collaborator who'd like to take it on, we could certainly discuss re-opening this.

**Comment by amadeus** [comment]
Welp, it looks like I will start taking a look at this. I am now using Flow at work, so it's directly impacting me now 😄

**Comment by amadeus** [comment]
My plan will be to make it an opt in, so you will have to set a sort of global variable to enable support for it.

My initial findings when playing around with it however, there are certain cases that may be VERY difficult to support.

**Comment by amadeus** [comment]
I have started a branch here [js-flow-support](https://github.com/pangloss/vim-javascript/tree/js-flow-support) that you can follow along with. It's far from feature complete by any means, but it hopefully will fix some issues already right off.

**Comment by amadeus** [comment]
A basic version of Flow support has been added to `develop`. Check the README on `develop` for instructions to enable flow features. It's possible there are bugs, so if you can, please test.
