### ISSUE TITLE
":" in 'iskeyword' ?

### ISSUE THREAD

**Issue by qstrahl** [pangloss/vim-javascript#319]
I don't know when or why this was changed, but I just noticed we added `:` to `'iskeyword'`. This is dead wrong, does anyone know why this happened?

**Comment by amadeus** [comment]
I cannot confirm, `:` is not in iskeyword for me. Also it's nowhere in the syntax. I am guessing you might have some other plugin causing problems?

**Comment by qstrahl** [comment]
Whaaaaat? Let me get back to you on this one... vim is behaving strangely
for me today.

**Comment by WChargin** [comment]
Also cannot confirm: for me, `echo &isk` is `@,48-57,_,192-255,$` (`:` is `58`), and `git grep 'isk'` yields only `setlocal iskeyword+=$`.
