### ISSUE TITLE
JSDoc highlighting issue with record type syntax

### ISSUE THREAD

**Issue by raine** [pangloss/vim-javascript#320]
<img width="408" alt="screen shot 2015-11-03 at 9 42 32" src="https://cloud.githubusercontent.com/assets/11027/10903145/50dde46a-820f-11e5-836d-9ffba63e9ba3.png">

It thinks that the last curly brace is the parameter name

**Comment by qstrahl** [comment]
I suspect the issue is simply that we don't have support for record type
syntax. Adding it shouldn't be too difficult; it may even be possible to
just add the object literal syntax group inside the jsDoc comment syntax
group.
