### ISSUE TITLE
add "indentation" label

### ISSUE THREAD

**Issue by davidchambers** [pangloss/vim-javascript#325]
There are a number of indentation-related issues. I think it would be helpful to tag them as such. If I get a `:+1:` from one of the other maintainers I'll create the label and apply it to open issues where appropriate.

**Comment by amadeus** [comment]
:+1:

**Comment by davidchambers** [comment]
Done. About half our open issues are related to [indentation][1].


[1]: https://github.com/pangloss/vim-javascript/issues?q=is%3Aopen+is%3Aissue+label%3Aindentation
