### ISSUE TITLE
Make node.js 's  module highlight surpported.

### ISSUE THREAD

**Issue by lookforit** [pangloss/vim-javascript#327]
Hi
In the following code :  
```js
var fs = require( 'fs' );
fs.watch( 'foo.txt', function ()
{
    console.log( 'Start' );
} );
```

I just want `watch`  `log` highlight as function ,how can i customize  this ?

**Comment by WChargin** [comment]
You can add the following to your `.vimrc`:

```vim
autocmd FileType javascript syntax keyword jsBuiltins watch log
```

This means "whenever I open a JavaScript file, add `watch` and `log` as keywords under the `jsBuiltins` syntax group"; this group is highlighted like `eval`, `parseInt`, etc.

**Comment by davidchambers** [comment]
Thanks, @WChargin.
