### ISSUE TITLE
Please add an explicit license file to the repo

### ISSUE THREAD

**Issue by mbrukman** [pangloss/vim-javascript#338]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Thanks!

**Comment by davidchambers** [comment]
I believe the original author and all subsequent contributors will need to agree on a licence. This may take some time. ;)

**Comment by qstrahl** [comment]
Paging @pangloss ... and while I'm at it, let's page @davidchambers and @amadeus and @goatslacker 

My usual go-to license for vim projects is to release it under the same terms as vim itself, as laid out under `:help license`. What do y'all think?

**Comment by davidchambers** [comment]
> My usual go-to license for vim projects is to release it under the same terms as vim itself, as laid out under `:help license`.

Sounds good to me!

**Comment by WChargin** [comment]
:+1: for my contributions. Let me know if I need to sign anything…

**Comment by pangloss** [comment]
Oh, I thought there was a license in place... I'm happy with any open source license that you guys agree upon.

**Comment by amadeus** [comment]
Fixed in `develop`
