### ISSUE TITLE
jsDocParam problem

### ISSUE THREAD

**Issue by hushicai** [pangloss/vim-javascript#341]
see `@file`.

![qq 20160108234941](https://cloud.githubusercontent.com/assets/1249423/12202343/51d7435a-b664-11e5-9e6a-982aef09ee97.png)

Is there something wrong?I expect `arrow functions` as comment,but the first word `arrow` is treated as param,and highlighted as Label.

**Comment by amadeus** [comment]
So is the issue here that simply `@file` should not trigger a highlight after it, and should mimi `@author`?

I don't really have any experience with JSDocs, but I I think I have a super simple solution if this is all that's required?

**Comment by amadeus** [comment]
Fixed in `develop`
