### ISSUE TITLE
Is `Entity` a keyword I'm unaware of?

### ISSUE THREAD

**Issue by damionvega** [pangloss/vim-javascript#343]
![screen shot 2016-01-10 at 8 28 53 pm](https://cloud.githubusercontent.com/assets/7221494/12226413/d9d82902-b7d8-11e5-81a6-750a86a3b009.png)

**Comment by davidchambers** [comment]
It's DOM-related, [apparently][1].


[1]: https://github.com/pangloss/vim-javascript/blob/06326d595be14a78d82fdc99b73f9c1f8e869473/syntax/javascript.vim#L149-L151

**Comment by WChargin** [comment]
It's an [HTML entity](https://developer.mozilla.org/en-US/docs/Glossary/Entity), like `&amp;` or `&ldquo;`. The [API](https://developer.mozilla.org/en-US/docs/Web/API/Entity) says it's deprecated. It doesn't exist in Chrome 47.

**Comment by damionvega** [comment]
Would you like a PR removing `Entity` and adding `Buffer` for Node.js?

138: `syntax keyword jsGlobalObjects Array Boolean ... Buffer`

**Comment by davidchambers** [comment]
> Would you like a PR removing `Entity` and adding `Buffer` for Node.js?

These changes seem unrelated to me.

Feel free to submit a pull request to add `Buffer` to `jsGlobalObjects`. :)

**Comment by damionvega** [comment]
They are unrelated. I just figured since I'd already had this issue open, I could take care of both as they're minor.

OK, and keep `Entity`?

Also, I don't get highlighting for anything in line 34, perhaps it's just me?
`syntax keyword jsOperator       delete instanceof typeof void new in`

**Comment by damionvega** [comment]
Third time's a charm ;)

**Comment by davidchambers** [comment]
> I don't get highlighting for anything in line 34, perhaps it's just me?

These keywords are highlighted for me. Perhaps your colour scheme is at fault.

**Comment by damionvega** [comment]
I figured so. Thanks.

**Comment by zanona** [comment]
Weird, I don't get `instanceof` highlighted as well. Using `develop` branch here.
