### ISSUE TITLE
indentation using other than what is set for sw, ts

### ISSUE THREAD

**Issue by bounceme** [pangloss/vim-javascript#349]
```
foo(a(b,
      c))

if( a == b
   && c == d
 && e == f
   || g == h
     || i == j ) {
       a = b
       + c
       - d;
     }
```
These examples show that there can be situations where a line is indented from some offset based on the preceding characters, rather than depending on the users ts and sw choices. Also the second example is just very broken looking in general

**Comment by WChargin** [comment]
The first example is definitely the "expected" behavior: the continuation extends to the last opening delimiter in the line above, as in
```
someVeryLongFunctionCall(arg1,
                         arg2);
```
(Personally, I don't like it, and always prefer a constant `&sw` indentation for continuations, but that's what this indenter does.)

The second one is just busted, yeah.

**Comment by bounceme** [comment]
Well, i think that this is actually recommended for npm style code: https://docs.npmjs.com/misc/coding-style
but the returned text,and also the ending delimiter if it is on it's own line, should be aligned to the opening delimiter

**Comment by bounceme** [comment]
this is closable,having the vertical alignment seems like a benefit if it is what npm recommends.I'd like this indent script also vertically align the terminal delimiter however but that is another issue.Thank you!
