### ISSUE TITLE
Multiple require statements don't indent correctly

### ISSUE THREAD

**Issue by pmpbar** [pangloss/vim-javascript#355]
When using the single var syntax for multiple require statements the indentation is broken.
What it should do:
![image](https://cloud.githubusercontent.com/assets/3513897/13971959/fc27c4ea-f059-11e5-9448-19c51b01cd2c.png)

What it does:
![image](https://cloud.githubusercontent.com/assets/3513897/13971970/2525c8ba-f05a-11e5-92ab-3ab1712ad282.png)

**Comment by amadeus** [comment]
I believe this has been fixed in the `develop` branch since I currently cannot replicate it.

**Comment by pmpbar** [comment]
Coolio. Yeah I switched to the develop branch to check first.

**Comment by amadeus** [comment]
This should be fixed in `develop`
