### ISSUE TITLE
Syntax Highlighting issue with backticks, parentesis , dollar and curlybraces

### ISSUE THREAD

**Issue by chipironcin** [pangloss/vim-javascript#356]
<code>
set testVar = \`Include ${helper.join(varList.htaccessDir, \`${name}-htaccess.conf\`)}\`;
</code>

This sample coee breaks the syntax highlighting for all the document afterwards.
Removing curly braces in `${name}` fix the issue.

**Comment by amadeus** [comment]
I think this issue has been fixed with the recent changes merged into `master`. If not, please comment here and I can re-open.

**Comment by chipironcin** [comment]
Fixed! Many thanks!
(I pulled right before this issue to make sure about it)
