### ISSUE TITLE
jsParensError for parenthesized arrow function

### ISSUE THREAD

**Issue by davidchambers** [pangloss/vim-javascript#364]
I just noticed that the closing parens in the following line is marked as `jsParensError`:

    f(() => {});
              ^

The same applies in this case:

    f(() => {
    });
     ^

This also exhibits the problem:

    f((x) => {});
               ^

Interestingly, this does not:

    f(x => {});

When I have a bit more time I will run `git bisect` to determine which change is responsible.

**Comment by amadeus** [comment]
Good find, this is part of the challenge with arrow functions in general. Finding the specific commit is probably not necessary, I'll take a look.

**Comment by davidchambers** [comment]
It was something in #363. I've played around a bit, but so far haven't determined exactly which change is responsible.

**Comment by tomxtobin** [comment]
I just ran into this; it's 36f34b25d63211f1fab20c1f748a3dd070b4c270 according to `git-bisect`.

**Comment by tomxtobin** [comment]
Reverting [this change](https://github.com/pangloss/vim-javascript/commit/36f34b25d63211f1fab20c1f748a3dd070b4c270?diff=unified#diff-af5b29be69c5b34c00e40f13b7e92435R230) fixes the issue:
```diff
-syntax match   jsArrowFuncArgs  /(\(\k\|,\|\s\|\n\|\.\)*)\s\+\(=>\)\@=/ skipwhite contains=jsFuncArgs extend
+syntax match   jsArrowFuncArgs  /(\%(.\)*)\s*\(=>\)\@=/ skipempty skipwhite contains=jsFuncArgs nextgroup=jsArrowFunction
```

**Comment by tomxtobin** [comment]
It's the greedy `\%(.\)*` inside the arrow parameters' parentheses match. It's consuming too much of the line, including the closing `)` of the parameters.

A quick fix is changing that to the non-greedy equivalent `.{-}` — the Vim equivalent of PCRE's `.*?` — but then you're still matching unbalanced parentheses and whatnot. (We don't need the surrounding `\%(` and `\)` either way.)

**Comment by davidchambers** [comment]
Thanks for investigating, @tomxtobin!

> A quick fix is changing that to the non-greedy equivalent `.{-}` — the Vim equivalent of PCRE's `.*?` — but then you're still matching unbalanced parentheses and whatnot.

It's not valid to have `(` or `)` characters in the first elision of `(…) => {…}`, though, so we needn't worry about balancing parens. Perhaps all we need to do is replace the `.*` with `[^()]*` (or whatever the Vim equivalent of this PCRE is).

**Comment by amadeus** [comment]
@davidchambers I think it is valid to have something like:

```js
(x = (2 + 3)) => {}
```

Ideally the requirements for this regex are:

* Cannot be contained
* Must allow pretty much every type of expression
* Needs to be matched differently than `jsParen`
* Handle destructuring

Some crazier examples that make this regex really hard to do right:

```js
((x = (2 + 3)) => { return x; })();
((x = (true ? 1 : 3)) => { return x; })();
((x = (true ? event => event.response : () => { return error.response; })) => { return x; })();

var multiline = ({
	x = 2,
  y = false
}) => {
	console.log()
}
```

**Comment by davidchambers** [comment]
> I think it is valid to have something like:
>
> ```js
> (x = (2 + 3)) => {}
> ```

Oh! I wasn't aware of this, @amadeus. The problem is trickier than I imagined.

**Comment by amadeus** [comment]
I mean, to be fair, just because people could write such shitty and hard to read code, doesn't mean they should.

To paraphrase a brilliant friend of mine, we may be reaching the limits of a regex can interpret in a complex language.

**Comment by amadeus** [comment]
Like, ideally, `jsArrowFuncArgs` should probably be `region`, not a match. But in all my trial and error of trying out different regex combinations, and priorities, I have yet to find something that works in all cases.

**Comment by amadeus** [comment]
Ok, so this issues is pretty bad, and I think a good workaround in the meantime, until we can get it properly fixed is to comment out the `jsArrowFuncArgs` match that incorporates parenthesis. At the very least people won't see those major red errors.

**Comment by amadeus** [comment]
So, I've been playing with things a bit, and I have something that works pretty well, with a few caveats:

https://github.com/amadeus/vim-javascript/tree/lambda-experiments

Some notes:

1. It fixes all examples posted above - EXCEPT multiline
2. You cannot use parenthesis inside a destructuring statement (this includes creating another lambda statement

I've done some research into other editors, like Sublime and Atom, and all seem to break down if you incorporate new lines into the arguments section, so that's not a huge issue imo.

**Comment by amadeus** [comment]
A basic version of this is fixed in `develop`
