### ISSUE TITLE
Bad syntax highlighting for comments inside arrow function

### ISSUE THREAD

**Issue by ruiafonsopereira** [pangloss/vim-javascript#368]
After the last update, the comments inside arrow functions are not highlighted correctly. Consider the following screenshot as an example.

![screen shot 2016-04-10 at 16 33 14](https://cloud.githubusercontent.com/assets/3859158/14411235/fe68caf8-ff39-11e5-91ac-d34e5e6fc5f2.png)

**Comment by amadeus** [comment]
Is this an arrow function declaration within a class definition? If so, then it's a duplicate of #365 and I have a PR ready at #366

**Comment by amadeus** [comment]
Bump: Ya'll maintainers cool if I go ahead and merge this in? It's a pretty quick and simple fix.

**Comment by ruiafonsopereira** [comment]
@amadeus, yes, it is within a class definition. Before opening I took a look at that issue and I didn't see the comments in your example. My bad. Sorry for the duplication.

**Comment by ruiafonsopereira** [comment]
Fixed by #366 .
