### ISSUE TITLE
Bad syntax highlighting and braces-matching when comments with braces

### ISSUE THREAD

**Issue by chipironcin** [pangloss/vim-javascript#372]
A specific situation cause the syntax highligting to fail a bit and wrongly matches closing braces.
Happens when inside curly braces you have another function with curly braces that has a block comments with '@' and curly braces in it too.

Sample code, wrongly matching last curly brace:
```
class testClass {
  /**
   * Sample description
   * @returns {Object} - Object containing the database attributes: user, name, password, host and port.
   */
  testFunction(parameter) {
  };
}
```

**Comment by amadeus** [comment]
This should be fixed in `develop`

**Comment by chipironcin** [comment]
I attest this works on `develop` branch.
Thanks @amadeus 
I hope it gets merged soon 😛
