### ISSUE TITLE
Destructuring Arrays as function args

### ISSUE THREAD

**Issue by iansinnott** [pangloss/vim-javascript#376]
When destructuring an array within a function definition I'm seeing the array brackets getting highlighted as `jsFuncArgs`. However, object destructuring seems to work fine:

```js
function([ history, startTimeToken, endTimeToken ]) {
  //     ^                                       ^
  //     jsFuncArgs                              jsFuncArgs
}

function({ history, startTimeToken, endTimeToken }) {
  //     ^                                       ^
  //     jsFuncArgDestructuring                  jsFuncArgDestructuring
}
```

Any thoughts on what's going on here?

**Comment by amadeus** [comment]
There appears to be extra parenthesis in your example? However, your example still shows the issue correctly if I remove the extra opening parenthesis.

**Comment by iansinnott** [comment]
Ah yes, thanks for catching that @amadeus

**Comment by amadeus** [comment]
@iansinnott I have a fix at #377

**Comment by iansinnott** [comment]
Nice! Thank you @amadeus. That response time... 👏 

Looking forward to updating once it's merged.

**Comment by amadeus** [comment]
A fix for this has been merged into `develop`
