### ISSUE TITLE
Function call brackets closes incorrectly when have ES6 arrow function as argument

### ISSUE THREAD

**Issue by unclechu** [pangloss/vim-javascript#378]
I hope this screenshots will explain a lot:
![bug with ES6 arrow function](http://pix.toile-libre.org/upload/original/1460732419.png)
![works correctly with usual function](http://pix.toile-libre.org/upload/original/1460732448.png)
Here the text example:
- ES6 arrow bug: it**(**'_.blind(**)**', () => {}<em>)</em>;
- Usual function: it**(**'_.blind()', function () {}**)**;

**Comment by amadeus** [comment]
Yup, known issue. We'll get a fix out shortly!

**Comment by unclechu** [comment]
May be it's same issue:
![Issue demonstration screenshot](http://pix.toile-libre.org/upload/original/1460986854.png)
First `=>` wasn't highlighted.

**Comment by amadeus** [comment]
Things should be sort of fixed for now in `develop`.

@unclechu I am working on another PR to bring some of the old functionality back, do you mind posting your screenshot snippets as code examples? So I can work them into a test file for the next update?

The more crazier examples you can provide that you actually end up using, would be super helpful!

**Comment by jackfranklin** [comment]
@amadeus just wanted to say thanks for your work on this, and generally for your work on this repo. As a user it's awesome to see issues being fixed so quickly, and I really appreciate it :)

**Comment by unclechu** [comment]
@amadeus 
```javascript
const f = func('_.foo()', () => {});
```
```javascript
const async = require('async');
const fs = require('fs');
async.waterfall([
  (cb) => cb(null, 'file.txt'),
  (path, cb) => fs.exists(path, (exists) => cb(null, exists)),
], (err, exists) => if (err) console.error(err); else console.log('exists:', exists));
```

**Comment by unclechu** [comment]
@amadeus 
```javascript
const found = _.find(headers, (it) => /^Content-Length: \d\+$/i.test(it));
```

**Comment by amadeus** [comment]
@unclechu these are great, thanks!

**Comment by amadeus** [comment]
This issue should be fixed in `develop`

**Comment by unclechu** [comment]
Also arrow function single argument without brackets example:
```javascript
const found = _.find(headers, it => /^Content-Length: \d\+$/i.test(it));
```
```javascript
const async = require('async');
const fs = require('fs');
async.waterfall([
  cb => cb(null, 'file.txt'),
  (path, cb) => fs.exists(path, (exists) => cb(null, exists)),
], (err, exists) => { if (err) console.error(err); else console.log('exists:', exists) });
```

**Comment by unclechu** [comment]
@amadeus now it works nice, thanks a lot!
