### ISSUE TITLE
Object on ES7 Class Highlights Closing Bracket Red

### ISSUE THREAD

**Issue by daGrevis** [pangloss/vim-javascript#393]
![Preview][preview]

[preview]: http://i.imgur.com/h0T0Oix.png

When you define an object on ES6 class, closing bracket of that object will get highlighted in red. When you define a number, a string, an array or a lambda instead, everything works.

```javascript
class Thing {
    foo = {}
}

class OtherThing {
    bar = 42
}
```

You can reproduce this on `master` branch.

**Comment by eddiezane** [comment]
Also reproducible on `develop`

**Comment by amadeus** [comment]
I believe this is actually ES7 functionality? Which we've slowly been adding, but we are a bit behind there.

**Comment by xwendotnet** [comment]
I have same problem when lambda as second parameter.

 
![screen shot 2016-04-23 at 10 16 59](https://cloud.githubusercontent.com/assets/7343175/14758748/97994912-093c-11e6-8bea-940779842566.png)

**Comment by eddiezane** [comment]
@xwendotnet think your issue is different and fixed `develop`.

**Comment by amadeus** [comment]
@xwendotnet yes, that is a different issue and what @eddiezane said, it should now be fixed!

**Comment by amadeus** [comment]
*in the 'develop' branch

**Comment by xwendotnet** [comment]
@amadeus thank you, I will checkout that branch

**Comment by daGrevis** [comment]
> I believe this is actually ES7 functionality?

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes): “JavaScript classes are introduced in ECMAScript 6“.

> Which we've slowly been adding, but we are a bit behind there.

Thanks!

**Comment by amadeus** [comment]
@daGrevis I should have been more clear. We support ES6 classes. The syntax here is actually new stuff added into ES7. If you look through that entire article, you won't find any examples of 'prop = val'

ES6 Classes only support functions in the definition.

**Comment by daGrevis** [comment]
Ah, I see. My bad. :smile:

**Comment by amadeus** [comment]
Should be fixed on `develop`
