### ISSUE TITLE
Error on vim launch

### ISSUE THREAD

**Issue by aguerere** [pangloss/vim-javascript#405]
Hi guys!

I am getting the following error from vim upon loading a .js file, using your plugin.
I am running OS X 10.11.4, and the regular Terminal.app .

![vim-error](https://cloud.githubusercontent.com/assets/14084214/14906575/a2c7c842-0d86-11e6-8815-2259916943fa.png)

**Comment by bounceme** [comment]
Oh, it's a problem with the byte limiting, @amadeus. this is only available on a newer vim version. Default vi bundled with OS X is also too old

**Comment by bounceme** [comment]
if you want to manually fix this delete the all occurrences of '50' on line 100

**Comment by aguerere** [comment]
That works beautifully! Thanks @bounceme , shame on you Apple! Haha

**Comment by amadeus** [comment]
Gonna re-open this because we should come up with a fix for this. 

@bounceme are you familiar with any way to feature detect for this?

**Comment by bounceme** [comment]
https://github.com/kballard/vim-swift/blob/master/syntax/swift.vim#L12
 Maybe this is too much though

**Comment by amadeus** [comment]
This is a good start, I'll look into coming up with a fix for this over the next day or so

**Comment by starsirius** [comment]
+1 Thanks, guys!

**Comment by bounceme** [comment]
I also think we could look into ```h /\%#=``` for setting the old 'regexpengine' on early 7.4 versions of vim.then we could remove that section from the readme

**Comment by amadeus** [comment]
Should be fixed on `develop` branch.
