### ISSUE TITLE
Messed up function call highlighting

### ISSUE THREAD

**Issue by qstrahl** [pangloss/vim-javascript#406]
I'm not sure when this started, but recently the highlighting for function calls has been messed up. Example:

```javascript
myFunc(args) // "myFunc" highlighted as jsFuncCall; this is correct

if (condition) { // "if" highlighted as jsConditional; this is correct
  myFunc(args); // "myFunc" highlighted as jsFuncName; wrong!

  if (otherCondition) { // "if" highlighted as jsFuncName; double wrong!
    myFunc(args); // "myFunc" highlighted as jsFuncCall again; correct
  }
}
```

If you keep nesting `if`s, it keeps cycling between correct and wrong highlighting.

**Comment by amadeus** [comment]
Yup, this is a bug I just noticed last night introduced by c4ccee6950c465d2a78c9f0b284a6ccf1b48a1a4

I should probably comment those two new lines out, until I figure out a better fix.

**Comment by amadeus** [comment]
@qstrahl #409 fixes this issue. This only exists as a bug in `develop` currently.
