### ISSUE TITLE
Multi-line comment indentation broken inside parens, braces

### ISSUE THREAD

**Issue by metasyntax** [pangloss/vim-javascript#407]
I think this is due to a relatively recent change in master. Indenting the second and third lines of the comment now does this:

```
function foo() {
  /*
*
*/
}
```

Thanks for looking.

**Comment by bounceme** [comment]
Hey, it is kind of a naive solution but you can use #408,i'll be improving it when I can because I notice a few minor bugs already

**Comment by bounceme** [comment]
fixed in the develop branch
