### ISSUE TITLE
indentation bug

### ISSUE THREAD

**Issue by budkin** [pangloss/vim-javascript#411]
If there is a parenthesis between quotes within an `if` or `while` statement the next line is not indented, as in `if (c = "(")`
https://i.imgur.com/PEzpSwW.png

**Comment by budkin** [comment]
also, if a `case` in a `switch` statement contains an `if` or `while` the next line is unindented like it expects another `case`
https://i.imgur.com/1jIqKtt.png

**Comment by bounceme** [comment]
The second issue should be corrected in develop, can you confirm this?i will be try  to replace the regex based parantheses detection

**Comment by budkin** [comment]
Yes, the second issue is resolved in develop branch, switched to it, thank you

**Comment by bounceme** [comment]
On the parentheses issue, a solution to this would require several changes throughout the indent script,I invite anyone to enlist and do it otherwise you may be waiting a while, I recommend reading ```h search pair```
