### ISSUE TITLE
Conceal glyph problems

### ISSUE THREAD

**Issue by dmitriyK1** [pangloss/vim-javascript#415]
Some characters (arrow function, NaN etc.) doesn't work with my current font (Consolas), what font should I use in order to get them displayed properly?

![conceal](https://cloud.githubusercontent.com/assets/3366893/14995970/427d3f50-1180-11e6-8335-c6309744b0df.jpg)

**Comment by amadeus** [comment]
Unfortunately I do not use concealed characters, and therefore I cannot help you with this issue. I will leave this open for a few more days for better visibility, hopefully someone with more experience in this area can help, but will close it soon as it is outside the scope of this repo.

**Comment by dmitriyK1** [comment]
Thanks for the answer, actually I've resolved this problem recently using DejaVu Sans Mono font from here:
http://dejavu-fonts.org/wiki/Download

**Comment by m47h4r** [comment]
Sorry to re-open, I had the same problem but dejavu didn't seem to fix it for me (using Ubuntu with only fira-code installed additionally). I found that symbola font provides the noarg_arrow_function symbol. Just by installing it, gnome-terminal seems to use it properly whilst using fira-code as the primary font.
