### ISSUE TITLE
Object definition before constructor confuses highlighting functionality

### ISSUE THREAD

**Issue by jnsn** [pangloss/vim-javascript#418]
I am using [vim-javascript](https://github.com/pangloss/vim-javascript) and [vim-jsx](https://github.com/mxw/vim-jsx) to support ReactJS highlighting in Vim, but I'm suffering from some code highlight issues when defining objects before the constructor call. Then it looses the highlighting functionality.

Given the following code:

```js
import React, { Component, PropTypes } from 'react';

export defaults class User extends Component {
  static propTypes = {
    user: PropTypes.object.isRequired
  };

  constructor (props) {
    super (props);
  }

  doSomething () {
  }
}
```

When the `propTypes` object is defined, the highlighting gets confused, as illustrated on the following image:

![jsx-issue](https://cloud.githubusercontent.com/assets/348453/15029596/8b58c680-124e-11e6-804b-6bcab9c3d046.png)

Did I configure something wrong, or is it an unsupported construct, or am I missing some other configuration?

**Comment by amadeus** [comment]
So technically this is an ES7 definition, using `=` sign. Similar to #393

**Comment by jnsn** [comment]
I thought so.

You can close this as a duplicate then.

**Comment by bounceme** [comment]
going to close this for now at least
