### ISSUE TITLE
Indentation - Switch statement has multiple indentation errors

### ISSUE THREAD

**Issue by pappasam** [pangloss/vim-javascript#419]
Indentation is completely broken for the switch statement. 

**Problems:**
1) the first case statement indents forward a line
2) indentation for the first item nested below a case statement is much wider than my shiftwidth
3) all subsequent items are the same indentation as the original case line
4) subsequent case statements auto-indent one level in

I would normally just use a different plugin for indentation (for example, these issues are all absent from ason0x43/vim-js-indent). However, this plugin is a prerequisite for mxw/vim-jsx, so I'm stuck.

See the following example:

```javascript
function() {
  switch(h.test) {
          case hello:
                  var x = 2;
          return x;
  case world:
          var y = 2;
  return y;
  default:
          var z = 4;
  return t;
  }
}
```

I achieve the above result by typing code, without indentation modification on my end, with the following (purposely pared-down) .vimrc:

```vimscript
call plug#begin('~/.vim/plugged')

Plug 'pangloss/vim-javascript'

call plug#end()

augroup indentation_sr
  autocmd!
  autocmd Filetype * setlocal expandtab shiftwidth=2 softtabstop=2 tabstop=8
  autocmd Filetype python,c,elm setlocal shiftwidth=4 softtabstop=4 tabstop=8
  autocmd Filetype dot setlocal autoindent cindent
  autocmd BufRead,BufNewFile *.otl,*GNUmakefile,*makefile,*Makefile,*.tsv
        \ setlocal tabstop=4 softtabstop=0 shiftwidth=4 noexpandtab
  " Prevent auto-indenting from occuring
  autocmd Filetype yaml setlocal indentkeys-=<:>
augroup END
```

**Comment by bounceme** [comment]
develop branch,hopefully we'll have a merge to master soon
