### ISSUE TITLE
Improper indenting with template strings

### ISSUE THREAD

**Issue by eddiezane** [pangloss/vim-javascript#421]
Apologies if this is a duplicate. There are a few still open for indentation that might be the same cause.

Something is wonky when using template strings after a variable.

![screen shot 2016-05-06 at 2 34 53 pm](https://cloud.githubusercontent.com/assets/959573/15082834/ec25cf5e-1397-11e6-9dcf-b2afb006f7eb.png)

![screen shot 2016-05-06 at 2 35 03 pm](https://cloud.githubusercontent.com/assets/959573/15082836/ee9d0950-1397-11e6-800d-fa34ba92a513.png)

This appears to break things also.

![screen shot 2016-05-06 at 2 36 23 pm](https://cloud.githubusercontent.com/assets/959573/15082848/f8054796-1397-11e6-8c3c-ebcb1716f300.png)

![screen shot 2016-05-06 at 2 40 07 pm](https://cloud.githubusercontent.com/assets/959573/15082925/73fe9794-1398-11e6-8f75-b82dd0e11d49.png)

**Comment by eddiezane** [comment]
This is on `develop`

**Comment by bounceme** [comment]
can you paste some examples in markdown code blocks, whatever testing for this you can provide is helpful

**Comment by eddiezane** [comment]
```javascript
var foo

request({
  url: `http://myapi.com`,
    query: {

    },
    headers: {

    }
})

request({
  url: 'http://myapi.com',
  query: {

  },
  headers: {

  }
})
```

```javascript
request({
  url: `http://myapi.com`,
    query: {

  },
  headers: {

  }
})

request({
  url: 'http://myapi.com',
  query: {

  },
  headers: {

  }
})
```

```javascript
var a = `http://myapi.com`

  request({
    url: `http://myapi.com`,
      query: {

      },
      headers: {

      }
  })
```

```javascript
var a = 'http://myapi.com'

request({
  url: 'http://myapi.com',
  query: {

  },
  headers: {

  }
})
```
