### ISSUE TITLE
Indentation of switch case inside a callback

### ISSUE THREAD

**Issue by eddiezane** [pangloss/vim-javascript#423]
On `develop`.

```javascript
app.post('/events', function (req, res) {
  switch (req.body.foo) {
  case 'participant-join': // not indented far enough
    break // not indented far enough
    case 'participant-leave':
      delete db[req.body.CallSid]
      break
  }
})
```

<img width="519" alt="screen shot 2016-05-08 at 12 36 20 pm" src="https://cloud.githubusercontent.com/assets/959573/15099027/7ff961be-1519-11e6-8985-13b5f1802591.png">

**Comment by bounceme** [comment]
I see some problems with indenting with your example, but not actually the same as you, check to see what your cinoptions are, https://github.com/pangloss/vim-javascript/pull/400#issuecomment-214596214

**Comment by bounceme** [comment]
oh never mind, i also see this

**Comment by bounceme** [comment]
I suspect this is fixed!

**Comment by eddiezane** [comment]
Thanks @bounceme! You're crazy fast on these 😄
