### ISSUE TITLE
Incorrect highlighting when defining a computed method

### ISSUE THREAD

**Issue by paxunix** [pangloss/vim-javascript#425]
```
class Foo {
    [someThing]() {
        return 10;
    }
}
```
The current highlighter thinks the method body is jsClassBlock so its entire highlighting is thrown off.

**Comment by amadeus** [comment]
I believe this is some form of ES7 level functionality? I will look into it as I look to add ES7 support. Thanks for posting the issue!

**Comment by paxunix** [comment]
Computed method names (computed properties) is an ES6 feature:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

**Comment by amadeus** [comment]
In objects yes, I believe you are correct. Curly brackets in class definitions have a different set of rules that are being expanded upon in ES7

**Comment by amadeus** [comment]
Should be fixed in `develop`
