### ISSUE TITLE
Syntax support for ES property initializers

### ISSUE THREAD

**Issue by iansinnott** [pangloss/vim-javascript#433]
I'm not sure if this is a bug or simply something that is not yet supported, but it would be awesome to see support for [ES class property initializers](https://github.com/jeffmo/es-class-fields-and-static-properties). They are currently a stage-1 proposal but they make authoring React components much nicer.

I've tried this on both `develop` and `master`.

Example code:

```js
export class About extends React.Component {
  static propTypes = {
    children: PropTypes.any,
  }
  render() {
    return (
      <div className={cx('page')}>
        <div className={cx('siteTitle')}>
          <h1>About Page</h1>
        </div>
        <p>Welcome to the about page...</p>
      </div>
    );
  }
}

export class NotFound extends React.Component {
  render() {
    return (
      <div className={cx('page')}>
        <h4>Not found</h4>
      </div>
    );
  }
}
```

Here's how it's currently being highlighted. I annotated the screenshot with the syntax IDs of the highlighted parts of text:

![app_js______dev_js_redux-second-run_client_components__-_vim](https://cloud.githubusercontent.com/assets/3154865/15224383/e3e3ab64-182d-11e6-9249-caeddcb5da84.png)

Related: #393

**Comment by amadeus** [comment]
Should be fixed in `develop`
