### ISSUE TITLE
No syntax highlighting for curly and square braces?

### ISSUE THREAD

**Issue by asgeo1** [pangloss/vim-javascript#45]
Is it just me, or does the syntax highlighting included here not highlight curly and square braces?

The stock JS syntax file in Vim highlights the curly and square braces (but not normal parenthesis) fine - I figured this one would too!

Tested with both gVim and console vim with solarized and ir_black color schemes.

**Comment by zxlin** [comment]
Pardon the ignorance, how do I enable syntax highlighting for braces, because it is still not colored for me. Thanks in advance for the pointer!

**Comment by amadeus** [comment]
@zxlin you need to assign a color to either the main group `Noise` or to the individual groups themselves (if you want different colors for say square brackets vs curly brackets).

To assign a color to the `Noise` group, do the following in your `.vimrc`:

```viml
hi Noise guifg=#8200a8 guibg=NONE gui=NONE
```

`guifg` is for text color
`guibg` is for background color
`gui` is where you can apply `bold`, `italic`, `inverse`, or  `underline`

To assign colors to the separate groups themselves, you'd do the following:

```viml
" [ ]
hi jsBrackets  guifg=#8200a8 guibg=NONE gui=NONE
" ( )
hi jsParen     guifg=#8200a8 guibg=NONE gui=NONE
" { } - for object definitions only
hi jsBlock     guifg=#8200a8 guibg=NONE gui=NONE
" { } - for function definitions only
hi jsFuncBlock guifg=#8200a8 guibg=NONE gui=NONE
```

**Comment by zxlin** [comment]
@amadeus thank you very much for the pointer!
It didn't work initially because I'm using xterm-256color. 
Some research yielded the suggestion of using cterm* instead of gui* settings which worked like a charm!
