### ISSUE TITLE
incorrect indentation for after chained promise calls

### ISSUE THREAD

**Issue by wellsjo** [pangloss/vim-javascript#451]
Ever since 3208fc5, indenting after chained promise calls doesn't work correctly (everything shifts over a tab).  Example:

```javascript
someFunction()
.then(_ => console.log('hello'))
.then(_ => console.log('there'));

  // everything below here gets shifted over a tab >>

  /**
   * Comments
   */
  anotherFunction() {
   
  }

```

**Comment by bounceme** [comment]
fixed in my pr

**Comment by bounceme** [comment]
oh, not yet actually

**Comment by bounceme** [comment]
fixed in develop

**Comment by wellsjo** [comment]
awesome :-D

**Comment by wellsjo** [comment]
@bounceme I found another edge case. if there is a line between function calls, they are incorrectly shifted back 

Example:
```javascript
foo
  .bar()

// comment
.baz();
```

**Comment by bounceme** [comment]
i can't reproduce, though i'm working with some local changes right now

**Comment by bounceme** [comment]
maybe look for conflicting scripts?

**Comment by wellsjo** [comment]
what version of vim-javascript should I use to test?

**Comment by bounceme** [comment]
dev branch, or something is wrong with your setup possibly?

**Comment by wellsjo** [comment]
Does this break for you?
```javascript
func
  .anotherfunc()

/**
 *
 */
  function foo() {

  }
```

**Comment by bounceme** [comment]
no,function foo is aligned with func

**Comment by wellsjo** [comment]
must be my setup then. dang, do you have tips on how to debug this? it's really hard!

**Comment by zamN** [comment]
@wellsjo same exact setups? Same `.bashrc`'s, `.vimrc`'s, vim plugins, etc? Do you use a plugin manager for vim? If so I'd say nuke your vim plugin directory on Ubuntu and then try re-installing all your plugins. Do the same for Mac, but backup your 'working' `.vim` directory first. Doing this will help you isolate what is possibly conflicting.
