### ISSUE TITLE
Editor lockup when trying to insert line.

### ISSUE THREAD

**Issue by t0str** [pangloss/vim-javascript#454]
Hi
I'm getting an editor-lockup using your plugin. Basically if I try to create a line at a specific place in code it locks up. I have marked the space `###` in the file below. Problem happens with vim-latest and neovim-git-from-yesterday-evening.

```
import React, {
  Component,
  View,
  Text,
  Image,
  StyleSheet,
  Dimensions,
} from 'react-native';
### I can't enter a line here ('o' from the line above; 'O' from the line below) ###
### I can, however delete a line here ###
export default class MeinApoView extends Component {
  render() {
    return (
      <View style={{flex: 1}}>
        <Text>I'M A-MEI-ZING!!</Text>
      </View>
    );
  }
}
```

**Comment by bounceme** [comment]
hey you can checkout my branch for now. a better solution will hopefully come soon

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/tree/bounceme-patch-1

**Comment by t0str** [comment]
Thanks for the super-quick response. This solves my problem.

**Comment by bounceme** [comment]
i'll close this later, I have fixed this but it isn't in develop or master yet

**Comment by bounceme** [comment]
fix is in the dev branch

**Comment by patrick91** [comment]
I confirm that the fix works! Thanks!

**Comment by amadeus** [comment]
Closing this because it appears fixed. Please reply back if not.
