### ISSUE TITLE
Allow no change for arrow function

### ISSUE THREAD

**Issue by lewisdiamond** [pangloss/vim-javascript#456]
When using vim-javascript, my arrow function characters become misaligned:
![screenshot from 2016-06-01 11-10-06](https://cloud.githubusercontent.com/assets/1375600/15714696/853acc34-27e9-11e6-955d-72bf421c73eb.png)
This is the normal (aligned) version.
![screenshot from 2016-06-01 11-10-33](https://cloud.githubusercontent.com/assets/1375600/15714707/9411c82a-27e9-11e6-93af-6604c21c9931.png)

I'm not sure if it's because it's in bold.
I tried `let g:javascript_conceal_arrow_function = ""`, `let g:javascript_conceal_arrow_function = "=>"`, `unlet g:javascript_conceal_arrow_function`.
They all work (because it crashes) but generate an error when loading a file.

Is there a workaround/variable I can set to fix this?

**Comment by bounceme** [comment]
color schemes can make text bold, maybe try another to see

**Comment by amadeus** [comment]
Yeah, I am pretty sure you have some sort of bold effect happening here. Will close this for now, but if it's not the case please comment and I can re-open.
