### ISSUE TITLE
Suggestion: Could it follow the Standard style ?

### ISSUE THREAD

**Issue by yormi** [pangloss/vim-javascript#461]
I have a couple of issues with indentation.

Using the ...variable (spread operator) in an array or object on multiline for instance.

I'm not sure what is the style you guys want to follow with indentation. I was thinking that [Standard](https://github.com/feross/standard) would be a wise choice.

At the same time, is the spread operator thing an issue that you plan to work on ?

EDIT: I almost forget to thank you for the work. Thanks !

**Comment by bounceme** [comment]
can you give an example? an example for what you mean with the standard recommendation would be helpful

**Comment by bounceme** [comment]
guessing by my results with this file as a measure  https://github.com/feross/bittorrent-dht/blob/master/client.js we have support already for 'standard' js

**Comment by yormi** [comment]
I had few tiny problems but I updated lately and since then I think the indentation with ES6 spread operator is my only problem (no instances of this in the measure file):
```javascript
let example = [
  ...someObject,
  somethingElse
]
```

Instead of giving the above, the indentation change it for:
```javascript
let example = [
  ...someObject,
somethingElse
]
```

And, as you probably understood, this does not follow standardjs convention. MOreover, when `somethingElse` is an object literal instead of a variable, it makes it very not fun at all to read ;)

**Comment by bounceme** [comment]
most operator edge cases are caused by mixing operator first style with operator end style.maybe the spread operator is a special case though. moving the comma to the start of line three should fix your immediate issue

**Comment by yormi** [comment]
Ok thanks for the work around but I think I prefer just fix it by hand and wait for the fix. If I may ask, do you plan to fix it ? :)

**Comment by bounceme** [comment]
i already have haha

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/462

**Comment by yormi** [comment]
My hero ! haha

Yep it seems to work ! Thank you !

Should I close the issue or wait that the PR is merge ?

**Comment by bounceme** [comment]
i'll merge it to develop, seems to be pretty safe

**Comment by yormi** [comment]
Perfect !

Thanks again :)

2016-06-04 2:09 GMT+08:00 bounceme <notifications@github.com>:

**Comment by yormi** [comment]
@bounceme

I have another issue of the same kind with the indentation and Standard style.

```javascript
let someArray = [
{
  prop: 'Hello World'
}
]
```

Should be:

```javascript
let someArray = [
  {
    prop: 'Hello World'
  }
]
```

If you have a quick fix as know you can do, that would be amazing :)

**Comment by bounceme** [comment]
lines with only an opening brace,along with multiline comments and switch cases, use vim's c-implemented cindent.
```
set cinwords+=let
set cino+={1s
```
works but only when you are inside braces at any level(so if that is your entire file than it won't work)

**Comment by bounceme** [comment]
actually you can try this, or all three settings together `set cino+=f1s`

**Comment by yormi** [comment]
Are you some kind of genius or something !? :P

`set cino+=f1s` worked perfectly !

**Comment by bounceme** [comment]
you will not need this setting with the next push to dev

**Comment by yormi** [comment]
Great ! You are the best :D
