### ISSUE TITLE
Incorrect fold region and syntax highlighting after class `get` or `set` method

### ISSUE THREAD

**Issue by zanona** [pangloss/vim-javascript#465]
Hi, first of all, thanks for **vim-javascript**.
I've been using for a long time now and it has been really efficient to me.
One issue I stumbled upon was that apparently by naming class methods `get` or `set`, breaks the syntax highlighting and also confuses the fold levels?

```js
class Foo {
  static get(key) { … } //<!-- ok
  get(key) {  //<!-- breaks syntax
  }
  methodA() {
  }
  set(key, value) { //<!-- breaks syntax
  }
  methodB() {
  }
}
```

**Comment by amadeus** [comment]
This has already been fixed in the `develop` branch, sorry about that!
