### ISSUE TITLE
Indentation of multiline promise chains

### ISSUE THREAD

**Issue by sboehler** [pangloss/vim-javascript#467]
Currently (master & develop), vim-javascript seems to indent promise / function chains as follows, with an indent after the first line:

```
when(something)
    .then(thing => do(thing))
    .catch(err => handle(err));
```

However, until recently, it has always been formatting them as follow (which is my preference):
```
when(something)
.then(thing => do(thing))
.catch(err => handle(err));
```

Is this an intended change or a bug? And is it possible to switch back to the old behavior?

Many thanks for maintaining this plugin, I have noticed there has been considerable activity around it recently and it is good to see it is being actively developed!

**Comment by bounceme** [comment]
definitely intentional, but if this is very annoying to you you can remove the dot from this regex:
https://github.com/pangloss/vim-javascript/blob/develop/indent/javascript.vim#L73

**Comment by sboehler** [comment]
I changed the line to 
```
let s:continuation_regex = '\%([*?:]\|+\@<!+\|-\@<!-\|\*\@<!\/\|=\|||\|&&\)' . s:line_term
```
i.e. I removed the single dot I found as suggested, but it still indents the continuation lines as outlined above.

**Comment by bounceme** [comment]
sorry i edited the line number

**Comment by sboehler** [comment]
Awesome, this does the trick! Good enough for me, although it would be nice to have this somehow configurable via a variable. Thanks @bounceme for your help and for improving this plugin!

**Comment by bounceme** [comment]
#566

**Comment by tribou** [comment]
For anyone searching and finding this issue, I was able to disable indenting chained methods with this new config variable:

```vim
let g:javascript_opfirst = 1
```
