### ISSUE TITLE
Change identation to 2 spaces instead of 4

### ISSUE THREAD

**Issue by tiagofumo** [pangloss/vim-javascript#468]
I can't find anywhere how to set identation to 2 spaces instead of 4. Is that possible?

**Comment by amadeus** [comment]
These are Vim settings. Our plugin will use whatever configuration you have in Vim.

I suggest the following commands to learn about it:

```
:help expandtab
:help shiftwidth
:help tabstop
```

**Comment by tiagofumo** [comment]
I'm sorry, this is happening to me:
![output](https://cloud.githubusercontent.com/assets/12556770/15921645/2b0c6ca2-2df9-11e6-83b5-f8ef3d07ad6b.gif)

I have this line on my .vimrc:
`autocmd FileType javascript set tabstop=2|set shiftwidth=2|set expandtab`

I thought my indentation settings were messing with the plugin, so I was looking for a global variable to set or something. But this also happens when I comment the line and reopen vim, so I guess it's a different problem than.

**Comment by bounceme** [comment]
what are your plugins which could be related to javascript?your issue doesn't seem to be caused by this indent script(or I've never seen this happen). maybe try ` set indentkeys=`

**Comment by bounceme** [comment]
also try the develop branch,otherwise your issue is very likely caused by something else
