### ISSUE TITLE
Incorrect indentation with nested literal objects/arrays

### ISSUE THREAD

**Issue by tomxtobin** [pangloss/vim-javascript#469]
Commit d54b138f9113739780f1f61c9fe5aeec0e0ea088 broke indentation in the following case (and also with literal arrays):

```js
a = {
  b: {
    c: {
    },
  },
  d: {
      // indents to here
    // should indent to here, instead
  },
}
```

The issue doesn't arise if the trailing comma from `c` is removed.

The issue exists on the `develop` branch as well.

**Comment by bounceme** [comment]
fixed in 'bounceme-patch-1' branch, still needs #466 though

**Comment by bounceme** [comment]
can you try out develop again? this should be closable

**Comment by amadeus** [comment]
Working for me. Will close this unless someone can reproduce.

**Comment by tomxtobin** [comment]
Looks good to me on `develop`. Thanks!

**Comment by iryan2** [comment]
Broken for me on develop, depending on where the trailing comma is. It's when it appears on the last line of the last item:
<img width="238" alt="screen shot 2016-06-14 at 12 38 06 pm" src="https://cloud.githubusercontent.com/assets/5858312/16029622/64e58d5e-322d-11e6-9f4d-e28aa69815e2.png">



But not if the trailing comma appears earlier in the collection:
<img width="253" alt="screen shot 2016-06-14 at 12 41 09 pm" src="https://cloud.githubusercontent.com/assets/5858312/16029612/4dda1dfa-322d-11e6-8146-cf134c3170ba.png">
and 
<img width="245" alt="screen shot 2016-06-14 at 12 43 09 pm" src="https://cloud.githubusercontent.com/assets/5858312/16029641/9e2cedfa-322d-11e6-96e1-fdedbfcb2656.png">

Sorry if this isn't directly related to the originally reported issue, didn't want to spam your issue tracker :P

**Comment by bounceme** [comment]
are you sure there isn't any conflicting scripts?could you paste the examples as markdown, i'll be testing this later

**Comment by bounceme** [comment]
my results:
```
const a = [
  {
    id: 1,
  } ,
  {
    id: 2,
  }
];
```

**Comment by bounceme** [comment]
oh there is a problem still 
```
var a = [
  {
    id: 1,
  } , {
      id: 2,
    }
];
```
