### ISSUE TITLE
Incorrect unmatched paren highlighting with arrow functions

### ISSUE THREAD

**Issue by iryan2** [pangloss/vim-javascript#473]
When using ES6 arrow functions as callbacks, the closing paren is incorrectly reported to be unmatched, screenshot.
<img width="493" alt="screen shot 2016-06-14 at 10 12 42 am" src="https://cloud.githubusercontent.com/assets/5858312/16027354/915c7d08-3218-11e6-9ab2-d464d977e59a.png">

The first two examples show the problem, the third demonstrates that the problem does not occur with ES5 style callbacks

**Comment by amadeus** [comment]
Quick question, are you on `master` branch? I am 99% sure this is fixed in `develop`, which we will be merging into `master` shortly.

**Comment by iryan2** [comment]
Ah, just checked the develop branch and the problem is gone! Thank you!

**Comment by amadeus** [comment]
And I just merged the latest into master, so everything should be good!
