### ISSUE TITLE
Nested indentation sometimes misaligned

### ISSUE THREAD

**Issue by ysagal** [pangloss/vim-javascript#476]
It seems the indentation was significantly revised (for the better), but there's an issue with certain nesting situations. Here's an example.

Expected:
```
foo('foo',
  bar('bar', function() {
    hi();
  })
);
```

Actual:
```
foo('foo',
  bar('bar', function() {
  hi();
})
);
```

**Comment by bounceme** [comment]
i'm reworking some parentheses matching in #474, i'll try and fix this in the pr

**Comment by amadeus** [comment]
This appears fixed in `develop`, closing this as `develop` will go into `master` soon, perhaps even today.
