### ISSUE TITLE
Quoted string as object key not supported

### ISSUE THREAD

**Issue by alexlafroscia** [pangloss/vim-javascript#477]
Since pulling the updates from today, my highlighting has been way off.

![screen shot 2016-06-14 at 10 37 39 am](https://cloud.githubusercontent.com/assets/1645881/16053074/1679edec-321c-11e6-9d70-750b1fd0888b.png)

None of the `const`s are highlighted anymore, as are... Well, most other things.  It was all fine before `develop` was merged in today.

***

**Edit:** It's been determined that the issue is specifically with the following kind of syntax

```js
const obj = {
  'my-method'() {
    return ...;
  }
};
```

**Comment by amadeus** [comment]
This is probably the result of your color scheme. We've added a lot more syntax granularity, but it's possible your color scheme isn't matching up to these links well.

Can you link me to your color scheme file and I can look into perhaps better link things up?

**Comment by alexlafroscia** [comment]
Hmm, interesting.  I'm using [gruvbox](https://github.com/morhetz/gruvbox).

**Comment by alexlafroscia** [comment]
Huh, it looks like it might just be that one file, not a universal problem.  Here's a different file, same Vim config

![screen shot 2016-06-14 at 10 59 12 am](https://cloud.githubusercontent.com/assets/1645881/16053818/2bb712f4-321f-11e6-9a32-b28fbe64fe99.png)

Things look pretty normal there, so maybe it's just a problem with the first file I showed.

**Comment by amadeus** [comment]
Ahah, I think I can see the issue in your first file. It's a type of ES6/7 syntax I never thought to support.

```js
var obj = {
    'key-name'() {}
};
```

For now, if you changed it to:

```js
var obj = {
    ['some-key']() {}
}
```

Then it should fix itself. I will work on supporting that string key into parentheses syntax shortly though.

**Comment by alexlafroscia** [comment]
Alright, cool.  It's not something I can change in my codebase, but I'm glad to know it'll be handled sometime soon.

**Comment by amadeus** [comment]
I have a fix for this that is going into `develop` shortly. Thanks for the heads up!

**Comment by alexlafroscia** [comment]
Awesome! Thanks for the quick turn-around there, I'll install from `develop` and check it out.

**Comment by amadeus** [comment]
Awesome, closing this, as this fix will be going out shortly.

**Comment by alexlafroscia** [comment]
Thanks again for the quick turn-around!

**Comment by amadeus** [comment]
This is fixed in `develop`, gonna close this as it should be going into `master` soon.
