### ISSUE TITLE
Promise catch syntax error

### ISSUE THREAD

**Issue by eddiezane** [pangloss/vim-javascript#484]
This is on the `develop` branch.

![screen shot 2016-06-16 at 12 17 09 pm](https://cloud.githubusercontent.com/assets/959573/16124292/6222fd32-33bc-11e6-919f-879c04b6fa29.png)

```javascript
returnsAPromise()
  .catch(err => {
    console.error(err)
  })
```

**Comment by amadeus** [comment]
Awesome, thanks the find. I'll look into fixing this shortly!

**Comment by eddiezane** [comment]
@amadeus, @bounceme, and @davidchambers - y'all are the best people in the world. Such a stunning display of open source project management 💖 .

**Comment by alexlafroscia** [comment]
I was just coming over to this repo to report the same thing!  A few more examples in my screenshot:

![screen shot 2016-06-16 at 10 02 57 am](https://cloud.githubusercontent.com/assets/1645881/16125695/9ce5bcba-33a9-11e6-92a8-d9f97179c600.png)

It seems like a "regular" function passed to `.catch` gets thrown off as well.

**Comment by amadeus** [comment]
Yeah it's because `catch` is getting matched as a `catch` statement, not as a function call.

**Comment by alexlafroscia** [comment]
Totally makes sense, it's tough (and unfortunate) that it's both a keyword and the way to handle Promise errors.

As always, thanks for the hard work and attentive response to issues @amadeus!

**Comment by amadeus** [comment]
I have a fix in #485, perhaps check it out and confirm that it fixes the issue. Also make sure I didn't drastically break something else either xD

**Comment by amadeus** [comment]
Should be fixed in `develop`

**Comment by alexlafroscia** [comment]
@amadeus looks good to me! `.catch` is not un-highlighted when used as a method
