### ISSUE TITLE
Misc Issues With Strangely Placed Comments

### ISSUE THREAD

**Issue by amadeus** [pangloss/vim-javascript#487]
I have found a few cases where placing comments in specific contexts can cause major problems when relying on `nextgroup`.

Some examples:

```js
if (someBool) // This is a comment
{
   // This region is now matched as a `jsObject`, which is incorrect.
}

switch(someStr) /* Another comment */ {
    // This region is now matched as a `jsObject`, which is incorrect.
}
```

I wish there was a way to classify a certain group of regexes as skippable, and then opt in to skipping over them for determining `nextgroup`, however unfortunately this isn't possible.

The only real fix is to create case specific comments that can act as go-betweens for these regions. Since they would be contained I don't think it would create much overhead, but it would fix.

I am creating this issue as a reminder to fix these cases.

**Comment by smiechowy** [comment]
Yup, this is especially visible when using flow comment annotations
```
function testFunc() /*: string*/{
    var testObj = {
        prop: "lorem ipsum"
    };

    return someOtherFunc(testVar.prop);
}
```
highlight after /*: string*/ is totally broken

**Comment by amadeus** [comment]
@smiechowy we've recently added some experimental flow annotation support. Check the readme for details. It won't fix your comment annotation but it should support uncommented annotations

**Comment by amadeus** [comment]
Since you've brought up this issue, I will look into adding fixes for these comments in the next day or so.

**Comment by smiechowy** [comment]
Unfortunately I'm not using uncommented annotations in my current project, but one day it might come in handy. 

> Since you've brought up this issue, I will look into adding fixes for these comments in the next day or so.

Awesome, I'm looking forward to some results. Thanks for your hard work :)

**Comment by amadeus** [comment]
Took me a couple days to find time to tackle this, however I have a PR ( #532 ) open against develop that should fix many common instances of these.

**Comment by amadeus** [comment]
This issue should be mostly fixed in `develop`
