### ISSUE TITLE
Macro get broken by the plugin

### ISSUE THREAD

**Issue by akatsukle** [pangloss/vim-javascript#490]
After submitting my issue to [stackexchange](http://vi.stackexchange.com/questions/8290/macro-fails-using-arrows?noredirect=1#comment13938_8290), it looks like the issue come from pangloss.
When I remove it from my vimrc, it works again as expected.

**Comment by amadeus** [comment]
Unfortunately I cannot reproduce this issue at all, even with all my plugins enabled.

Furthermore, I can't see how our plugin would change anything like this? We don't do anything with remapping of keys. Perhaps it's related to a particular version of Vim?

If you can a way to more reliably reproduce this issue, let me know and I can re-open.
