### ISSUE TITLE
Trailing comma can mess up subsequent indentation

### ISSUE THREAD

**Issue by markrian** [pangloss/vim-javascript#491]
I haven't really characterised this fully, but it seems that a trailing comma in an array literal can mess up subsequent block indentation. Using the latest commit on develop (ea5803348e3ec88a1762b4f044b585d216d1974f), it indents the following code like so:
```js
var whatever = [
    'an item',
    'note the trailing comma',
].map(() => {
        anythingHere();
});
```
If you remove the trailing comma, you get this:
```js
var whatever = [
    'an item',
    'note the LACK of a trailing comma'
].map(() => {
    anythingHere();
});
```
which is how I'd expect the code to indented.

**Comment by markrian** [comment]
The most recent commit which doesn't exhibit this bug happens to be exactly v1.0.0 (d7f4728f830173d5894009771432d329d9098f17).

**Comment by bounceme** [comment]
dev branch!

**Comment by markrian** [comment]
I'm not sure what you meant by that comment - was I right to file an issue against the develop branch?

**Comment by bounceme** [comment]
I thought it was fixed already, this is still a problem but i'll try and fix it for the next push to master.

**Comment by amadeus** [comment]
Has this issue been fixed on `develop`?
