### ISSUE TITLE
Hanging indent causes subsequent lines to indent incorrectly

### ISSUE THREAD

**Issue by markrian** [pangloss/vim-javascript#492]
Using the latest commit on the develop branch (ea5803348e3ec88a1762b4f044b585d216d1974f), hanging indents cause subsequent lines to be indented. That is, this happens:
```js
expect(whatever).toBe(
    'some', 'parameters', 'here', 'whatever');
    expect(aThing).toHaveBeenCalledWith('foo');
    expect(anotherThing).toHaveBeenCalledWith('bar');
```
whereas I would expect this:
```js
expect(whatever).toBe(
    'some', 'parameters', 'here', 'whatever');
expect(aThing).toHaveBeenCalledWith('foo');
expect(anotherThing).toHaveBeenCalledWith('bar');
```

**Comment by markrian** [comment]
The most recent commit where this bug isn't present is be5506443592c5ef99493f817f26c3091af4585e.

**Comment by bounceme** [comment]
both of your issues appear to be fixed
