### ISSUE TITLE
Confuses default values in destructuring assignment

### ISSUE THREAD

**Issue by FuzzOli87** [pangloss/vim-javascript#502]
![screenshot_20160620_122522](https://cloud.githubusercontent.com/assets/12246915/16204001/7df9b108-36e2-11e6-9299-ca287eb2fd74.png)
[http://imgur.com/n3f0Tat](url)

As you can see, the second function loses syntax. It confuses the braces in the default assignment "settings" for closing braces.

It's weird that the top function also has destructuring but it does not flake out.

**Comment by amadeus** [comment]
Can you paste that snippet as a code block and I can look into it? Also, is this on `master` or `develop` branch?

**Comment by FuzzOli87** [comment]
@amadeus This is definitely master.
```javascript 
function createJobMetaLog(options, prefix = '') {
  const { meta: { processor: { name, version } = {} } = {} } = options;

  return `${prefix} ${name} v.${version}`;
}

function settingsHandler(options = {}) {
  const { settings = {} } = options;

  return {
    getSetting(setting) {
      return settings[setting];
    }
  };
}
```

HOWEVER!

I just tried the 'develop' branch on my .nvimrc and the syntax error is resolved. So, fix for this seems to be coming down the pipeline.

![image](https://cloud.githubusercontent.com/assets/12246915/16204381/27d32820-36e4-11e6-8636-4eda72fd42a1.png)

**Comment by amadeus** [comment]
Awesome, good to hear. Yeah, I just refactored how we handle destructuring, so glad to hear it's fixed.

**Comment by amadeus** [comment]
Your example was actually super helpful though, I've found another destructuring case that I didn't handle from before, so thanks for that! I'll get a PR together to improve `develop` further.

**Comment by amadeus** [comment]
Closing this as the issue that you found without realizing it, is now a PR for `develop`. Thanks again!
