### ISSUE TITLE
Bad syntax highlighting on block case statements

### ISSUE THREAD

**Issue by larsbs** [pangloss/vim-javascript#505]
In one of the recent updates, the support for block case statements has been broken. Don't know exactly when because I don't update frequently but here is a screenshot of the actual problem:

Using block declaration (Using `{ }`)
![20160622-110319](https://cloud.githubusercontent.com/assets/1436588/16260738/f67ee846-3868-11e6-869d-b10870dd7542.png)

Without block declaration (No `{ }`)
![20160622-110421](https://cloud.githubusercontent.com/assets/1436588/16260762/1a5b31de-3869-11e6-881f-351a0d2dc597.png)

As you can see, the last `}` is marked an invalid and the color of the `return` statement is wrong also. This is valid JavaScript syntax and used to work well with this plugin. Sorry not being able to help more for now.

**Comment by larsbs** [comment]
Ok, I had some time to checkout some commits. The issues started with these two commits:

1. a0d1abc172cd0d701c115b7c0197c5dfa288f278
2. c48323a215a472a0a4a2a71ca08f10096e1eeb73

So the latest working commit was: 6c2de108fbe66faea75e358774a12da1b44c0de0

**Comment by amadeus** [comment]
I'll have a fix for this shortly, thanks for submitting the issue!

**Comment by amadeus** [comment]
Should be fixed in `develop`
