### ISSUE TITLE
async class method not highlighted

### ISSUE THREAD

**Issue by Arch-Mage** [pangloss/vim-javascript#506]
This class

```javascript
class ClassName {
  async methodName(arg1) {
  }
}
```

should have `async` keyword highlighted as `jsAsyncKeyword`. But it is not. It  just have `jsClassBlock`.

If I'm correct adding `jsAsyncKeyword` to [this line](https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L138) should fix this, because it works
for me.

**Comment by amadeus** [comment]
Thanks for posting this issue! I'll have a fix in 'develop' shortly!

**Comment by amadeus** [comment]
I see, do you have some documentation for this ES7 somewhere that I could reference?

**Comment by Arch-Mage** [comment]
Tracked down on babel, and I found [this spec](https://tc39.github.io/ecmascript-asyncawait/) about `async` and `await`.

**Comment by amadeus** [comment]
I added it to objects in #507 as well.
