### ISSUE TITLE
Comment inside import and export not highlighted

### ISSUE THREAD

**Issue by Arch-Mage** [pangloss/vim-javascript#510]
Try this:

```javascript
import {
  // should be highlighted here but it is not
  fn, variable, orSomethingElse
} from 'package';

export {
  // here too
  fn, variable, orSomethingElse
};
```

I believe adding `jsComment` to [this line](https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L43) and [this line](https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L48) should fix this.

**Comment by amadeus** [comment]
Oof, thanks for posting the issue, I'll look into getting it sorted shortly!

**Comment by amadeus** [comment]
This issue has been fixed in `develop`
