### ISSUE TITLE
'Maybe' flow types break syntax highlighting

### ISSUE THREAD

**Issue by BlooJeans** [pangloss/vim-javascript#516]
On v1.1.3
Optional flow types (e.g. var foo: ?string = 'bar') will break the highlighting on subsequent lines.

Same result with both `let g:javascript_plugin_flow = 1` and `let g:javascript_plugin_flow = 0`

<img width="295" alt="screen shot 2016-06-28 at 14 15 27" src="https://cloud.githubusercontent.com/assets/1751182/16427410/33a2e958-3d3b-11e6-8608-67ea68d44f78.png">

**Comment by amadeus** [comment]
This should be fixed in #518. Can you please check out that branch and test when you have a chance?

**Comment by amadeus** [comment]
Fixed in `develop`

**Comment by sroecakepler** [comment]
This is broken again.
