### ISSUE TITLE
Flow type missing `bool` primitive

### ISSUE THREAD

**Issue by gf3** [pangloss/vim-javascript#519]
`jsFlowType` should include the `bool` primitive

**Comment by amadeus** [comment]
Should I remove `boolean` then? Or just add `bool`

**Comment by gf3** [comment]
@amadeus both are legal

**Comment by amadeus** [comment]
Added to that PR branch.

**Comment by gf3** [comment]
tested and fixed in #518

**Comment by amadeus** [comment]
Fixed in `develop`
