### ISSUE TITLE
Flow: More granular syntax matching

### ISSUE THREAD

**Issue by gf3** [pangloss/vim-javascript#520]
It'd be handy to have more granular syntax matches for both `jsFlowTypeStatement` and `jsFlowNoise` so that i could provide better highlighting similar to an object literal. Example comparison:

<img width="738" alt="screen shot 2016-06-28 at 2 53 08 pm" src="https://cloud.githubusercontent.com/assets/18397/16428455/f928671c-3d3f-11e6-98b8-e7c68b599e5a.png">

**Comment by amadeus** [comment]
Yup, would love to get around to do doing this! I've only just begun to use Flow, so I don't know a whole lot about it or it's syntax structure so I was holding off until I was more familiar with it.

Some of the highlighting may already be possible, we just have to properly link the syntax groups.

If you have some ideas, perhaps you could contribute some changes. The way we do things here - branch off of `develop` and submit PRs against `develop`.

I may go ahead and just merge in these JS Flow fixes in a minute btw.

**Comment by gf3** [comment]
@amadeus i'll give it a shot. thank you so much for your amazing work on the flow highlighting

**Comment by iansinnott** [comment]
Seconded 👍 . It would be great to have more robust Flow support. I would say full flow support might be beyond the scope of vim-javascript but it would be cool to have it nonetheless.

If it helps, here is another issue I've seen while using flow. Defining class property types in the class definition sometimes throws everything off ([Here are the pertinent Flow docs](https://flowtype.org/docs/react.html#defining-components-as-reactcomponent-subclasses)). Here is a react example:

![screen shot 2016-07-27 at 11 35 05 am](https://cloud.githubusercontent.com/assets/3154865/17187478/395d851e-53ee-11e6-846f-d5b463d270df.png)

In the above image the inclusion of 

```js
  props: {
    buttonText: string,
  }
```

throws all the highlighting off. However, refactoring the `props` type outside of the component works fine:

![screen shot 2016-07-27 at 11 25 35 am](https://cloud.githubusercontent.com/assets/3154865/17187446/1b40a7aa-53ee-11e6-8480-d853be5bfcf3.png)

Here's the raw code in case it helps:

```js
import React from 'react';
import shallowCompare from 'react-addons-shallow-compare';

export class Button extends React.Component {
  props: {
    buttonText: string,
  }

  shouldComponentUpdate(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState);
  }

  handleClick = () => {
    console.log('You clicked the button');
  };

  render() {
    return (
      <button className='Button' onClick={this.handleClick}>
        {this.props.buttonText}
      </button>
    );
  }
}
```

**Comment by amadeus** [comment]
@iansinnott this should be fixed in `develop`, assuming you have the js flow plugin enabled? `develop` will probably be merged into `master` shortly.

**Comment by gf3** [comment]
@iansinnott btw (unrelated), you can avoid using fake flow props to link your types by using type paramaterization:

``` js
import React from 'react';

type DefaultProps = {};
type Props = DefaultProps & {};
type State = {};

export class Button extends React.Component<DefaultProps, Props, State> {
  render() {
    // ...
  }
}
```

**Comment by iansinnott** [comment]
Awesome thanks @amadeus, I'll check out the `develop` branch. 

Thanks for the tip @gf3, good point!

**Comment by amadeus** [comment]
Since this main issue has been fixed, closing this issue. Flow will still be undergoing development, and if you see problems please file an issue so we can work on getting them fixed.
