### ISSUE TITLE
detect and highlight classname like funcname?

### ISSUE THREAD

**Issue by em-yuanbo** [pangloss/vim-javascript#522]
i want  classname highlighted like funcname does.
how can i get it?

**Comment by amadeus** [comment]
Are you saying you want to change the color of `Example` in this snippet

```
class Example {}
```

to match the color of `Name` in this example:

```
function Name() {}
```

**Comment by em-yuanbo** [comment]
Yes, that is what i want.
Is it relizable?

**Comment by amadeus** [comment]
Soo, it looks like I never linked up `jsClassDefinition` to any highlight group. I've done that in #526.

This fix should be in `develop` shortly.

**Comment by amadeus** [comment]
This issue is now fixed in `develop`, thanks for bringing it to our attention!
