### ISSUE TITLE
[flow] function return types that span multiple lines break following syntax highlighting

### ISSUE THREAD

**Issue by BlooJeans** [pangloss/vim-javascript#523]
On the latest develop (ad5d09edff)

When you define a function with a return type that spans multiple lines, it breaks the rest of that functions syntax highlighting

Example:
```
function getObj4(): {
  key: string
} {
  let foo = 'bar';
  return {
    baz: foo,
  };
}
```
<img width="289" alt="screen shot 2016-06-29 at 09 53 09" src="https://cloud.githubusercontent.com/assets/1751182/16454595/53afd7b6-3ddf-11e6-8100-1cdf02dc13a3.png">

- The same return type in a single line is fine (getObj1())
- Creating a new explict type on multiple lines is fine (getObj2())
- Multiline spanning object types is fine (getObj3())

**Comment by amadeus** [comment]
Sooo, coming up with the correct rules for this has been pretty tough. Right now all JS Flow statements using `:` are limited to one line.

I'd need to see the range of possibilities for these types of statements to figure out if I can allow them to be multiline or not. These ones are tough to figure out intent, so to speak.

**Comment by amadeus** [comment]
So I refactored a bunch of the flow stuff, and I think I have a fix for this issue in place. I may have introduced a couple other issues (one I need to look into is the use of the `?` maybe operator (or whatever it's called). But overall I think the new flow refactor in `develop` is a big improvement.

**Comment by amadeus** [comment]
Should be fixed in `develop`
