### ISSUE TITLE
Incorrect indentation after multiline variable declaration with array or object

### ISSUE THREAD

**Issue by markrian** [pangloss/vim-javascript#524]
Tested on latest develop ad5d09edfff3b15ac1c785796abb1705a0d64af6. This is the resulting indentation:
```javascript
const a = 1,
    b = {
        foo: 'bar'
    };

    anythingHere();
```
whereas I would expect this:
```javascript
var a = 1,
    b = {
        foo: 'bar'
    };

anythingHere();
```
Bizarrely, a trailing comma in the object or array literal fixes the subsequent indentation:
```javascript
const a = 1,
    b = {
        foo: 'bar',
    };

anythingHere();
```

**Comment by bounceme** [comment]
my new p.r. #515  , if finished, will work in just about any situation regardless of keyword, comma etc. it also removes about 80% of the code

**Comment by markrian** [comment]
Testing has so far revealed only one thing I'd definitely call a bug, and a couple of other things which are perhaps a matter of personal preference. The former I can only reproduce on a fairly large file, and I'm having trouble producing a minimal test case. In fact, it almost seems like the size is to blame, since changing the file at all seems to resolve the bug. That file is proprietary, so I can't share it, sadly. Once I've managed to make a minimal test case, I'll put it here.

I'll describe the other personal preference "bugs" later, too, when I have some time.

**Comment by amadeus** [comment]
This is now fixed in `develop`

**Comment by amadeus** [comment]
Should now be fixed in `develop`
