### ISSUE TITLE
do expression support

### ISSUE THREAD

**Issue by tomxtobin** [pangloss/vim-javascript#525]
[`do` expressions][do-expressions] aren't (quite) supported.

They sort-of work because of support for `do/while` loops, but the highlighting breaks down in certain cases.

In particular, they're highlighted incorrectly inside array and object literals.

Examples:

```javascript
const obj = {
  bar: do { // "do" gets jsObjectValue
    if (baz) { // "if" gets jsObjectFuncName
      'hi'
    } else {
      'bye'
    }
  },
} // jsParensError

const arr = [
  do { // "do" gets jsBracket
    if (baz) { // "if" gets jsObjectFuncName
      'hi'
    } else {
      'bye'
    }
  }, // jsParensError
]
```

Granted, `do` expressions are at stage 0, but Babel does support them with an official plugin, and I've seen support added to `vim-javascript` for other early-stage syntax.

[do-expressions]: http://babeljs.io/docs/plugins/transform-do-expressions/

**Comment by amadeus** [comment]
I'll look into this soon, I don't think it should be too hard to support.

**Comment by amadeus** [comment]
I've just added a PR for `do` expression support in #530, it's not a big change so I think it will be safe to merge into `develop` shortly

**Comment by amadeus** [comment]
This has been merged into `develop`

**Comment by tomxtobin** [comment]
Looks great. Thanks!
