### ISSUE TITLE
ES2015 template strings with globs patterns

### ISSUE THREAD

**Issue by ahmedelgabri** [pangloss/vim-javascript#527]
<img width="589" alt="screen shot 2016-07-02 at 20 30 28" src="https://cloud.githubusercontent.com/assets/63876/16541926/eed921aa-4093-11e6-8d0c-3cf6bd364f31.png">

As you can see from the screenshot after the first pattern `./app/${appName}/assets/images/**` everything after this point is highlighted as a comment which is not right. Removing `**` fixes everything but it's not an option.

**Comment by huynhquancam** [comment]
:+1: Yeah, same problem here

**Comment by amadeus** [comment]
Unfortunatly I cannot reproduce this issue:

![example](https://dl.dropboxusercontent.com/s/pznvxn45r1py9ux/_2016-07-07_21-24-49.png?dl=0)

Perhaps something odd is going on with the conceal characters? But still, I don't see how that could be an issue...

**Comment by amadeus** [comment]
Hmm, just checked with that function conceal character and still couldn't reproduce. Are you guys sure you are using the latest version?

**Comment by huynhquancam** [comment]
@amadeus Yeah I'm using the latest version. 

Could you try this?

```javascript
export default class Thing extends Components {
  render() {
    const abc = urls.map((url) =>
      <div className={`hello${something}`}></div>
    )

    const b = 10
    const c = a + b
  }
}
```

It looks like this for me.

<img width="411" alt="screen shot 2016-07-08 at 11 53 44" src="https://cloud.githubusercontent.com/assets/5930347/16677713/b2e40534-4502-11e6-8b06-2ef5bc65af8b.png">

**Comment by bounceme** [comment]
another ?
mxw/vim-jsx

**Comment by amadeus** [comment]
@bounceme yup, that's exactly it.

@huynhquancam you need to be using the JSX plugin in addition to ours. https://github.com/mxw/vim-jsx Also you need to ensure to `:set filetype=javascript.jsx` once the plugin is installed.

**Comment by huynhquancam** [comment]
@amadeus @bounceme Yes it works perfectly after :set filetype=javascript.jsx

Many thanks for your support!

**Comment by ahmedelgabri** [comment]
For me it's not a `jsx` issue because my file is just JavaScript. I was using the plugin through vim-polyglot, then I disabled it and used it separately, pulled the latest version, changed color schemes, even disabled all plugins except this one and still having the same problem.

**Comment by huynhquancam** [comment]
`vim-polyglot` user here. Maybe getting the HEAD version of `vim-polyglot` will fix it?

`vim-polyglot` is actually sync-ed with this repo.

**Comment by amadeus** [comment]
@ahmedelgabri so, based on your screenshot that you originally posted, and based on my attempts to reproduce, I am 99% sure that for some reason your vim is not actually sourcing and using our syntax file.

For starters, just look at the things that are highlighted in my screenshot, vs yours. Your revolt string example doesn't even match `${}` portion which leads me to believe this isn't a bug in our script at all, but something not set up properly in your configuration. Perhaps you can post more details of how you have things set up?

**Comment by ahmedelgabri** [comment]
@huynhquancam I already did and still the problem presists.

@amadeus Here is my [`.vimrc`](https://github.com/ahmedelgabri/dotfiles/blob/master/vim/vimrc.local) file, also I have [this](https://github.com/ahmedelgabri/dotfiles/blob/master/vim/.vim/after/syntax/javascript.vim) for function conceal color.

I'm using iTerm2, Neovim (HEAD) & tmux. All with true color enabled.

**Comment by amadeus** [comment]
Oh yeah, your concealing code ruins everything. You should be using our built in concealing api, check the readme for details.

**Comment by ahmedelgabri** [comment]
Yes that was the problem, I forgot to remove it when I moved to `vim-polygot`. Thanks @amadeus
