### ISSUE TITLE
Template string and JSX

### ISSUE THREAD

**Issue by meriadec** [pangloss/vim-javascript#529]
I'm experiencing some regressions with the template string handling when using inside JSX code.
After a bit of digging, it appears that the commit which introduced the problem is this one: https://github.com/pangloss/vim-javascript/commit/c48323a215a472a0a4a2a71ca08f10096e1eeb73.

An image is often better than an explanation, so here it is:

![fixture](https://cloud.githubusercontent.com/assets/315259/16564859/1b3443ac-420a-11e6-824b-62e0a2cd5310.jpg)

I couldn't manage to get it works, playing with regexes in the `syntax/javascript.vim` file. Can you help?

Maybe handling JSX is out of scope of this plugin, so let me know.
Anyway, it would be perfect to have the same behaviour as before.

Thanks!

(edit: right commit link)

**Comment by amadeus** [comment]
I am not at a computer at the moment, however quick question, are you using the [vim jsx](https://github.com/mxw/vim-jsx) plugin? It adds support for JSX assuming you set the file type to `javascript.jsx`.

It's made to work with our syntax highlighting as well and I am pretty sure it should fix your issue.

**Comment by meriadec** [comment]
I've tested with and without vim jsx, infortunately it doesn't solve the problem 😢 
My current solution is to use vim-javascript on a HEAD older than https://github.com/pangloss/vim-javascript/commit/c48323a215a472a0a4a2a71ca08f10096e1eeb73. Thanks for the quick reply.

**Comment by amadeus** [comment]
So, I am 99% sure the file isn't set to `javascript.jsx`. Here's a screenshot from that exact code snippet

![example](https://dl.dropboxusercontent.com/s/uabwuw3icj3ymlf/_2016-07-04_08-58-28.png?dl=0)

If you run this command in vim while the file is open `:set filetype?`, what is the output?

If it's not `javascript.jsx` then you will need to do `:set filetype=javascript.jsx`

**Comment by meriadec** [comment]
Ok my bad :( I wasn't using the `.jsx` extension with the jsx plugin. It works now like a charm!
Thanks a lot dude!

**Comment by amadeus** [comment]
No problem! Glad you got it sorted!

**Comment by edrpls** [comment]
You can also add to your vim config:
`let g:jsx_ext_required = 1`
to use the .js extension

**Comment by ayohan** [comment]
pop this into your vimrc
`au BufNewFile,BufRead *.jsx set filetype=javascript.jsx`
