### ISSUE TITLE
Provide full filetype plugin

### ISSUE THREAD

**Issue by dmitrivereshchagin** [pangloss/vim-javascript#545]
As mentioned in #543 it may be reasonable to provide a full filetype plugin. The one which bundled with Vim could be adapted. Among other advantages this change allows the user to override filetype settings more easily.

**Comment by amadeus** [comment]
Can you elaborate a bit more on what would be in this and what the benefits of it would be?

I read what you wrote in the other PR, however it wasn't clear to me what the benefits of it and why.

**Comment by dmitrivereshchagin** [comment]
I have changed my mind. Moving filetype plugin to after directory will be better. Please see #553.

**Comment by dmitrivereshchagin** [comment]
Closed, since #553 was merged.
