### ISSUE TITLE
option for extra indent in chained method calls

### ISSUE THREAD

**Issue by gera2ld** [pangloss/vim-javascript#559]
For example:
``` js
// Expected, situation in Atom
Promise
.resolve()
.then(() => ())
```

In Atom, it will be indented just like above. But with vim-javascript, there will be an extra level of indent before each method:
``` js
// Actual situation
Promise
  .resolve()
  .then(() => ())
```

Sometimes there will be lots of chained calls. I don't think it necessary to indent since we don't actually care about the start of the chain and we can add blank lines to separate different blocks.

Perhaps some peopl prefer the extra-indented way, so can we have an option for this?

**Comment by bounceme** [comment]
Alright, here's an exercise for the people requesting this : make a p.r. and I'll merge if it works correctly and leaves the current behavior as default

**Comment by amadeus** [comment]
So, I partially agree with the request in this issue, however I think there is a more balanced middle ground that doesn't require configuration options.

As of now, the default functionality does exactly the first scenario:

```js
Promise
.resolve()
.then(() => ())
```

While I personally would use the desired results in the follow-up example:

```js
Promise
  .resolve()
  .then(() => ())
```

I think it would get annoying for people who like to write JS without semicolons (I am not one of those people btw :P). However, I think a preferred middle ground is the following (although this may not be possible, I am not sure?):

```js
Promise
|
^ - Cursor by default goes here
```

```js
Promise
    |
    ^ - I press tab to indent, and type the next method
```

```js
Promise
    .resolve()
|
^ - When I press return, I am brought back to the original indentation
```

```js
Promise
    .resolve()
    |
    ^ - is it possible to be returned to here?
```

I guess I have no idea how to know when the user is done with a statement or when they continue a statement... so not sure how solvable this is?

**Comment by bounceme** [comment]
@amadeus we can experiment with `indentkeys`
try this : `set indentkeys+=0.`

**Comment by bounceme** [comment]
is that configurable in atom?

**Comment by gera2ld** [comment]
@bounceme it's not configurable by default but can be supported by plugins in atom.
Some people are requesting for this feature too (beautify-web/js-beautify#482).

**Comment by bounceme** [comment]
#566
