### ISSUE TITLE
Syntax with decorator using `

### ISSUE THREAD

**Issue by gregaou** [pangloss/vim-javascript#572]
Syntax doesn't work with a decorator declared like that :
![2016-07-26-123709_3600x1080_scrot](https://cloud.githubusercontent.com/assets/1533798/17135016/cfc76036-532d-11e6-9918-9e4adc1b3edb.png)

**Comment by amadeus** [comment]
I'll look into decorator support once we get the current `develop` branch into master. Decorators I believe are somewhat controversial? I think they were specced, then deprecated?

**Comment by gregaou** [comment]
Decorators seems specify for ES7, if i'm not wrong.

**Comment by jfelchner** [comment]
@amadeus decorators are in stage 2 so barring something crazy, they should land fairly close to as-is.
