### ISSUE TITLE
JSDoc highlighting for optional parameters

### ISSUE THREAD

**Issue by alexlafroscia** [pangloss/vim-javascript#574]
I've noticed that `vim-javascript` does an excellent job with most JSDoc highlighting, but gets confused on [optional parameters](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values).

Here's a screenshot showing how both "normal" and "optional" parameters are handled.

<img width="513" alt="screen shot 2016-07-26 at 1 29 54 pm" src="https://cloud.githubusercontent.com/assets/1645881/17154268/1f53479e-5335-11e6-9735-5c658598c7fa.png">

It would be great if it showed up the same color, and even better if the each part was highlighted separately to make the default value stand out, if provided.

**Comment by tomxtobin** [comment]
Just pushed up #660 which fixes the issue.

FWIW, I usually write all my Vim regexes prefixed with `\v` just so I don't go crazy trying to track down bugs like that. ;-)

**Comment by alexlafroscia** [comment]
Awesome, thanks @tomxtobin!
