### ISSUE TITLE
JsDoc does not work after recently update (neovim)

### ISSUE THREAD

**Issue by crusoexia** [pangloss/vim-javascript#577]
I'm using neovim build v0.1.5-372-gd97a97d, recently after update the plugin, the js doc highlight missing
<img width="427" alt="screen shot 2016-07-29 at 10 55 55 am" src="https://cloud.githubusercontent.com/assets/5928754/17236362/193b6222-557b-11e6-961d-23ee553ea288.png">

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript#configuration-variables

**Comment by crusoexia** [comment]
@bounceme thanks, haven't check the readme for a long time.
