### ISSUE TITLE
Arrow functions without brackets extra indent 

### ISSUE THREAD

**Issue by mnbroatch** [pangloss/vim-javascript#585]
This happens without the .then as well, but it shows the contrast of the extra indent.

When there's a new line after an arrow, it gets two indents instead of one.

![screen shot 2016-08-02 at 12 58 19 pm 2](https://cloud.githubusercontent.com/assets/18113135/17343229/7b700d1a-58b1-11e6-9131-798fbb816b20.png)

**Comment by bounceme** [comment]
intentional
https://github.com/pangloss/vim-javascript/issues/332
https://github.com/lukehoban/es6features#arrows

**Comment by bounceme** [comment]
Oh unless you mean that indent should be one &sw if the previous line contains the opening paren

**Comment by mnbroatch** [comment]
under the arrow in my screenshot, you can see there are two indents before the word "Joke". There should be one.

**Comment by bounceme** [comment]
can you paste this at line 188 (or 197 at develop)
`        \ inb) || (num < lnum && s:Onescope(lnum,pline,0) && line !~ s:line_pre . '{')`

**Comment by bounceme** [comment]
I also will make the dot chain functions increase to two &sw

**Comment by bounceme** [comment]
how is this working: https://github.com/pangloss/vim-javascript/pull/586 ?

**Comment by mnbroatch** [comment]
sorry I'm a little new to using github features that aren't posting to my own repo; can't figure out the right way to get that new file XD

But I did copy and paste the new source into my indent/javascript.vim file, and it's working great. Thanks!

**Comment by mnbroatch** [comment]
Well, I'm not sure if you care, but I'm also using vim-jsx (which requires vim-javascript as a dependency), and the new code causes the same problem to appear with jsx elements. They are now double-indented. Definitely could be a "not my problem" moment for you guys but I thought you'd want to know


![screen shot 2016-08-02 at 3 41 17 pm 2](https://cloud.githubusercontent.com/assets/18113135/17347917/abac9e7e-58c7-11e6-9e0b-43d9ab61d41d.png)

**Comment by bounceme** [comment]
should be fixed, though it isn't exactly a js problem. Thanks!
