### ISSUE TITLE
Chained Indent Comments

### ISSUE THREAD

**Issue by cleversoap** [pangloss/vim-javascript#587]
First off thanks for a great plugin, eagerly followed the latest updates and really appreciate all the hard work that goes into making it.

I've noticed that when chaining function calls together that comments are not indented along with the subsequent function call. **Is this behaviour intentional or configurable?**

There are some issues (eg. #566) that I thought would have affected this but I haven't been able to discern what the outcome of that issue was or if we should be (or how to) using those globals (js_continuation, js_opfirst) to change the behaviour.

- Vim 7.4 and Neovim 0.1.4
- mxw/vim-jsx is used but the behaviour is the same in both *javascript* and *javascript.jsx* filetypes

![nvim-comments-example](https://cloud.githubusercontent.com/assets/564094/17347989/c4385c5a-5956-11e6-9492-e51a5eb5e0f4.png)

*On a personal note it would actually be nice to have the chained function call be where the comments are currently being put, even if that just means setting some global like g:js_chained_indent=0 that sets the regex in js_continuation to something that accomplishes that*

**Comment by bounceme** [comment]
there are now two configurable regexes for operator caused indent, `g:javascript_opfirst` and `g:javascript_continuation` . The comment issue isn't fixable however, those are considered code while the script evaluates in their line, however they are correctly not considered when a regular code line is looking for context. The only other method to indent comments is by just copying the previous lines indent or some complex look-forward assessing, which will be difficult given that that is essentially the opposite of what this and all other vim indent scripts do

**Comment by bounceme** [comment]
Sorry, didn't read that you knew of those configurable options. basically just copy them from the source and and add, remove characters. if you aren't good with regex think about them in parts separated by `\|` and group-able with `\%(` `\)`

**Comment by cleversoap** [comment]
I'm familiar enough with regex but I can't quickly figure out what I should change here - if I wanted to match where the comments are now would I just remove the "." from the regex like so?
`let g:javascript_continuation = '\%([*,?:]\|+\@<!+\|-\@<!-\|\*\@<!\/\|=\|||\|&&\)'`

**Comment by bounceme** [comment]
yes, continuation is for the end of line, opfirst for the start

**Comment by cleversoap** [comment]
Alright I give up - I have no idea how to set the regexes so that the chained function calls are indented the same as the first function in the chain, not worried about the comments anymore. I'm not seeing any difference in indentation but the globals are definitely being set correctly.

I've tried removing the dots, escaping them, etc... sorry to be a pest but any help is appreciated!

```vim
let g:javascript_continuation = '\%([*,?:]\|+\@<!+\|-\@<!-\|\*\@<!\/\|=\|||\|&&\)'
let g:javascript_opfirst = '\%([,.:?]\|\([-/.+*]\)\%(\1\|\*\|\/\)\@!\|||\|&&\)'
```

**Comment by bounceme** [comment]
```
let g:javascript_opfirst = '\%([,:?^%]\|\([-/+]\)\%(\1\|\*\|\/\)\@!\|\*\/\@!\|=>\@!\||\|&\|in\%(stanceof\)\=\>\)\C'
```
should work

**Comment by cleversoap** [comment]
Thank you - that worked perfectly and incidentally resolved the core of this issue with chained comments haha
