### ISSUE TITLE
Use vim-javascript in html files

### ISSUE THREAD

**Issue by sassanh** [pangloss/vim-javascript#588]
Is it possible to use this plugin for javascript sections of html parts? The one in `<script>` tags.

**Comment by bounceme** [comment]
that is up to the html script maintainer

**Comment by jonsmithers** [comment]
Any tips on how someone could make this work?

When I work as a front-end Polymer developer, 90% of the javascript code I touch is embedded in html. That's a real problem for vim.

**Comment by bounceme** [comment]
https://github.com/vim/vim/tree/master/runtime

https://github.com/jason0x43/vim-js-indent/blob/master/indent/html.vim

I'd diff the html indent files, the second one is changed to hardcode a specific js indent script. Syntax probably has a similar problem, only the file in $VIMRUNTIME gets sourced. Then email the maintainers with a patch or bug report

**Comment by jonsmithers** [comment]
I started to look into it, and it seems the vim-javascript plugin actually already works on javascript embedded in html. I tested by viewing embedded javascript after uninstalling and after re-installing. I did this in both Vim 8.0 and NeoVim 0.1.5. Now I'm not sure what made me conclude that it wasn't working.

I found the following line in vim's `html.vim` file.

```
syn include @htmlJavaScript syntax/javascript.vim
```

I think that means that vim-javascript's `syntax/javascript.vim` file is used for embedded javascript.

**Comment by bounceme** [comment]
Oh great, also the indent script included with vim is now an older version of this repo's . I'll be sending a newer version to Bram soon

**Comment by bounceme** [comment]
Actually, the html indent script doesn't source the indent script but uses cindent. That's a bug

**Comment by jonsmithers** [comment]
I figured out why I initially thought it wasn't working.

In case anyone else comes here thinking the same thing:

It seems that sometimes vim loses track of the bigger context and thus doesn't know to apply javascript syntax highlighting. I see this issue in html `<script>` tags that contain pages worth of javascript. It only happens when you jump down into the middle/bottom of the file, so the starting `<script>` tag is out of sight.

To get syntax highlighting back on track, you can run `:syntax sync fromstart`. http://vim.wikia.com/wiki/Fix_syntax_highlighting

**Comment by bounceme** [comment]
https://github.com/vim/vim/commit/690afe1fef87e7eef6fb7343a926617d5f7315fa

html indentation as of https://github.com/vim/vim/commit/690afe1fef87e7eef6fb7343a926617d5f7315fa won't use cindent for js anymore

**Comment by sassanh** [comment]
@bounceme is it possible to use it in neovim too or should I create an issue in neovim repo?

**Comment by bounceme** [comment]
i think this script will work: https://github.com/polpo/vim-html-js-indent

**Comment by sassanh** [comment]
Thanks, and what about syntax? Is it possible to use `vim-javascript` syntax in html files?

**Comment by bounceme** [comment]
I don't know, i thought that happens by default

**Comment by sassanh** [comment]
No, actually after installing it, it doesn't seem to work. I don't know how a single indent file could work without syntax file. It should be useless without syntax.

**Comment by bounceme** [comment]
I haven't tried it. maybe copy the html syntax file from vim to your `autoload/indent/` folder
