### ISSUE TITLE
Syntax for class decorators 

### ISSUE THREAD

**Issue by tobiasandersen** [pangloss/vim-javascript#590]
There's currently support for function decorators, e.g.:
    
    @computed // jsDecoratorFunction
    get title () { ... } 

But not for class decorators, e.g.:

    @observer // nothing
    class MyClass { ... }

**Comment by felix-d** [comment]
In the meantime, a simple hack
```vim
au FileType javascript syn match jsDecorator '@[a-zA-Z_][0-9a-zA-Z_$]*'
au FileType javascript hi link jsDecorator Function
```
