### ISSUE TITLE
Nested Indent Bug

### ISSUE THREAD

**Issue by amadeus** [pangloss/vim-javascript#597]
Hey @bounceme, I found a pretty glaring hole with the current indent script:

Start with this (`|` represents cursor):

```js
var obj = {
	func() {
		if (|
	}
}
```

Then press `return` to make a new line: (cursor should probably at least be a tab in here:

```
var obj = {
	func() {
		if (
		|
	}
}
```

But it now gets worse if I type the closing `)`:

```
var obj = {
	func() {
		if (
	)|
	}
}
```

**Comment by bounceme** [comment]
https://github.com/vim/vim/commit/0952131376a517fc12dc5ae908a97018b4ee23f0
 timing haha

**Comment by bounceme** [comment]
It is working fine for me though, using develop

**Comment by amadeus** [comment]
hmm, perhaps its another setting of mine that is getting in the way?

**Comment by bounceme** [comment]
I don't think a setting, maybe something with the jsx plugin? maybe you have some changes locally which are causing this?

**Comment by bounceme** [comment]
asciinema.org/a/cjowbq1ib5wkm5a940eu28m8b

**Comment by amadeus** [comment]
Ahah, I figured out the problem. It all breaks if you have `set smartindent` or `set autoindent` in your .vimrc.

Not sure if we should explicitly disable these in our indent file?

**Comment by amadeus** [comment]
I bet you those lil buggers have been the source of my misc indentation randomness I've had in the past too :(

**Comment by bounceme** [comment]
The autoindent doesn't change anything for me (i've always had it set) but yea, smart indent will do something else entirely

**Comment by bounceme** [comment]
smart indent was removed here -> https://github.com/pangloss/vim-javascript/pull/551/files

try adding the unsetting back into the indent file, if that works maybe we should reconsider that change, @dmitrivereshchagin

**Comment by dmitrivereshchagin** [comment]
According to Vim documentation `'smartindent'` has no effect when `'indentexpr'` is set. I have the same results with or whithout `'smartindent'`.

Maybe I misunderstood something. @amadeus please explain what you expect and what you get.

**Comment by amadeus** [comment]
I am not sure exactly why mine was breaking with `smartindent`, perhaps it was a mix of another plugin, and I don't really have the patience or time right now to try and debug it.

However, the fix of disabling `autoindent` appears to work great, and is something we should definitely do if we are all noticing the issue, or at the very least, document it in the README.

@dmitrivereshchagin the TL;DR: (`|` === cursor)

With `autoindent` I got this:

```js
var obj = {
    func() {
        if (
    )|
    }
}
```

When I expected this:
```js
var obj = {
    func() {
        if (
        )|
    }
}
```
