### ISSUE TITLE
async keyword not properly highlighted in various places

### ISSUE THREAD

**Issue by Arch-Mage** [pangloss/vim-javascript#598]
I found `async` keyword is not properly highlighted places. Here some which I found.

```javascript
export default async function fn() {} // Got 'jsExportContainer'
export async function fn() {} // Got 'jsExportContainer'

class Class {
  async method() {}  // Got 'jsClassMethodType'
  static staticMethod = async function() {} // Got 'jsClassValue'
}

const object = {
  async method1() { }, // Got 'jsObjectMethodType'
  method2: async function() { }, // Got 'jsObjectValue'
  method3: async () => {} // Got 'jsFuncCall'
}
```
I think `async` keyword there should be highlighted as `jsAsyncKeyword`.

**Comment by mixedCase** [comment]
@amadeus Voting for reopening. Bug still present for the most part. Copypasting OP's snippet gives me this: https://i.imgur.com/fifGcOp.png

**Comment by leomao** [comment]
Is this issue going to be fixed?
Adding `jsAsyncKeyword` into `jsExpression` cluster can solve this.
But I am not sure if it is the correct way to solve this problem...
