### ISSUE TITLE
Increment and decrement ("++","--") treated as binary operators

### ISSUE THREAD

**Issue by reynir** [pangloss/vim-javascript#60]
Judging from the indent behaviour it seems the increment and decrement operators are treated like binary operators (or a binary operator followed by a unary operator).

For example,

```javascript
a++
b
```
becomes
```javascript
a++
    b
```

I spent two minutes looking at the code and I believe s:continuation_regex and possibly also s:msl_regex should be altered so they do not match "++" and "--". I do not have a solution.

**Comment by bounceme** [comment]
#396

**Comment by amadeus** [comment]
Fixed in `develop`
