### ISSUE TITLE
labelled blocks

### ISSUE THREAD

**Issue by bounceme** [pangloss/vim-javascript#600]
Wouldn't  be a very high priority bug as i don't think any js dev actually uses these but this breaks highlighting (and subsequently indentation)

```
outer_block: {
  inner_block: {
    console.log('1');
    break outer_block; // breaks out of both inner_block and outer_block
    console.log(':-('); // skipped
  }
  console.log('2'); // skipped
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/break#Examples

**Comment by amadeus** [comment]
This may be a nightmare to support :(

Or maybe not, because I created a bad ass new syntax matching system. I would prefer to hold off on implementing until we start getting people complaining (or if one of us is starting to use it in the workplace xD)

**Comment by bounceme** [comment]
Sounds good to me, unless we see proof of these ever being used just leave this open

**Comment by romgrk** [comment]
Proof
```js
  here: for(var idx in salesReps) {
    var territories = salesReps[idx].territories;

    if (!territories)
      continue here;

    territories = territories.split(',');

    for(var tx in territories) {
      if(territories[tx] == territory) {
        salesRep = salesReps[idx].user;
        break here;
      }
    }
  }
```

**Comment by bounceme** [comment]
I see labelled loops occasionally, but those already work here right? I meant just a block statement

**Comment by bounceme** [comment]
Oh, the indent logic was actually removed in one of my refactorings

**Comment by romgrk** [comment]
Doesn't seem to have any syntax applied on my setup; though I admit I'll use them like once a year.

**Comment by bounceme** [comment]
Close this for #687 ?

**Comment by amadeus** [comment]
Labelled block support is currently being tested in #778 

Assuming no major issues are found in the next few hours, it will get merged into master.

**Comment by amadeus** [comment]
This feature is now in `master`
