### ISSUE TITLE
I think it is not working using Pathogen

### ISSUE THREAD

**Issue by Miguelme** [pangloss/vim-javascript#605]
I've just installed the plugin using pathogen according to the README.md but I see no difference than before in the JS file. How could I tell if the plugin is set up properly ? It would be a huge helper to specify how to, at least, test that it was installed in the README.md

**Comment by bounceme** [comment]
clone it to your $VIM/bundle folder `:h $VIM`, also make sure you installed pathogen correctly

**Comment by bounceme** [comment]
for a single user clone to $HOME/.vim

**Comment by bounceme** [comment]
anyways this is a pathogen user issue, maybe start with an issue there? I believe pathogen is consistent to the point were putting a plugin inside of your .vim folder in your home directory will always work
