### ISSUE TITLE
Correctly indent comma-first objects

### ISSUE THREAD

**Issue by eshao** [pangloss/vim-javascript#609]
Comma first is a very popular style in node repositories. The plugin currently correctly indents comma-first var statements:

```
  var browserify = require("browserify-middleware")
    , express = require("express")
    , r = require('rethinkdb')
```

However, it incorrectly indents comma-first objects:

```
  var test = {
    hello: 'what'
    , no: 'yes'
    , yes: {
      something: 'not'
      , hello: 'no'
      , hello2: 'no'
    }
  }
```

It should be:

```
  var test = {
    hello: 'what'
  , no: 'yes'
  , yes: {
      something: 'not'
    , hello: 'no'
    , hello2: 'no'
    }
  }
```

**Comment by bounceme** [comment]
what is incorrect about that? this is intentional and the way all beautifiers and other editors work which have the ability to differentiate object properties

**Comment by bounceme** [comment]
I'm sorry, i couldn't stand to work with indentation like that so it won't be changed
