### ISSUE TITLE
Indentation issue in import statements

### ISSUE THREAD

**Issue by amadeus** [pangloss/vim-javascript#611]
I found an issue with indentation.

Expected result:

```js
import {
    somObj,
    anotherObj
} from 'example';
```

Actual result:

```js
import {
    someObj,
        anotherObj
} from 'example';
```

**Comment by bounceme** [comment]
so the braces aren't block braces? any other es6 chars that are like that? I already added var/let/const for destructuring

**Comment by bounceme** [comment]
i guess it isn't a block or an object,a member container?

**Comment by bounceme** [comment]
actually a list of es6 or es7 keywords that are allowed before braces which are Not delimiting a block statement would be appreciated

**Comment by bounceme** [comment]
fixed in dev

**Comment by amadeus** [comment]
Word, thanks!
