### ISSUE TITLE
Flow syntax not working

### ISSUE THREAD

**Issue by simonsmith** [pangloss/vim-javascript#612]
Hey,

Firstly, thanks for this great plugin.

I have the option enabled but Flow syntax does not work

```
let g:javascript_plugin_flow = 1
```

I checked this is correct with the following:

``` diff
if exists("javascript_plugin_flow")
+  echo 'test'
  runtime extras/flow.vim
endif
```

It prints `test`.

Adding another `echo` in `extras/flow.vim` does nothing though. However if I paste the entire contents of `extras/flow.vim` into the block above it works as expected.

I'm using Neovim 0.1.5

Anything I'm missing?

**Comment by amadeus** [comment]
I can't seem to reproduce, it appears to work fine for me?

**Comment by amadeus** [comment]
I'm gonna close this since I haven't seen any other issues about this and have been unable to reproduce. If you have more details, feel free to post here and perhaps it can be re-opened.
