### ISSUE TITLE
Flow syntax does not work with es6 Arrow functions when attaching name to arrow function

### ISSUE THREAD

**Issue by sroecakepler** [pangloss/vim-javascript#613]
Flow syntax does not work properly with es6 Arrow functions when attaching a name to the arrow function. See image for example:

![image](https://cloud.githubusercontent.com/assets/8355169/17942339/e82435b2-6a04-11e6-87fc-66acaa6be8b4.png)

**Comment by sroecakepler** [comment]
To elaborate, we would expect "string" to be highlighted in blue for the function "does_not_work" in the same way that it is highlighted for "works" an "also_works". Since it is not highlighted, this appears to be a bug.

**Comment by amadeus** [comment]
This should be fixed in `master`
