### ISSUE TITLE
Inserting the closing character of a pair doesn't "jump" with autoclose plugins

### ISSUE THREAD

**Issue by romgrk** [pangloss/vim-javascript#615]
Hi there,

This is a duplicate of https://github.com/Raimondi/delimitMate/issues/248, but I think there might be something interfering with the auto-close feature of some plugins. Or maybe not, but I was wondering if you could help.

Using Raimondi/delimitMate:
```
 I type ;  I get  ;  I want
   ()   ;   ()|)  ;  ()|
```

Using Townk/vim-autoclose:
```
 I type ;  I get  ;  I want
   (    ;   (|   ;  (|)
```

Also it only happens with `()` and `{}`. It works fine with `[]`, `''`, `""` and backticks.
Also, `()` and `{}` work fine inside a string, with all three string delimiters.

Turning syntax off solves the problem. 
Tested on both `master` and `develop` branches, same result.

**Comment by bounceme** [comment]
sorry this isn't a solution but what you can try is this instead of a full plugin, though it isn't quite the same
```
fun! MyCR()
  if getline('.')[col('.')-2] == '{' && col('.') == col('$') &&
        \ synIDattr(synID(line('.'),col('.') - 1,0),'name') !~? '\%(string\|regex\|comment\)'
    return "\<CR>}\<C-o>O"
  end
  return "\<CR>"
endfun
inoremap <CR> <C-R>=MyCR()<CR>

```

**Comment by bounceme** [comment]
I couldn't reproduce

**Comment by romgrk** [comment]
For reference, I ended up using [lexima](https://github.com/cohama/lexima.vim).
