### ISSUE TITLE
Syntax highlighting is very broken

### ISSUE THREAD

**Issue by Fer22f** [pangloss/vim-javascript#616]
I don't know what happened, but one day, I updated my vim-javascript, and it broke basically everything. It's been like this for a while, maybe 1-2 months. A few examples as follows:

![braces](https://cloud.githubusercontent.com/assets/3057302/18037036/05d665b8-6d51-11e6-9d11-8a0e8b9e8755.png)
Broken detection of closing and opening braces, parenthesis and square brackets.

![generalbroken](https://cloud.githubusercontent.com/assets/3057302/18037057/89e7da62-6d51-11e6-9452-e35617373f8d.png)
Broken detection of keywords inside functions: All those highlighted in bold green are "function names" in gruvbox, but aren't. I didn't capture in this picture but in the end, `}])` is also broken and marked as red.

This happened suddenly, in a quick update, and sometimes I just think it's better to disable syntax highlighting all together or use the one that comes with vim (which I think doesn't work with => and other new syntaxes) because those opening/closing braces errors throw me off, a lot.

Oh, I should mention, the lambda symbol is just a conceal operation for "function" provided by the plugin vim-lambdify.

**Comment by amadeus** [comment]
If you disable conceal chars, does it work ok?

**Comment by Fer22f** [comment]
Oh yes, it does work! However I think I had vim-labdify before.

**Comment by Fer22f** [comment]
It's a far more interesting interaction than I thought before: that function() inside myDirective turns into a lambda properly if I don't use vim-javascript, and instead, I use vim's default javascript highlighter.

**Comment by amadeus** [comment]
Aha, try using our conceal characters API instead:

https://github.com/pangloss/vim-javascript#concealing-characters

**Comment by Fer22f** [comment]
Welp, thanks for the help, I didn't even know these were available! :)

**Comment by amadeus** [comment]
No problem, glad you got it sorted!
