### ISSUE TITLE
Incorrect indentation for multiline expressions:

### ISSUE THREAD

**Issue by sassanh** [pangloss/vim-javascript#620]
Look at these examples:

```
if (true &&
    false &&
        false &&
        false)
    return 1;
```
```
const a = (1 +
    2 +
        3 +
        4);
```
```
const a = <div x={{
    y: z,
        u: v,
}}>
</div>;
```
```
const a = <div x={true
    ? 1
        : 2
}>
</div>;
```

I think the current logic that prevents double indentations, should somehow extend itself to next lines.

**Comment by sassanh** [comment]
Another issue caused by this behavior is discussed here: https://github.com/mxw/vim-jsx/issues/116#issuecomment-244227298 and here: https://github.com/pangloss/vim-javascript/issues/618#issuecomment-243972420

**Comment by bounceme** [comment]
this shouldn't be happening:
```
const a = <div x={{
    y: z,
        u: v,
}}>
</div>;
```

**Comment by sassanh** [comment]
Yeah the one you mentioned is fixed only in dev branch, but that's not the point. Instead of fixing them one by one with exceptions and user configuration and likes I guess we should just extend the double indentation elimination to following lines.

**Comment by sassanh** [comment]
Or don't eliminate it at all if it makes sense.

**Comment by bounceme** [comment]
So are you going to post your preferred indent results? These are only 'fixable' by doubling the indent for the first line,which is a change much broader than you imagine, there will be unexpected changes in **Most** js files (also consider continuations after switch case statements, where an arbitrarily large offset will be further increased)  .
```
switch () {
 case 1: return new Error('hey' +
      'look')
```
> Or don't eliminate it at all if it makes sense.
that doesn't

here is your other issue touching the same issue: 
https://github.com/pangloss/vim-javascript/issues/557#issue-166404060

this could also be an option

**Comment by sassanh** [comment]
The moment we agree this is a problem that should be fixed, instead of something that we should coup with, the we can list solutions and decide which one to implement. I'm sure you and @amadeus will find better solutions than what I can think of.

> which is a change much broader than you imagine, there will be unexpected changes in Most js files

Well, this is the develop branch, that's how it goes in develop branch. You may change fundamental things, you take care to do it right and avoid bugs and problems then you see how it goes by testing it with real cases.

> that doesn't

It doesn't make sense for me too. I think we should extend eliminating the second indent (keeping it single indented) for following lines. You may say that's not possible in current implementation with regexps and we may need CFG or using some libraries which parse the js file grammar wise (I'm sure there are good ones out there, eslint for example should be one of these, or babel.) Then we may postpone this for future till someone has time to do it, I don't know. But none of these change the fact that this problem exists and we should have a plan for it. The plan may be "lets postpone it for 50 years" 😆

**Comment by sassanh** [comment]
Btw I'm sure https://github.com/pangloss/vim-javascript/issues/557#issue-166404060 was solved when I checked out `develop` lots of things were solved in `develop` I was really impressed how stable it was when I checked it out. But suddenly after an update many things broke. I think I felt it because I'm using jsx and it bolds the issues.

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/issues/557#issuecomment-233841113

i'll add an option and default to the new behaviour to guage the response. Sometime this weekend

**Comment by sassanh** [comment]
No rush, thanks.
