### ISSUE TITLE
Indentation regression

### ISSUE THREAD

**Issue by vxsx** [pangloss/vim-javascript#626]
Currently the indentation for multiline comments seems to be broken, e.g. if i have:
```
/**
 * |@function getLatestVersionData
 * @returns {$.Deferred}
 */

```
where `|` is the cursor position, if i press `o` the result would be this:
```
/**
 * @function getLatestVersionData
    * |
 * @returns {$.Deferred}
 */
```
Which is incorrect.

I did some bisecting and it shows https://github.com/pangloss/vim-javascript/commit/32e7c78716ec72f60c7962af22a8eadc287b579c as a first bad commit but I couldn't really figure out which change broke it

**Comment by bounceme** [comment]
try on the dev branch, thanks

**Comment by vxsx** [comment]
@bounceme tried, no difference in behaviour

**Comment by vxsx** [comment]
actually, I rechecked with all other plugins disabled, and it seems like the behaviour changes to correct one if i disable `yggdroot/indentline` plugin

sorry for the false alarm
