### ISSUE TITLE
ES6 import is a bit off when destructing on multiple lines

### ISSUE THREAD

**Issue by blacksails** [pangloss/vim-javascript#634]
When importing something  using ES6 import and destructing it on multiple lines, it gets indented a bit weird.

The following is indented by vim-javascript:
```javascript
import { 
  LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_USERNAME_CHANGE,
    LOGIN_PASSWORD_CHANGE
} from "../actions/session"
```

What I would expect:
```javascript
import { 
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_USERNAME_CHANGE,
  LOGIN_PASSWORD_CHANGE
} from "../actions/session"
```

**Comment by amadeus** [comment]
Check out `develop` branch, this should be fixed. And we plan to merge to `master` shortly.

**Comment by blacksails** [comment]
@amadeus Ah. Thanks. Im just closing this then.
