### ISSUE TITLE
require( is not highlighted

### ISSUE THREAD

**Issue by dbellavista** [pangloss/vim-javascript#639]
``` js
// test.js
const test = require("test");
```

By using this utility: http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

The High group of `require` is:

`hi<jsFuncCall> trans<jsFuncCall> lo<jsFuncCall>` instead of **jsGlobalNodeObjects**

**Comment by dbellavista** [comment]
Sorry, got it. Only the `require` keyword should be highlighted

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/issues/410

**Comment by dbellavista** [comment]
Thanks, but just in case, the purpose of this instruction:
```vim
syntax match   jsGlobalNodeObjects  /require/ contains=jsFuncCall
```
(https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L118)

Wasn't to set the `require(` as a __jsGlobalNodeObjects__ ?

**Comment by bounceme** [comment]
@amadeus , any thoughts?

**Comment by amadeus** [comment]
Fixed in `develop`

**Comment by dpiccone** [comment]
It might be related to this, but I get this situation whenever I call a function that contains require in the name.

![screenshot from 2016-10-31 09-36-20](https://cloud.githubusercontent.com/assets/1982461/19848386/7e268eca-9f4d-11e6-837e-23533cdc4d0f.png)

**Comment by bounceme** [comment]
should be a word boundary in the regex, thanks !

**Comment by dpiccone** [comment]
Since `require` is part of global objects https://nodejs.org/api/globals.html shouldn't this be declared here instead? 

https://github.com/pangloss/vim-javascript/blob/997c2b12f5fffedd3a787b8840dfe710b2e6d3f9/syntax/javascript.vim#L116

**Comment by amadeus** [comment]
Fixed!
