### ISSUE TITLE
JsBrackets highlighting insconsistency

### ISSUE THREAD

**Issue by cjnucette** [pangloss/vim-javascript#641]
Hi, I'm trying to highlight arrays brackets with the following line in my init.vim:

`hi! jsBrackets guifg=#268bd2 guibg=NONE gui=NONE`

And it works like it should when the array is part of an expression

![screenshot from 2016-09-23 08-45-56](https://cloud.githubusercontent.com/assets/2278326/18786130/56eeae7e-816a-11e6-9039-a70ee0a56928.png)

But it doesn't when it is a part of a definition like this

![screenshot from 2016-09-23 08-48-06](https://cloud.githubusercontent.com/assets/2278326/18786172/838b6792-816a-11e6-9557-d14e68988055.png)

actually if I surround the array definition it works

![screenshot from 2016-09-23 08-50-09](https://cloud.githubusercontent.com/assets/2278326/18786229/d69a8b52-816a-11e6-81ee-a4c885958578.png)

Is jsBracket the correct key (tag, identifier???) for this? or Am I doing something wrong.

(Sorry if my English is not very good looking ;p)

**Comment by amadeus** [comment]
Are you on the latest version of the plugin?

Your `hi` shouldn't doesn't need the `!` in it however it should it should still work.

Here's a quick screenshot with me setting `jsBrackets` to green:

![example](https://dl.dropboxusercontent.com/s/gu6b13swfm4ecdu/_2016-09-23_10-59-43.png?dl=0)

My guess is perhaps another plugin is at play here?

**Comment by cjnucette** [comment]
Yes it was a plugin problem with `mhartington/vim-folds`. Next time i'll make sure to do this before open an issue.
Thanks.

**Comment by amadeus** [comment]
No problem at all! Glad you got it sorted!
