### ISSUE TITLE
Include NodeJS __dirname & __filename

### ISSUE THREAD

**Issue by romgrk** [pangloss/vim-javascript#643]
Hi there,

Forgot to include these in https://github.com/pangloss/vim-javascript/issues/534 but `__filename` and `__dirname` would be good to have. These two are "globals", aka they vary for each file but are always defined.

**Comment by bounceme** [comment]
https://nodejs.org/api/globals.html#globals_class_buffer
shows a few other globals are in node: Buffer, and the immediate timing functions

**Comment by bounceme** [comment]
probably just __file/dirname and Buffer
