### ISSUE TITLE
ES6 shorthand property names

### ISSUE THREAD

**Issue by romgrk** [pangloss/vim-javascript#644]
As of ES6:

``` js
var o = { a, b, c };
```

is equal to:

``` js
var o = { a: a, b: b, c: c };
```

Currently, the syntax doesn't apply the `jsObjectKey` group to these.

Ref: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by amadeus** [comment]
Yeah, so I'm aware of this, and I thought about it a bunch as well. It's kinda NOT a key, even tho it evaluates to one based on the name. Technically it's a variable tho, so I've left it different.

**Comment by romgrk** [comment]
Yea, I had taught about that without making my mind if it was a variable or a key.
My motivation to submit it was that if you have for example:
```js
var o = {
  key: value,
  notkey
}
```
Then the `notkey` is not highlighted. 
My main argument for implementing this would be that if you're reading the code, and look at some object declaration, you want to have an idea of the keys that this object possesses; having one key (or notkey) in a different color makes it slightly more difficult to know that.

**Comment by fvictorio** [comment]
Is there a group that can be used for the keys in shorthand notation?

**Comment by bounceme** [comment]
> Is there a group that can be used for the _identifiers_ in shorthand notation?

**Comment by amadeus** [comment]
I'll look at refactoring the `jsObjectKey` group later this weekend to see if I can come up with a fix

**Comment by hovissimo** [comment]
Just an opinion:

```javascript
do_the_thing({
   foo: bar,
   baz, 
}
```

`baz`'s role as an object key is more important to me here than `baz`'s role as variable name.

I support highlighting it as `jsObjectKey`.

**Comment by bounceme** [comment]
\*P.r.s Welcome\*
