### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by pangloss** [pangloss/vim-javascript#65]

**Comment by amadeus** [comment]
Can we add @bounceme as a collaborator, please?

**Comment by pangloss** [comment]
done

**Comment by amadeus** [comment]
Thanks!

**Comment by amadeus** [comment]
Also @pangloss, there's a new feature now in Github where you can set branches to be Protecte, so they can't be deleted or force pushed too.

I'd suggest at the very least that master gets set as protected to prevent any accidental herp derps.
