### ISSUE TITLE
ES7 static Object syntax highlighting broken?

### ISSUE THREAD

**Issue by MaxMEllon** [pangloss/vim-javascript#655]
![2016-10-03 23 59 36](https://cloud.githubusercontent.com/assets/9594376/19042047/78a7699e-89c5-11e6-9f62-7449e30accd6.png)

`foo` syntax group is `javascriptClassBlock->javascriptMethodName`
`bar` syntax group is `javascriptClassBlock->javascriptMethodName`

**Comment by amadeus** [comment]
Unfortunately I cannot replicate. Perhaps you can dig around your configuration a bit and try to isolate it? It could be a competing plugin or something.

**Comment by MaxMEllon** [comment]
I'm sorry. 
I had read the other Plugins... 
thanks.
