### ISSUE TITLE
Split indentation script to separate repo?

### ISSUE THREAD

**Issue by olalonde** [pangloss/vim-javascript#657]
I'm using [othree/yajs.vim](https://github.com/othree/yajs.vim)  for syntax (mainly because I'm used to the colors) but it unfortunately [does not](https://github.com/othree/yajs.vim/issues/133) include indentation support. As a workaround, I'm [now](https://github.com/othree/yajs.vim/issues/20#issuecomment-251559310) using [rschmukler/pangloss-vim-indent](https://github.com/rschmukler/pangloss-vim-indent) which is a an outdated fork of this repo's indent support.

I was wondering, if it's not too much trouble, if it would be possible to have an official repo for indentation support separate from the syntax highlighting one so that it can be used with other syntax scripts (or make it possible to load this plugin but only enable the indentation support).

**Comment by bounceme** [comment]
apparently vim allows you to override syntax files, though i'm not really sure how. Anyway the indent script is included with recent versions of vim so you won't need this repo if that is all you want (I recommend the syntax file in this repo though, as it is much faster than yajs and that actually affects indentation speed, also it is just very high quality). and yes splitting the repo would be too much trouble

**Comment by bounceme** [comment]
I tried installing yajs and the syntax was overridden and indentation worked fine. I've also made sure the indent was compatible yajs in the past so either @othree made some recent syn-naming changes or you are installing things in a strange way.

**Comment by olalonde** [comment]
Ok, thanks. Guess I can just try to get used to vim-javascript's syntax colouring.

**Comment by bounceme** [comment]
It is possible to keep using yajs. there may be something going on in your config though. yajs needs to be loaded before the one in pangloss
