### ISSUE TITLE
Indentation of multiline parentheses in return and assign statements is wrong

### ISSUE THREAD

**Issue by madox2** [pangloss/vim-javascript#663]
When I press enter inside parentheses in return or assign statements, the indentation of last parenthesis is wrong. For example when I press enter here:

```
function render() {
  return (|<ENTER>)
}
```

I would expect:

```
function render() {
  return (
    |<CURSOR>
  )
}
```

but actually the last parenthesis is not indented:

```
function render() {
  return (
    |<CURSOR>
)
}
```

**Comment by bounceme** [comment]
Can't reproduce(on dev). I'd try disabling the plugin for parentheses expanding.

**Comment by bounceme** [comment]
also remove other js syntax/indent files if you have them

**Comment by madox2** [comment]
I've found out that is is actually problem with jiangmiao/auto-pairs plugin. Thanks for help!
