### ISSUE TITLE
Syntax highlighted is getting worse 

### ISSUE THREAD

**Issue by PezCoder** [pangloss/vim-javascript#666]
### What ??
My syntax highlighting is getting worse after I included this plugin as compared to without any plugin.

Here's **with** including 'vim-javascipt'
![image](https://cloud.githubusercontent.com/assets/8057916/19237857/7e94333a-8f1c-11e6-9518-b2ad32f30412.png)

& Here's **without** 'vim-javascript'
![image](https://cloud.githubusercontent.com/assets/8057916/19237868/8d1148b2-8f1c-11e6-9f5b-19a88188fc34.png)

Although this plugin has improved my indentation but the syntax highlighting as you can see is messed up.

### My System Config
I'm using Vim v7.3.
Mac OSX El capitan
Please help!

**Comment by bounceme** [comment]
Only differences I see are that self is being highlighted everywhere, and the colors are slightly different (depends on the color theme)

**Comment by bounceme** [comment]
and self is referring to `window.self` which is wrong

**Comment by landabaso** [comment]
I'm also getting subtle differences in my color scheme. Since the issue is closed, should we assume this something supposed to happen?

**Comment by bounceme** [comment]
yes
