### ISSUE TITLE
Flow type definitions

### ISSUE THREAD

**Issue by wokalski** [pangloss/vim-javascript#669]
Flow type definitions don't work correctly

```js
type T = {
  foo: string
}
```

Such definition is not highlighted. Namely, type and type name are highlighted with the same color and the rest is just plain text.

**Comment by bounceme** [comment]
They just aren't highlighted by the color scheme. there are several groups active ('string' is `jsflowtypevalue`  'foo' is `jsflowobjectkey` etc.)

**Comment by amadeus** [comment]
Did you set the appropriate global from the README?

**Comment by wokalski** [comment]
@bounceme ugh. Sorry for bringing that up! Thanks 👍 .
