### ISSUE TITLE
Incorrectly highlighted brace in JSX

### ISSUE THREAD

**Issue by hakunin** [pangloss/vim-javascript#674]
Hi,
the ted highlight on this brace is incorrect in the JSX syntax:

![screenshot 2016-10-18 10 56 55](https://cloud.githubusercontent.com/assets/65846/19470995/d3ab3a98-9521-11e6-877a-149117b9022c.png)

**Comment by amadeus** [comment]
You need to be using the [vim-jsx](https://github.com/mxw/vim-jsx) plugin alongside ours. Also you need to make sure the filetype is set to `javascript.jsx`.
