### ISSUE TITLE
Small JSX Indent Issue

### ISSUE THREAD

**Issue by amadeus** [pangloss/vim-javascript#680]
I found a small, fairly easy to reproduce issue with JSX.

Start with the following case (`|` denotes the cursor):

```jsx
const Component = React.createClass({
    render() {
        return (
            <div>
                {this.test}
                <div>|</div>
            </div>
        );
    }
});
```

Then press enter, the result:

```jsx
const Component = React.createClass({
    render() {
        return (
            <div>
                {this.test}
                <div>
            |</div>
            </div>
        );
    }
});
```

The expected result:

```jsx
const Component = React.createClass({
    render() {
        return (
            <div>
                {this.test}
                <div>
                |</div>
            </div>
        );
    }
})

```

**Comment by bounceme** [comment]
Make sure you have the mxw/vim-jsx plugin and the filetype set @amadeus !
Actually though this should be an issue with vim-jsx . But i can't get that plugin to set the correct indentexpr . 


You can test with `:set indentexpr?` which should be the jsx one, though it isnt for me

**Comment by bounceme** [comment]
Yea it's a bug with vim-jsx. I think it has to do with the syntax highlighting.

**Comment by amadeus** [comment]
I do have the plugin and filetype set properly.

The syntax highlighting appears fine though? I'll do a bit more tracing later to see for sure.
