### ISSUE TITLE
Regressions

### ISSUE THREAD

**Issue by sassanh** [pangloss/vim-javascript#681]
After merging `master` to `develop` some fixes (related to https://github.com/pangloss/vim-javascript/issues/620 and https://github.com/pangloss/vim-javascript/issues/618 I guess) are broken. For example:

```
return <div
style={{
    position: 'relative',
        width: '210mm',
        height: '297mm',
        pageBreakAfter: 'always',
}}>
```
which should be:
```
return <div
style={{
    position: 'relative',
    width: '210mm',
    height: '297mm',
    pageBreakAfter: 'always',
}}>
```
and I'm sure it was fixed.

**Comment by bounceme** [comment]
You need vim-jsx.

**Comment by bounceme** [comment]
You said before you were using a modified vim-jsx , this may be the issue. Only support for embedded syntaxes is from recognized external syntax files. Confirm if that is the cause please.

**Comment by bounceme** [comment]
Works for me ( on dev ) . other issues should be directed to vim-jsx until they can be confirmed as problems directly caused by this repo

**Comment by sassanh** [comment]
@bounceme I do use vim-jsx and I'm using vim-javascript develop branch too. It happens with unmodified version of vim-jsx too. I wonder what's the difference in our setups that it's working for you and not for me.
It checked out past commits one by one and found that it gets broken in this commit: https://github.com/pangloss/vim-javascript/commit/baa07dd.

This is the synid list of in the parent commit of above mentioned commit in which it works alright:
```
['jsExportContainer', 'jsClassBlock', 'jsFuncBlock', 'jsxRegion', 'htmlTag', 'htmlValue', 'jsBlock', 'jsObject', 'jsObjectKey']
```
And this is the synid list after checking out above mentioned commit (which breaks the indentation):
```
['jsExportContainer', 'jsClassBlock', 'jsFuncBlock', 'jsxRegion', 'htmlTag', 'htmlValue', 'jsBlock', 'jsObject', 'jsObjectKey']
```

They're the same. vim-jsx runs vim-javascript's indentation in js blocks and it is a js block inside the jsx block so it's indented by vim-javascript. It is the same double indent issue we discussed earlier.  I guess it'll be much cleaner if we solve it in vim-javascript.

**Comment by bounceme** [comment]
Html synids are the issue aswell as vim-jsx is just very buggy. I'm certain that this is an issue with your configuration as it works fine. I'm not going to get into this again.

https://github.com/MaxMEllon/vim-jsx-pretty
works much better in my experience.

**Comment by bounceme** [comment]
also adding support for non-standard jsx constructs will absolutely **not** be cleaner. That would be ridiculous for this repo to code around a bug caused by https://github.com/mxw/vim-jsx

**Comment by sassanh** [comment]
Thanks for introducing vim-jsx-pretty. vim-jsx-pretty has problems too, for example it indents like this:
```
                            <text
                                x={35 + 30 * index}
                                y='104'
                                transform={`rotate(60, ${35 + 30 * index}, 104)`}
                                textAnchor='end'
                                fontSize='.5em'
                                direction='rtl'>
                                {material === 0 ? gettext('All') : (material.title.substring(0, 8) +
                                    (material.title.length > 8 ? '...' : ''))}
                                </text>
```
last line has extra indentation. This is really bad but the good point is that it's absolutely related to that repo and I can follow it there.

Thanks for info :-)
