### ISSUE TITLE
wrong highlight with ES6 block scope

### ISSUE THREAD

**Issue by gera2ld** [pangloss/vim-javascript#687]
In such case, highlights and indentations do not work:

``` js
{
  function a() {}
  a();
}
```

![image](https://cloud.githubusercontent.com/assets/3139113/19679210/8b953cc4-9ad3-11e6-8e85-15d13f2b916b.png)

**Comment by bounceme** [comment]
what is different in es6? could you link to documentation?

**Comment by gera2ld** [comment]
In ES6, a block (`{ ... }`) is like a closure, which means the code:
``` js
{
  function a() {}
  a();
}
```
is like:
``` js
!function () {
  function a() {}
  a();
}();
```
But in the case I mentioned earlier, code inside a block will not be highlighted correctly.
Sorry for the indentations report but I could not reproduce it now.
Ref: http://es6-features.org/#BlockScopedFunctions

**Comment by bounceme** [comment]
good news! https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-01/jan-29.md#function-in-blocks-in-non-strict-mode  : more info

**Comment by amadeus** [comment]
Ugh, this change is literally gonna be the death of me 😪

**Comment by amadeus** [comment]
If you check #778, I have a working implementation of block statements and labels.

It should be merged in in the next few hours barring no major issues are found.
