### ISSUE TITLE
Highlight calls to "fetch" API

### ISSUE THREAD

**Issue by mixedCase** [pangloss/vim-javascript#688]
https://fetch.spec.whatwg.org/

Fetch is the promise-based XMLHttpRequest replacement. It's globally available such as other currently highlighted objects like `console` and `window`.

Example code taken from the MDN:
```javascript
fetch('flowers.jpg').then(function(response) {
  if(response.ok) {
    response.blob().then(function(myBlob) {
      var objectURL = URL.createObjectURL(myBlob);
      myImage.src = objectURL;
    });
  } else {
    console.log('Network response was not ok.');
  }
})
.catch(function(error) {
  console.log('There has been a problem with your fetch operation: ' + error.message);
});
```

**Comment by bounceme** [comment]
There are tons of other web apis. should we just add whichever ones people ask for? yajs uses a webidl system for this, but the keywords pollute other things like user defined prop names

**Comment by mixedCase** [comment]
Good enough for GitHub and VSCode from what I've paid attention to today.

**Comment by bounceme** [comment]
we don't highlight any bultin method calls, but highlighting `fetch` seems alright

**Comment by bounceme** [comment]
https://developer.mozilla.org/en-US/docs/Web/API

any one keen to make the p.r. ?
