### ISSUE TITLE
Highlighting identifiers as jsFuncName when used with arrow functions

### ISSUE THREAD

**Issue by apazzolini** [pangloss/vim-javascript#694]
To make identifying functions easier, it would be really nice if we could highlight identifiers that hold arrow functions as functions themselves.

For example,

![image](https://cloud.githubusercontent.com/assets/869471/19977317/33ec32a8-a1c1-11e6-8a47-41a99c6de6e2.png)

`doSomething` is identified as `jsFuncName` whereas
`doSomethingElse` is identified as `jsVariableDef`.

The Babel ES6 grammar in Atom handles this, but I'm not sure if it has more capabilities than what we're able to do in Vim.

**Comment by bounceme** [comment]
is that technically a function definition, or assignment to a function expression? If the second, it is more accurate as-is.

**Comment by bounceme** [comment]
a p.r. for this may be accepted if there is a stronger argument for it. It is up to @amadeus

**Comment by apazzolini** [comment]
@bounceme I agree it's more accurate to call it a function expression assigned to a variable, and if we could identify it as such users can customize how they'd like to color it.

I'd be happy to submit a PR to identify it as such, but I've banged my head against Vim's syntax highlighting for a couple hours with no progress - do you have an off the top of your head suggestion on how to go about implementing this pattern?
