### ISSUE TITLE
highlights in comment when used with javascript-libraries-syntax

### ISSUE THREAD

**Issue by with0out** [pangloss/vim-javascript#700]
When I use **vim-javascript** with **javascript-libraries-syntax.vim** together, unwanted highlights will appear in comments:
![Imgur](http://i.imgur.com/s8xAxWm.png)

Are there any workaround to make these highlight go away?
Thanks!

[Issue](https://github.com/othree/javascript-libraries-syntax.vim/issues/53) in their Repo

**Comment by amadeus** [comment]
This is not really an issue with our plugin, it would need to be fixed in the other plugin, sorry.
