### ISSUE TITLE
When used with javascript-libraries-syntax, all the "ng-*" html attribute cannot be properly highlighted.

### ISSUE THREAD

**Issue by xc1427** [pangloss/vim-javascript#704]
**Environment**: Windows 10 64bit, gvim8.0 64bit.

Here is the syntax highlighting:

![image](https://cloud.githubusercontent.com/assets/5611770/20159996/6e6aaf18-a6e4-11e6-8453-1c95a4fc41d9.png)

The problem comes from `vim-javascript/syntax/javascript.vim @ line 17`
```vimL
syntax iskeyword @,48-57,_,192-255,$
```
When reading html file, gvim also loads javascript.vim syntax file (I also want to know how this is done if someone can kindly teach me :) )

As `syntax iskeyword` does not include hyphen `-`, all html attributes which contain hyphen cannot be recognized as `htmlArg` but as `htmlTag` ([This script can identify syntax highlighting](http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor)).

My workaround is to add to _vimrc:
```vimL
autocmd FileType html syntax iskeyword @,48-57,_,192-255,$,-
```
Then highlighting is correct:

![image](https://cloud.githubusercontent.com/assets/5611770/20160397/f4fb0c92-a6e6-11e6-8123-30cb52b36c3c.png)

But I think it is better to be done cleanly in vim-javascript plugin.

**Comment by bounceme** [comment]
the hyphen isn't a keyword character in js though.

https://github.com/pangloss/vim-javascript/issues/153

**Comment by bounceme** [comment]
Essentially, there is an issue with the html script which this repo can't fix, it being for javascript files.
