### ISSUE TITLE
Ellipsis (spread operator) parse issue

### ISSUE THREAD

**Issue by cjnucette** [pangloss/vim-javascript#707]
I just notice that the ellipsis (spread operator) is being parsed as two jsNoise and a jsPropertyAccessExpr, and this makes it look a little bit weird:

![screenshot from 2016-11-12 13-49-20](https://cloud.githubusercontent.com/assets/2278326/20239770/f7e1924c-a8de-11e6-9941-fb86211d0cfa.png)

**Comment by cjnucette** [comment]
The same thing happen in this case:

![screenshot from 2016-12-12 10-18-33](https://cloud.githubusercontent.com/assets/2278326/21102492/d7a355dc-c054-11e6-92f7-c1091633068d.png)

**Comment by bounceme** [comment]
you have a jsx plugin?

**Comment by amadeus** [comment]
This is actually a legitimate bug, I'll look to fix soon

**Comment by cjnucette** [comment]
@bounceme: Yes i have.

**Comment by amadeus** [comment]
Fixed!

**Comment by cjnucette** [comment]
Sorry i keep reopening this issue

![screenshot from 2017-01-13 22-47-42](https://cloud.githubusercontent.com/assets/2278326/21951761/a4dcd40a-d9e2-11e6-8254-973334be8754.png)

`call plug#begin('~/.vim/jsplugged')
" syntax
  Plug 'pangloss/vim-javascript', {'for': ['javascript']}
  Plug 'crusoexia/vim-javascript-lib', {'for': ['javascript']}
  Plug 'moll/vim-node', {'for': 'javascript'}
  Plug 'flowtype/vim-flow', {'for': 'javascript'}

"   " Colorschemes
  Plug 'mhartington/oceanic-next'
  Plug 'https://github.com/crusoexia/vim-monokai.git'
  Plug 'lifepillar/vim-solarized8'
  Plug 'joshdick/onedark.vim'
  Plug 'atelierbram/Base2Tone-vim'

" misc stuff
  Plug 'neomake/neomake'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'

" Neocomplete stuff
  Plug 'Shougo/neocomplete'
  Plug 'ternjs/tern_for_vim', {'for': 'javascript', 'do': 'npm install'}

call plug#end()`
