### ISSUE TITLE
Ability to highlight html/css in tagged template literals

### ISSUE THREAD

**Issue by marlun** [pangloss/vim-javascript#712]
There's a lot of tools now which works as follows

    var view = html`
      <div class"parent">
        ${parentVar}
        <div class="child">${childVar}</div>
      </div>
    `

and

    var styles = css`
      border-color: green;
      background-color: yellow;
    `

How would we add support for HTML and CSS highlighting inside a javascript file for those situations?

After reading in the vim mailinglist I thought I could do it with something like this in after/syntax/javascript.vim but it's not working

    unlet b:current_syntax
    syntax include @CSS syntax/css.vim
    syntax region sheetify matchgroup=Type start="css`" end="`" contains=@CSS

**Comment by bounceme** [comment]
Quramy/vim-js-pretty-template

**Comment by marlun** [comment]
Is that the solution? I tried it and didn't get it working. Will add an issue over there too.

**Comment by bounceme** [comment]
looking at the source of that plugin, I can;t see any reason a tagged template would act different. My guess, though I don't know much about vim syntax files, and have never tried this plugin, is that it is a conflict with the syntax file in this repo.

**Comment by geoyws** [comment]
Template literals containing CSS and HTML are still not highlighting in August 2017. :(

**Comment by bounceme** [comment]
> in August 2017


It is an open bug isn't it? noone who contributes, to my knowledge, wants/cares about it since there isn't any difference between ```html`<body>` ``` and ```html`?not html` ``` .

**Comment by geoyws** [comment]
we can leave it as an option for users to opt-in to parse template literals with tags as HTML... just do a simple regex check perhaps? Highly likely that people would love their HTML/CSS template strings syntax highlighted IMHO

**Comment by bounceme** [comment]
> Highly likely that people would love their HTML/CSS template strings syntax highlighted IMHO

my point is that it doesn;t seem so

**Comment by marlun** [comment]
Unfortunately I never got it working, would still love it though.

**Comment by bounceme** [comment]
going to close this to prevent useless debates. Rather, make a pr (either here or js-pretty-template repo). If you choose the plugin route (dynamic, complex commands, multi-filetypes) , don't bother here. If you were to copy the `extras/jsdoc.vim` approach, (syntax which only affects one syntax group (in this case `comment`, within an optional file) you could get it into this repo.

**Comment by jesstelford** [comment]
For those passing through, this is what I got:

![jsx-gql-styled-highlighting](https://user-images.githubusercontent.com/612020/29912070-b5696cf2-8e73-11e7-9fcc-ade990c74085.png)

My setup:

- https://github.com/jesstelford/vim-js-pretty-template (commit `f3431ae` / `no-default` branch)
- https://github.com/mxw/vim-jsx (commit `b098827`)
- https://github.com/pangloss/vim-javascript (commit `ee376ba`)

`~/.vimrc`
```vim
let g:jsx_ext_required = 0 " Works on files other than .jsx

if has('autocmd')
  " Support `-` in css property names
    augroup VimCSS3Syntax
        autocmd!
        autocmd FileType css setlocal iskeyword+=-
    augroup END

    call jspretmpl#register_tag('gql', 'graphql')
    " Use sass highlighting for `styled.span` / `styled.div` / etc
    call jspretmpl#register_tag('\v(styled\.\w+)', 'scss')
    autocmd FileType javascript.jsx JsPreTmpl
    autocmd FileType javascript JsPreTmpl
endif
```

**Comment by jesstelford** [comment]
My updated setup, which is working:

- **new** https://github.com/styled-components/vim-styled-components (commit `7447cfd`)
- https://github.com/jesstelford/vim-js-pretty-template (commit `f3431ae` / `no-default` branch)
- https://github.com/mxw/vim-jsx (commit `52ee8bb`)
- https://github.com/pangloss/vim-javascript (commit `3e0b1af`)
- https://github.com/hail2u/vim-css3-syntax (commit `ed97cb7`)
- https://github.com/ap/vim-css-color (commit `2411b84`)
- neovim:
```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180320-42675-1qez91d/build/config -I/tmp/neovim-20180320-42675-1qez91d/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180320-42675-1qez91d/build/src/nvim/auto -I/tmp/neovim-20180320-42675-1qez91d/build/include
Compiled by jess@Jesss-MBP.lan
Features: +acl +iconv +jemalloc +tui
```

`~/.vimrc`
```
let g:jsx_ext_required = 0 " Works on files other than .jsx

if has('autocmd')
  " Support `-` in css property names
  augroup VimCSS3Syntax
    autocmd!
    autocmd FileType css setlocal iskeyword+=-
  augroup END

  call jspretmpl#register_tag('gql', 'graphql')
  autocmd FileType javascript.jsx JsPreTmpl
  autocmd FileType javascript JsPreTmpl
endif
```

**Comment by gtsop** [comment]
> * https://github.com/mxw/vim-jsx
This package is now deprecated
