### ISSUE TITLE
Issue with with flow type object

### ISSUE THREAD

**Issue by gf3** [pangloss/vim-javascript#723]
In flow, object keys can be terminated with a semi-colon (vs a comma in JS) and that seems to be tripping up syntax highlighting:

<img width="465" alt="screen shot 2016-11-21 at 10 57 19 am" src="https://cloud.githubusercontent.com/assets/18397/20489643/5b5aefca-afd9-11e6-98b0-17fe99cacde4.png">

This is with version a87c94438b038a060fa2920055a50a0c1cf08186

**Comment by amadeus** [comment]
I've recently created a branch with some flow fixes, if you could do me a solid and test it: https://github.com/pangloss/vim-javascript/pull/991
