### ISSUE TITLE
Const directly followed by import is not highlighted

### ISSUE THREAD

**Issue by blacksails** [pangloss/vim-javascript#726]
Sometimes I would like to destruct an import "as part of the import". In these cases it makes sense to me to have the destruct directly after the import. When I do this the const doesn't get highlighted. 

See screenshots:

![screen shot 2016-11-24 at 08 31 30](https://cloud.githubusercontent.com/assets/3807831/20589988/7534cfd0-b220-11e6-8a99-d6a5bf9c09f2.png)
![screen shot 2016-11-24 at 08 36 28](https://cloud.githubusercontent.com/assets/3807831/20590066/21b46a40-b221-11e6-93e7-63276a9df050.png)

It is only a problem when not using semicolons:

![screen shot 2016-11-24 at 08 37 35](https://cloud.githubusercontent.com/assets/3807831/20590094/5238867e-b221-11e6-98cb-25ac1550a0f9.png)

**Comment by amadeus** [comment]
Good catch, I always use semicolons so I never noticed. Anyways, I have a fix in #727
