### ISSUE TITLE
indentation bug: array of objects inside object

### ISSUE THREAD

**Issue by scharfie** [pangloss/vim-javascript#73]
First, I want to say great job on this indent script, as it works great nearly all the time.  I did encounter a bug with this particular data structure:

```javascript
var data = {
  arrayOfObjects: [
    {
    key: "value"
  }
  ]
}
```

Notice that the key: "value" line and following brace are off by one indentation level.

**Comment by edwardsmit** [comment]
+1 Doesn't look like the maintainers find this annoying seeing that this "confirmed bug" is open for more than a year :(

**Comment by qstrahl** [comment]
Oh believe me, we find it annoying. It's just that vim indent plugins are
arcane and we all have lives outside code, too.

**Comment by amadeus** [comment]
Also, unfortunately, none of the current maintainers (including myself) have any real experience with Vim's indent API. None of us wrote the original code for it, so it's a bit of a scary beast

**Comment by bounceme** [comment]
With the develop branch I can't reproduce any of these examples

**Comment by amadeus** [comment]
Yup, this does appear fixed!
