### ISSUE TITLE
How to replace the default parenthesis-aligned indent with a regular one?

### ISSUE THREAD

**Issue by moll** [pangloss/vim-javascript#75]
Is there a way to replace the default parenthesis-aligned line continuation indenting with a regular 1-indent per continuation?

While the parenthesis-alignment may look nice occasionally, it makes the code very irregular, sharp, wastes a lot of space with longer function names, doesn't work with tabs and kills bunnies.

That is, instead of:
```javascript
function(1,
         2)
```
get
```javascript
function(1,
  2)
```

**Comment by nornagon** [comment]
Wish this was configurable :(

**Comment by WChargin** [comment]
Am I missing something, or is the following patch all it takes?
```diff
diff --git a/indent/javascript.vim b/indent/javascript.vim
index 0f526db..a935a87 100644
--- a/indent/javascript.vim
+++ b/indent/javascript.vim
@@ -426,14 +426,8 @@ function GetJavascriptIndent()
   " add indent depending on the bracket type.
   if line =~ '[[({]'
     let counts = s:LineHasOpeningBrackets(lnum)
-    if counts[0] == '1' && searchpair('(', '', ')', 'bW', s:skip_expr) > 0
-      if col('.') + 1 == col('$')
+    if counts[0] == '1' || counts[1] == '1' || counts[2] == '1'
         return ind + &sw
-      else
-        return virtcol('.')
-      endif
-    elseif counts[1] == '1' || counts[2] == '1'
-      return ind + &sw
     else
       call cursor(v:lnum, vcol)
     end
```

Admittedly, I don't understand what the whole `searchpair` business is supposed to do, but I'm pretty sure I don't want it. Doesn't that patch :arrow_up: just essentially mean "when there's an opening paren/bracket/brace, add one `shiftwidth`," which is exactly what we want?

Of course, we'd probably want to add it as a flag, but that's not difficult; #159 shows the way to do that.

**Comment by bounceme** [comment]
If we all agree on removing the special parentheses indent, i can get this into develop

**Comment by bounceme** [comment]
hey,on develop this was finally changed in a fairly large commit, which means certain things could have issues. testers are welcome

**Comment by clessg** [comment]
Thanks a lot, @bounceme. This will be a welcomed change.

The only problem I've had with the `develop` branch is that it becomes:

```javascript
function(1,
2)
```

Instead of

```javascript
function(1,
  2)
```

Still better than the previous behavior though.

**Comment by bounceme** [comment]
my other branch,bounceme-patch-1, fixes that. i'll try and finish up my new pr soon

**Comment by moll** [comment]
Yay. Has this been merged in already? If not, I'd suggest keeping this issue open until it's resolved in the stable release. Things tend to slip through otherwise. ;)
