### ISSUE TITLE
Customizing colors

### ISSUE THREAD

**Issue by wamoyo** [pangloss/vim-javascript#752]
Is there a useful way to customize colors?

For instance, strings and objects are the same color and it's throwing me off a bit. I'd love to be able to change that.

**Comment by amadeus** [comment]
Sounds like you might be using a pretty bad color theme? I have never seen a theme where objects and strings are colored the same.

I'm assuming you have `:syntax on`?

**Comment by amadeus** [comment]
But to answer your question directly, yes. If you take a look at `syntax/javascript.vim` And scroll to the bottom of the file there's a bunch of lines there that begin with `HiLink`. These are mapping to various groups that you can attach your own colors to via the `highlight` command. I recommend looking at another a color scheme file for reference, and either append your modifications to your .vimrc, or just start maintaining your own custom color theme.

**Comment by wamoyo** [comment]
Yes. Syntax is on, and I tried different color schemes but they essentially produce the same results.

Let me share some screenshots, just in case my description was way off.

![shot1](https://cloud.githubusercontent.com/assets/1170326/20919415/b44a3a5a-bb69-11e6-82c5-2e5a153fcfa3.png)
![shot2](https://cloud.githubusercontent.com/assets/1170326/20919416/b44c3b02-bb69-11e6-87d4-c9c2846b3a44.png)

The color of console, booleans and of strings are all the same. That can get confusing. I guess the first question to ask is, "Is this just true for me, or is this intended?"

**Comment by wamoyo** [comment]
Cool, deal! I'll try making some edits to my vimrc.
