### ISSUE TITLE
ES6 destructuring of array with default value in function params identified as error

### ISSUE THREAD

**Issue by hbaughman** [pangloss/vim-javascript#755]
In both of the following instances of destructuring with a default value in a function param, the closing `]` is identified as

> hi\<jsParensError\> trans\<jsParensError\> lo\<Error\>

when using the script from [this vim tip](http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor).

```javascript
function someFunc([foo, bar = "huh"]) { }
const anotherFunc = ([foo, bar = 4]) => {}
```

I have the latest version of vim-javascript (as updated by Vundle).

Love the plugin, IMO it's essential for JS development in vim.

**Comment by amadeus** [comment]
Whoops, forgot to include array destructuring in function arguments. Should be fixed in `master` now.

**Comment by hbaughman** [comment]
Awesome, thanks!
