### ISSUE TITLE
[flow] bug: wildcard and object destructuring

### ISSUE THREAD

**Issue by anilanar** [pangloss/vim-javascript#762]
Wrong highlighting with the following case, I guess flow wildcards are not handled by `vim-javascript`:

```
export default (x) => ({
    fn: function* (x): * {
        const {length} = x;
    },
    fn2: function () {
        return {
            a: 1,
            b: 2,
            c, 3
        };
    }
});
```

![screen shot 2016-12-15 at 12 44 03](https://cloud.githubusercontent.com/assets/753736/21222819/340ed53c-c2c4-11e6-8648-4656bca72461.png)

After removing wildcard: 

![image](https://cloud.githubusercontent.com/assets/753736/21222879/7eaf3078-c2c4-11e6-9fc1-3e62a3bcb869.png)

**Comment by anilanar** [comment]
Apparently return type annotations for arrow functions are not properly highlighted either.

**Comment by amadeus** [comment]
Fixed!
