### ISSUE TITLE
Issue with decorators inside class definition

### ISSUE THREAD

**Issue by chemzqm** [pangloss/vim-javascript#763]
<img width="294" alt="screen shot 2016-12-19 at 8 14 18 pm" src="https://cloud.githubusercontent.com/assets/251450/21312965/065797a0-c62a-11e6-896e-f8e13f2bc68b.png">

It work well with commas, but not always work without commas.
The problem repeatable with only vim-javascript as external plugin.

**Comment by amadeus** [comment]
Should be fixed in #776
