### ISSUE TITLE
Help installing (newbie here)

### ISSUE THREAD

**Issue by jsantana90** [pangloss/vim-javascript#773]
Hello

I'm looking on trying out VIM for an IDE of some sort, I've installed [vimrc](https://github.com/amix/vimrc) for the most part it looks pretty decent.

What I'm missing is linting configuration for syntax errors and what not, some sort of intellisense (which I think vim-javascript does).

From what I've read, [vim-pathogen](https://github.com/tpope/vim-pathogen) is the way to install vim specific plugins.

I've followed the documentation in vim-javascript on how to install using pathogen. I notice after installing that I see text colors differently but I still don't get autocomplete of any sort.

I tried adding the configurations to my .vimrc file but I don't think I'm doing it right.

Here's what it looks like:

```
 set runtimepath+=~/.vim_runtime
 
 execute pathogen#infect()
 source ~/.vim_runtime/vimrcs/basic.vim
 source ~/.vim_runtime/vimrcs/filetypes.vim
 source ~/.vim_runtime/vimrcs/plugins_config.vim
 source ~/.vim_runtime/vimrcs/extended.vim
 let g:javascript_plugin_jsdoc = 1
 let g:javascript_plugin_ngdoc = 1
 let g:javascript_plugin_flow = 1
 set foldmethod=syntax
 
 try
 source ~/.vim_runtime/my_configs.vim
 catch
 endtry
```

**Comment by bounceme** [comment]
`Vastly improved Javascript indentation and syntax support in Vim.`

there is no autocompletion plugin here

**Comment by amadeus** [comment]
Yeah, are only indentation and syntax support.

I would also recommend using [Plug](https://github.com/junegunn/vim-plug) over of Pathogen
