### ISSUE TITLE
Function bind syntax incorrectly highlighted as Flow inside function calls

### ISSUE THREAD

**Issue by tomxtobin** [pangloss/vim-javascript#785]
Function bind syntax is incorrectly highlighting as Flow inside function calls, e.g.:
```js
foo(bar::baz)
```
`::baz` above is being highlighted as `jsFlowDefinition`.

**Comment by amadeus** [comment]
How far along is this new syntax? 😳

If it's pretty much accepted and standardized I'll look to support it, otherwise I'd prefer to hold off until it becomes official.

**Comment by tomxtobin** [comment]
[It's at Stage 0, same as do expressions](https://github.com/tc39/proposals/blob/master/stage-0-proposals.md), which you were kind enough to add support for when I asked about it in #525. :-) Both are supported in Babel, for what that's worth.
