### ISSUE TITLE
Highlighting jsGlobalObjects anywhere

### ISSUE THREAD

**Issue by marlun** [pangloss/vim-javascript#797]
Words which is in jsGlobalObjects get highlighted everywhere, even when inside something like Marionette.Object.extend(...). Here Object is highlighted even though it's not the global Object. Could this be fixed somehow? Maybe making sure there's whitespace before?

**Comment by bounceme** [comment]
whitespace doesn't affect the `.` operator. and Object is itself a property of either `window` , or in node, `global` .

**Comment by amadeus** [comment]
I have an idea that might fix this in #814, please checkout that branch and test if you can!

**Comment by amadeus** [comment]
Should be fixed in `master` now
