### ISSUE TITLE
Wrong indentation inside object literals

### ISSUE THREAD

**Issue by osenvosem** [pangloss/vim-javascript#798]
![screen shot 2017-01-07 at 22 40 42](https://cloud.githubusercontent.com/assets/6762673/21744652/21cf5346-d52b-11e6-9129-b855b619a358.png)

**Comment by bounceme** [comment]
can you post the plugins you use?

**Comment by bounceme** [comment]
and paste the code in the photo, thanks

**Comment by bounceme** [comment]
```
export default {
  query:{
    func(){
      return a +
        2
    },
    func2(){
      return t =
        2
    }
  }
}
```
my results with similar code ^

conflict in your vimrc is my guess

**Comment by bounceme** [comment]
you may want to try reinstalling your plugins to get a clean env

**Comment by osenvosem** [comment]
@bounceme you are right. After I removed all my plugins and reinstall them, the indentation works fine. Thank you.

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/commit/dce5a10a0ff0a69f52cd6902eaad43f5f237ef1a

i messed it up there
