### ISSUE TITLE
Class keyword breaks highlighting if used as object property

### ISSUE THREAD

**Issue by meznaric** [pangloss/vim-javascript#805]
<img width="293" alt="screen shot 2017-01-12 at 15 12 02" src="https://cloud.githubusercontent.com/assets/1058131/21895299/16a60b24-d8da-11e6-81ab-f53af79f2494.png">

I know we should avoid using `class` in that way, but this is what happens when you depend on external API. I tried to contribute with PR but I don't know enough about vimscript (yet!)

Oh, and thanks for fixing the other issue so fast!

**Comment by amadeus** [comment]
Good find, I have a test fix in #814 that I need to sit on for a couple days to ensure I didn't regress anything. I would recommend checking out that branch and helping to test.

**Comment by amadeus** [comment]
Should be fixed in `master` now
