### ISSUE TITLE
Regression on function class property shorthand

### ISSUE THREAD

**Issue by meriadec** [pangloss/vim-javascript#812]
**EDIT 2017-08-03**: *initial problem is not an issue anymore, but similar pb raised by @indiesquidge* :

```
// this is OK
class Test {
  something = () => this.foo({ bar: 'baz' })
}

// this is KO
class Test {
  something = () =>
    this.foo({ bar: 'baz' })
}
```

![2017-08-03-095648_663x405_scrot](https://user-images.githubusercontent.com/315259/28911820-13b353ac-7832-11e7-9d8c-a2a61346ad72.png)

-----------------------------------------------------------

Hi, and thanks for this plugin.

d8a6fef Bugfix for jsArrowFuncArgs

This commit introduced a regression on function class property shorthand highlighting.
Given this input:

```javascript
class Foo {

  doSomething = () => ({
    foo: 'bar',
  })

}

```

Actual result (on HEAD, 690f23e fix for inc/dec operators and blocks (#811))

![screen shot 2017-01-16 at 15 16 47](https://cloud.githubusercontent.com/assets/315259/21986223/e2fad62e-dbfe-11e6-8642-84cec451694d.png)

Result when reverting d8a6fef :

![screen shot 2017-01-16 at 15 17 09](https://cloud.githubusercontent.com/assets/315259/21986235/f18476be-dbfe-11e6-8df5-7fe8b626dac3.png)

**Comment by indiesquidge** [comment]
@meriadec, is this still an issue for you on the latest release? I am not seeing it.

<img width="308" alt="screen shot 2017-08-02 at 1 29 23 pm" src="https://user-images.githubusercontent.com/3409645/28893543-ac86389e-7786-11e7-8757-bce9f9aa08db.png">

**Comment by indiesquidge** [comment]
However, I do get it with something similar

<img width="476" alt="screen shot 2017-08-02 at 1 33 38 pm" src="https://user-images.githubusercontent.com/3409645/28893677-3f795348-7787-11e7-9136-66b0b6d4bfd8.png">

Not sure if this warrants opening a new issue, or if the screenshot above can serve as the "updated" version of this issue.

**Comment by meriadec** [comment]
@indiesquidge yep you're right, my initial problem is fixed, but I confirm issue with the function class property using `this`. Will update my initial question.

**Comment by mhanberg** [comment]
I am also seeing some strange highlighting, but I'm not sure if it is exactly related to this.

With newline (incorrect highlighting and some kind of nameless errors):
![image](https://user-images.githubusercontent.com/5523984/49172566-6fc46100-f30f-11e8-8979-9652c37aae99.png)


Without newline (correct highlighting):
![image](https://user-images.githubusercontent.com/5523984/49172525-515e6580-f30f-11e8-8c70-dca3be1c2b28.png)

I am interested in attempting to fix this, if anyone can point me in the right direction of where to start looking I would appreciate it!

Thanks!
