### ISSUE TITLE
Syntax Highlight breaks on special uses of template `strings`

### ISSUE THREAD

**Issue by tomgco** [pangloss/vim-javascript#818]
For example:

```js
{`/:org/${name}`}
```

causes anything after that to highlighted like a string.

![screenshot from 2017-01-19 11-29-11](https://cloud.githubusercontent.com/assets/524382/22105125/86b1422a-de3a-11e6-84dd-2052d7accbdd.png)

This seems to only happen when the backticks are surrounded with curly braces.

**Comment by amadeus** [comment]
You must be using [mxw/vim-jsx](https://github.com/mxw/vim-jsx) alongside this plugin in order to write JSX

**Comment by tomgco** [comment]
@amadeus I am not using `vim-jsx`, so to provide a new test case and to show you **just** `vim-javascript` running I have provided the following screenshot. (I am using neovim)

I understand that you might get a lot of noise from developers that have conflicting plugins, so the following test case should hopefully prove that it isn't a configuration issue, although I cannot rule out it being neovim, which I am not sure if you support.

![screenshot from 2017-01-20 10-51-33](https://cloud.githubusercontent.com/assets/524382/22146949/6d1cc89c-defe-11e6-97eb-3df552018c43.png)

On the left you can see my config, everything is commented out, apart from `vim-javascript`, I have opened up the file in question on the right. 

As you can see that the bug still exhibits itself.

I then decided to disable vim-javascript, and the result is the bug disappearing.

![screenshot from 2017-01-20 10-56-19](https://cloud.githubusercontent.com/assets/524382/22147114/1795fbc2-deff-11e6-8e68-63648c5d4bfc.png)

As a note I am happy to help to debug this, I just am not sure how, I have never authored a vim plugin.

Thanks for your time.

**Comment by bounceme** [comment]
you *need* vim-jsx

**Comment by tomgco** [comment]
> you need vim-jsx

I understand this, but it shouldn't explode when parsing, or are you saying it should if it finds some unknown grammar? The plugin works as I expect it to in every other use-case. And I don't really want to have jsx syntax highlighting.

**Comment by bounceme** [comment]
set filetype to `javascript.jsx` or `jsx`

**Comment by bounceme** [comment]
oh, yes, you need `vim-jsx` and to set the filetype or everything will break

**Comment by bounceme** [comment]
the syntax file at this repo is almost parser like. there are basic syntax files which just highlight keywords and strings you can use ( like the default one )

**Comment by amadeus** [comment]
JSX is literally invalid JavaScript. It's going to blow up our syntax matching unless we explicitly match for it.

**Comment by amadeus** [comment]
And just a side note, the vim-jsx file is super minimal and does a great job of building on top of ours. It's a very consistent experience, as I use it daily

**Comment by dmdque** [comment]
This would be worth including in the README, imo. Thanks for the tip.

**Comment by costerik** [comment]
I have the plugin `vim-jsx` installed and I still have the problem. :-(
<img width="717" alt="Screen Shot 2019-11-12 at 5 49 12 PM" src="https://user-images.githubusercontent.com/8321591/68717460-d8ced400-0574-11ea-8f1a-72a3aa4e1997.png">

**Comment by amadeus** [comment]
Can you paste a snippet of code that shows the bug? It's easier to do that then re-type from an image. I've been using vim-javascript and mxw/jsx for a long time now and not really come across any issues.

**Comment by atomheartother** [comment]
@cthulhu-bot thank you so much, this was driving me crazy, I wonder why `neovim` doesn't understand these file types by default, it looks like regular VIM gets it just fine.
