### ISSUE TITLE
Indentation is not showing properly

### ISSUE THREAD

**Issue by ex-surreal** [pangloss/vim-javascript#819]
Indentation for es6 is not showing properly.
![image](https://cloud.githubusercontent.com/assets/6083611/22132784/5c6144dc-dee6-11e6-8859-4a82d4884691.png)
Output for `verbose set indentexpr?` is
```
indentexpr=EclimGetJavascriptIndent(v:lnum)
Last set from ~/.vim/eclim/indent/javascript.vim
```
Is there any extra setting needed for that?

**Comment by amadeus** [comment]
`EclimGetJavascriptIndent` is not our plugin. It should say `GetJavascriptIndent`.

You'd need to bring it up with Eclim
