### ISSUE TITLE
html with script causes render issues

### ISSUE THREAD

**Issue by justsaul** [pangloss/vim-javascript#820]
If inside html you have script that looks something like this:

`<script type="text/ng-template" id="...">
    <div>....</div>...<div></div>....form...
</script>`

then it causes vim to render it super slowly and it has incorrect color issue.

this issue seems to be caused by forms with input fields inside script

**Comment by bounceme** [comment]
why would an input field cause that? I think it is probably some inline code

**Comment by bounceme** [comment]
wait, is that html inside of a script tag? that may be your problem

**Comment by justsaul** [comment]
Yeah, script contains html.

**Comment by bounceme** [comment]
`src="template"` is the easy solution

**Comment by bounceme** [comment]
it's an issue with html syntax anyway
