### ISSUE TITLE
Syntax mishap: one-line arrow functions as property initializers in class definition

### ISSUE THREAD

**Issue by qstrahl** [pangloss/vim-javascript#821]
Given the following code:

```
class Foo {
  goodBar = (() => console.log('good bar'));
  alsoGoodBar = arg => console.log('also good bar', arg);
  badBar = () => console.log('bad bar'); // this line does not highlight right!
}
```

The syntax highlighting of the `badBar` definition is... not. A brief inspection revealed that the syntax region immediately following the `=>` is `jsClassValue`. Hopefully this is as straightforward as including the right subgroup/region somewhere, just a missed case.

**Comment by qstrahl** [comment]
I found that removing `keepend` from this line in `syntax/javascript.vim` fixed it, but I'm not sure of the ramifications:

```
syntax region  jsClassValue             contained start=/=/ end=/\%(;\|}\|\n\)\@=/ contains=@jsExpression keepend
```

**Comment by amadeus** [comment]
Currently not at my computer to test, but if you remove `keepend` and also remove the semicolons, does it still work?

If so then we should be good with that PR

**Comment by qstrahl** [comment]
Do you mean if I remove the semicolons from the code example, or if I remove the semicolon from the `end` value of the syntax region?

**Comment by amadeus** [comment]
From the syntax test case you provided, sorry, wasn't clear there.

**Comment by qstrahl** [comment]
No problem. Yeah, still seems to work.
