### ISSUE TITLE
Syntax highlighting for attributes?

### ISSUE THREAD

**Issue by neilpeter08** [pangloss/vim-javascript#841]
Not really sure if this is the right place to ask but is it possible to change the color of the attributes from white to a different one on this code?

![screen shot 2017-02-08 at 10 07 34 am](https://cloud.githubusercontent.com/assets/5005708/22720828/3d4f145a-ede8-11e6-93ff-544543ad010c.png)

**Comment by bounceme** [comment]
put your cursor over something then paste this in the command prompt:
`echom synIDattr(synID(line('.'),col('.'),0),'name')` that will show you what syntax group to change with a `:hi` command

**Comment by neilpeter08** [comment]
You learn new things everyday. Thanks @bounceme!
