### ISSUE TITLE
Interferes with rainbow_parentheses

### ISSUE THREAD

**Issue by laughinghan** [pangloss/vim-javascript#85]
I just cloned the latest `master` and its interfering with my (up-to-date) fork of https://github.com/kien/rainbow_parentheses.vim . It doesn't interfere with any of my other syntax highlighting plugins (e.g. https://github.com/groenewege/vim-less), only vim-javascript.

Specifically, it appears to be just the `function` keyword that breaks the rainbow parens:
![screenshot](https://f.cloud.github.com/assets/225809/738842/ef7cda9e-e34d-11e2-85b0-4389fac67acb.png)

**Comment by ohcibi** [comment]
I have just pulled latest master (current commit 977e220b3719) and the issue still exists. I have a js file with `function` in it. If I delete just e.g. the `n` of the word all braces, parenthesis and brackets suddenly become colorful when they were black before. Again this is only an issue with vim-javascript.

**Comment by c10b10** [comment]
Seems that the issue still exists for me too in https://github.com/oblitum/rainbow 

If I disable the plugin, colouring starts to work in js files.

**Comment by Heldraug** [comment]
Same issue, as @laughinghan wrote previously, deleting syntax/javascript.vim fixes the issue.

**Comment by Illiux** [comment]
Same issue, using luochen1990/rainbow

**Comment by amadeus** [comment]
See my comments in #184. This will probably never be fixed based on how our syntax file works.

**Comment by laughinghan** [comment]
Y'all may also be interested in the workaround mentioned in #184:
```
autocmd FileType javascript syntax clear jsFuncBlock jsFuncArgs
```

Apparently it breaks `vim-javascript`'s code folding feature, but I wouldn't know, I don't use it.

**Comment by amadeus** [comment]
@laughinghan that command will pretty much break most of the syntax highlighting if you do that, btw.

**Comment by laughinghan** [comment]
What kinds of things should break? Looks fine to me:
<img width="277" alt="screen shot 2016-06-29 at 16 29 18" src="https://cloud.githubusercontent.com/assets/225809/16467727/9ce4c310-3e16-11e6-8dc0-a42c408f3db6.png">
