### ISSUE TITLE
Unclosed parenthesis indentation not respecting cinoptions

### ISSUE THREAD

**Issue by joshglendenning** [pangloss/vim-javascript#859]
With `set cinoptions=(0` in my vimrc I would expect multiline if conditionals to be formatted this way (using 2-space tabs):
```javascript
if (cond1 ||
    cond2 ||
    cond3) {
  // ...
}
```

However, vim-javascript produces the tabbing:
```javascript
if (cond1 ||
  cond2 ||
  cond3) {
  //...
}
```

Is there another way to configure this?

**Comment by bounceme** [comment]
* `:h cino-:`
* `:h cino-star`

these are the only cinoptions implemented, others are outside the scope of this plugin.

**Comment by joshglendenning** [comment]
So there is no way to change that behavior? Those other cinoptions have nothing to do with my issue.

**Comment by bounceme** [comment]
no, `cino-(` is not supported, there isn't anything to change

**Comment by joshglendenning** [comment]
It looks like this was discussed in https://github.com/pangloss/vim-javascript/issues/75.

From what I can tell, since vim-javascript previously indented that way, it is capable of either style of indenting. Why not support cino-(? It's rather annoying to not be able to use autoindenting.

**Comment by bounceme** [comment]
you seem to be the only person to want that indent style, since no-one had any issue since about it being removed. I could probably reimplement it, but until I do, it is disappointing indeed

**Comment by joshglendenning** [comment]
Shouldn't the issue remain open then? I can maybe look into implementing it.

**Comment by bounceme** [comment]
don't worry, I'll do it by tomorrow

**Comment by joshglendenning** [comment]
Looks like @actionshrimp took a stab at implementing a flag for it, looks like it didn't really go anywhere https://github.com/pangloss/vim-javascript/pull/159

Not sure if that'll help or not. I assume adding support for `cinoption`s is similar to adding a flag.

**Comment by bounceme** [comment]
I already have the cino parsing algorithm, https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L330. 
there will be some differences with this specific one though

**Comment by bounceme** [comment]
for example, I don't want to implement the part about multiple parens increasing the indent

**Comment by bounceme** [comment]
actually i'll just implement the option if it set as `cino=(` or `cino=(0`

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/860
