### ISSUE TITLE
JavaScript highlighting inside ${} in `template strings`

### ISSUE THREAD

**Issue by chee** [pangloss/vim-javascript#863]
i'd love js highlighting in the place holder expressions inside the template strings

![https://snake.dog/s/botab/cedod.png](https://snake.dog/s/botab/cedod.png)

**Comment by bounceme** [comment]
<img width="271" alt="screen shot 2017-03-02 at 8 29 40 am" src="https://cloud.githubusercontent.com/assets/9332107/23516581/785bf25c-ff22-11e6-8726-4b64df9049e7.png">

**Comment by chee** [comment]
huh, well what about that.

@bounceme did you do anything special to get that, chris?

**Comment by bounceme** [comment]
I don't, no. maybe you have a conflicting plugin. also if your editing jsx make sure to install mxw/vim-jsx

**Comment by amadeus** [comment]
Full proper syntax highlighting is supported within template parts of template strings. Make sure you are up to date and what @bounceme said is 100% as well.

**Comment by chee** [comment]
the problem was i was using this through vim-polyglot and it wasn't fully up to date. i'm using it directly now and i have beautiful highlighting in my placeholder expressions.

 thanks

**Comment by chee** [comment]
actually,

![https://snake.dog/s/wezub/xefib.png](https://snake.dog/s/wezub/xefib.png)

this is only highlighting for me if it follows [A-Za-z0-9] !

i note that that isn't the case for @bounceme.

i'm on latest version

**Comment by amadeus** [comment]
While a screenshot is useful to show the problem you are having, please post a snippet that we can copy paste into a blank file that exhibits the problem. I use template strings a lot in my day to day in many different scenarios, but have yet to experience a problem like what you show above.

**Comment by chee** [comment]
sure

```js
// doesn't highlight
const x = `abc=${this.lol}`
// does highlight
const y = `abcd${this.lol}`
```

**Comment by chee** [comment]
i've just disabled all other plugins and confirm this is happening because of something other than pangloss/vim-javascript.
