### ISSUE TITLE
Comment indentation wrong, also messes up anything after it

### ISSUE THREAD

**Issue by tvenable-mie** [pangloss/vim-javascript#866]
Hi! I'm having a problem with indentation in comments. I am fully up-to-date with master. Here's an example:

**BEFORE INDENT**

```
/*
 * test
 */

function foo() {
	return 1;
}
```

**AFTER INDENT** (gg=G)

```
/*
* test
	*/

	function foo() {
		return 1;
	}
```

So you can see, not only is the comment itself wrong, but everything after that gets indented too many spaces. Thanks for looking!

**Comment by bounceme** [comment]
can't reproduce, only guess is that you have syntax highlighting turned off. otherwise it's your config

**Comment by tvenable-mie** [comment]
With a brand new file in that same session, I was getting the issue... but after closing Vim and going back to that file, everything was working again. Something must've gotten messed up in my session. I'll keep that in mind for the future. Sorry for the noise!

**Comment by amadeus** [comment]
So just to add to this, I have yet to find a way to reproduce, but occaisionally I do find that the indentation just seems off and refuses to correct itself. As if there is some cached variable that wasn't updated or something. This always occurs in long coding sessions. If I open a new Vim instance and try to recreate it, the problem goes away

**Comment by bounceme** [comment]
I know the cause @amadeus , it is an optimization unfortunately. https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L325

The `top` variable, which sets the limit to paren searching to the prev line if it had non-string chars in column 0. This is only a problem until the https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L321 condition is met (consecutive lines indented, like normal editing)
