### ISSUE TITLE
global javascript variable pass from php broken work plugin

### ISSUE THREAD

**Issue by nPaul** [pangloss/vim-javascript#871]
why this code broken plugin?
```
<?php $qwe = "qwe";?>
<script>
var qwe = <?php echo $qwe;?>;
function qwe()
{
}
</script>
```

but this code work fine
```
<?php $qwe = "qwe"; ?>
<script>
function qwe()
{
var qwe = <?php echo $qwe;?>;
}
</script>
```

**Comment by bounceme** [comment]
is that php or js? anyway this would be an issue with the html syntax

**Comment by nPaul** [comment]
is php file
I tried to remove this plugin from vimrc, and everything is working fine without that plugin

**Comment by bounceme** [comment]
move the code to a seperate file ? anyway it's a bug with the html syntax file

**Comment by nPaul** [comment]
it looks like
![image](https://cloud.githubusercontent.com/assets/2100668/23644764/4afcd5e6-034c-11e7-83c8-6dbceb21c8ed.png)

**Comment by nPaul** [comment]
if insert php code in quotes ", that looks like
![image](https://cloud.githubusercontent.com/assets/2100668/23645741/f36efc28-0350-11e7-96c9-94795a5031ce.png)

**Comment by bounceme** [comment]
not the place, sorry

**Comment by nPaul** [comment]
okey, i remove plugin vim-javascript
The error disappeared

**Comment by bounceme** [comment]
try `<script language="php">`
