### ISSUE TITLE
does`dd` then `p` auto indent work?

### ISSUE THREAD

**Issue by lluvio** [pangloss/vim-javascript#875]
```js
let a = {
  name: 'z san', //wait for dd
  example: {
// here wait fro paste
    name : 'lisi',
  }
}
```

now i dd the `name: 'z san' line paste below the example, i get here

```js
let a = {
  example: {
  name: 'z san', // it is indent error
    name : 'lisi',
  }

```

**Comment by bounceme** [comment]
you can use `]p`  and `[p` to paste with the same indent as the previous/next line, but the indent code only runs with the indent commands

**Comment by bounceme** [comment]
also can install unimpaired.vim and use `=p`

**Comment by lluvio** [comment]
@bounceme  thank you!
