### ISSUE TITLE
[flow] import/export type should have syntax highlighting applied

### ISSUE THREAD

**Issue by sheldonkwok** [pangloss/vim-javascript#885]
Currently, type is highlighted when declared but export type is not highlighted.

`type foo` works
`export type foo` does not work

**Comment by sheldonkwok** [comment]
I'm still running into issues with `export type Foo = { bar: boolean };`
The type is not highlighted. I just upgraded to the latest version of vim-javascript.

**Comment by bounceme** [comment]
only indent has been supported so far

**Comment by sheldonkwok** [comment]
I also just noticed `type` is not highlighted in  
`import { someVariable, type ImportantType } from './library'`

**Comment by amadeus** [comment]
I've recently created a branch with some flow fixes, if you could do me a solid and test it: https://github.com/pangloss/vim-javascript/pull/991
