### ISSUE TITLE
Add possibility to fold only functions

### ISSUE THREAD

**Issue by zdm** [pangloss/vim-javascript#888]
Hi.
Is it possible to add possibility to fold only functions bodies?

This is not very handy, when all syntax blocks are folded and you need to unfold everything when editing function.
Usually fold function body is enough.

**Comment by amadeus** [comment]
This would require us to pass all our syntax expression lines as strings, which is a path I really don't want us to travel down, sorry.

**Comment by Jeansen** [comment]
I'd like something like this too, so not every for, if and so on gets fold. This would be especially handy when using anonymous/local functions.

**Comment by zdm** [comment]
Who invented the idea to fold every block? 
This makes this plugin completely unusable for me.
Constant folding / unfolding of each level makes me crazy.
