### ISSUE TITLE
numerous flowtype highlighting issues

### ISSUE THREAD

**Issue by davidroeca** [pangloss/vim-javascript#891]
My g:javascript_plugin_flow is set to 1, and the same issue exists while set to 0 (unsurprisingly).

If I create an optional type variable, say `type OptionalString = ?string`, the syntax highlighting below is broken.

If I create a functional type such as `type MyFunctionType = (val1: string) => string`, the syntax below is broken.

If I type a variable with `var1: Array<?string>`, the syntax below is broken.

**Comment by amadeus** [comment]
Yeah, there are a lot of issues with the flow syntax. I just haven't had time to delve into them unfortunately

**Comment by amadeus** [comment]
I've recently created a branch with some flow fixes, if you could do me a solid and test it: https://github.com/pangloss/vim-javascript/pull/991
