### ISSUE TITLE
Invalid syntax highlighting inside string literals - it detects /* as a starting line for a comment

### ISSUE THREAD

**Issue by simoncpu** [pangloss/vim-javascript#896]
![examplejs](https://cloud.githubusercontent.com/assets/128593/24187860/ed1aab86-0f19-11e7-9d1b-f9a7fbab5a92.png)

Copy-pasteable:

        const init_env =` 
            for i in \`ls ${process.env['LAMBDA_TASK_ROOT']}/bin/*\`; do
                echo $i
            done
        `;

**Comment by simoncpu** [comment]
Looks like that vim was using the built-in JavaScript syntax highlighter. I solved this by putting:
`execute pathogen#infect()`
at ~/.vimrc.

**Comment by bounceme** [comment]
> Looks like that vim was using the built-in JavaScript syntax highlighter. I solved this by putting:
execute pathogen#infect()
at ~/.vimrc.

I think that is invalid syntax, use `call pathogen#infect()`
