### ISSUE TITLE
FlowType syntax breaks on nullable types

### ISSUE THREAD

**Issue by unclechu** [pangloss/vim-javascript#901]
![vim-javascript__flowtype_syntax_issue_1](https://cloud.githubusercontent.com/assets/799353/24377183/e2584b4e-1357-11e7-9a26-f8d45444a563.png)
![vim-javascript__flowtype_syntax_issue_2](https://cloud.githubusercontent.com/assets/799353/24377182/e2575090-1357-11e7-99a1-7c8c20c4708e.png)

**Comment by bsonntag** [comment]
@unclechu did you find any solution for this?

**Comment by unclechu** [comment]
@bsonntag no, solution could be just to make PR that fixes this.

**Comment by dcosson** [comment]
I too run into this all the time since I started using flow, the closing brace is highlighted red whenever one of the attributes in an object or function type annotation is nullable.

**Comment by bounceme** [comment]
`export type` also needs support

**Comment by dcosson** [comment]
I see this constantly as well. It also happens if the return value of a function is optional:

![screen shot 2017-06-22 at 11 02 26 am](https://user-images.githubusercontent.com/708904/27448632-4e1903fc-573a-11e7-97a5-1e098e32308c.png)

**Comment by amadeus** [comment]
I've recently created a branch with some flow fixes, if you could do me a solid and test it: https://github.com/pangloss/vim-javascript/pull/991

**Comment by unclechu** [comment]
@amadeus here is a screenshot of a random code chunks:
![vim-javascript-flow-issue](https://user-images.githubusercontent.com/799353/27552359-819257b8-5ac0-11e7-8e65-d7cc7e717ebd.png)
I'm not sure if everything is fine, but comments are really broken.
So, why (in this screenshot) `IAction` generic is colored but `IRecord` is not? So coloring comes when it is inside object-type-notation.

**Comment by amadeus** [comment]
@unclechu would you mind giving me some copy pasta snippets of broken code? It's easier for me to debug if I don't have to re-type things manually, but I can look into this

**Comment by unclechu** [comment]
@amadeus here is an example:
```javascript
// @flow
import * as x from './foo/sm-th';
import {smth} from './foo/sm-th';
import type {SomeType} from './foo/sm-th';

type ExactObjectNotation = {|
	// Comment inside exact object notation
	foo: SomeGeneric<SomeType>,
	/*
	 * multiline comment
	 */
	bar: SomeGeneric<AnotherType>,
|};

type ObjectNotation = {
	// Comment inside object notation
	foo: SomeGeneric<SomeType>,
	/*
	 * multiline comment
	 */
	bar: SomeGeneric<AnotherType>,
};

export type SomeType = string;
export type SomeType = ?{||};

// one same line
export type SomeType = {|foo: Array<boolean>, bar: number|};

// one separated line
export type SomeType =
	{|foo: Array<boolean>, bar: number|};

export type SomeType = SomeGeneric<SomeType>;
export type SomeType = number;

const
	withoutType = {foo: 1},
	withType: {[key: string]: number} = {bar: 2};
```
![image](https://user-images.githubusercontent.com/799353/27633087-42b2c016-5c17-11e7-9bad-e48f061ffeee.png)

**Comment by unclechu** [comment]
Another example (reproduces with 51beff79f987a7459e27e80887107726e179945a):
```javascript
// @flow
type SomeGeneric<A, B, C> = {|
	foo: number,
	bar: boolean,
|};
```
![image](https://user-images.githubusercontent.com/799353/27701334-fea535a8-5d19-11e7-9961-0a26471d1c8c.png)
