### ISSUE TITLE
highlighting for script in html is broken

### ISSUE THREAD

**Issue by gera2ld** [pangloss/vim-javascript#905]
Open an HTML file with content below:
``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script>
    import something from 'something';
    console.log(something);
  </script>
</body>
</html>
```

When not using any plugin, highlighting works for the embedded script. But when adding `pangloss/vim-javascript` plugin, `import` cannot be recognized and indention after `import` is broken.

Without `vim-javascript`:
![](https://cloud.githubusercontent.com/assets/3139113/24574394/6043b808-16c4-11e7-8ca7-796bd4b7122e.png)

With `vim-javascript`:
![](https://cloud.githubusercontent.com/assets/3139113/24574430/071d824e-16c5-11e7-8929-43a871cd5d9e.png)

**Comment by bounceme** [comment]
i suggest you split it into a different file, or file a bug report with the html script maintainer. We have no control over html files.

**Comment by gera2ld** [comment]
It only happens when this plugin is enabled, and the syntax highlight is quite different before and after the plugin is enabled (Just like that in a JavaScript file).
I have just looked into the HTML plugin, it does nothing with JavaScript, but just fallbacks to `indent/javascript.vim`, which in my case is from this plugin.

I have found the solution by appending `jsImport` and `jsExport` to `jsAll`, like this:
``` viml
syntax cluster jsAll contains=@jsExpression,jsStorageClass,jsConditional,jsRepeat,jsReturn,jsStatement,jsException,jsTry,jsAsyncKeyword,jsNoise,jsBlockLabel,jsImport,jsExport
```

**Comment by gera2ld** [comment]
@bounceme Is there a reason to exclude `jsImport` and `jsExport` from `jsAll`?

**Comment by bounceme** [comment]
Don't know, @amadeus might (I don't have any idea how syntax files work) . If you make a pr things will likely move faster with this
