### ISSUE TITLE
jsObjectProp wins over jsPrototype

### ISSUE THREAD

**Issue by moll** [pangloss/vim-javascript#915]
Hey,

I'm not sure if that's intentional, but `jsObjectProp` wins over `jsPrototype` in the following code snippet:
```js
Foo.prototype
```

I believe `prototype` is supposed to be highlighted differently there.

**Comment by moll** [comment]
I fixed it for myself with:
```vim
syntax match   jsNoise /[\.]\{1}/ skipwhite skipempty nextgroup=jsObjectProp,jsFuncCall,jsPrototype
```

**Comment by bounceme** [comment]
couldn't it just be: 
`syntax match   jsNoise /\./ skipwhite skipempty nextgroup=jsObjectProp,jsFuncCall,jsPrototype` ?

**Comment by moll** [comment]
Dunno. I just copied the jsNoise statement from the current master and added one group.

**Comment by amadeus** [comment]
Should be fixed in master, thanks!
