### ISSUE TITLE
Losing indents on multiline variable declarations

### ISSUE THREAD

**Issue by sbussetti** [pangloss/vim-javascript#918]
I'm using variable indents for multiline variable declarations in es6, for instance:

```
const foo = 1,
      bar = 2,
      baz = 3;

let foo = 1,
    bar = 2,
    baz = 3;
```
In addition to that, I'm using 2-space tabs, so in the above case, the indent depth is 3 and 2 respectively.

Out of the gate, vim-javascript only indents multiline variable decls with one indent.  Is there any way for me to configure that differently?

**Comment by sbussetti** [comment]
After reading the source I'm realizing that GetJsxIndent from vim-jsx is what provides the indentexpr that I need to deal with.. right?

**Comment by bounceme** [comment]
what? this repo is for javascript.

my results, as expected

```
const foo = 1,
  bar = 2,
  baz = 3;

let foo = 1,
  bar = 2,
  baz = 3;
```

**Comment by sbussetti** [comment]
eslint allows for this:

```
    "indent": [2, 2, {
      "VariableDeclarator": {"var": 2, "let": 2, "const": 3},
    }],
```

Or are you making the argument that JavaScript is only a subset of ECMAScript @bounceme ?

**Comment by bounceme** [comment]
eslint has an option for this, this repo doesn't. i'm not arguing about ecmascript vs. javascript ( first time i've ever heard of there being a distinction ). and i'll just ignore the comment about vim-jsx as it makes no sense in this context, as the examples don't have any jsx in them

**Comment by sbussetti** [comment]
Yeah neither have I, I was trying to understand what you meant.

Comment deleted, no reference to jsx here, I was incorrect in my assumptions.

So there's no way to configure the indent depth for block statements with your plugin?  That's totally cool, thanks for clearing that up.

**Comment by bounceme** [comment]
yea, it depends only on `shiftwidth` and `tabstop` settings.

**Comment by sbussetti** [comment]
That's helpful, thanks, I follow now.  I couldn't suss it out.
