### ISSUE TITLE
Use With TypeScript?

### ISSUE THREAD

**Issue by iammerrick** [pangloss/vim-javascript#923]
vim-javascript still highlights better than the typescript syntax files. I'm wondering if I can use vim-javascript on my typescript files and still have the filetype be typescript (for other typescript plugins)

**Comment by amadeus** [comment]
Out of scope for this plugin, but you could build your own typescript filetype plugin that then sources JS instead

**Comment by iammerrick** [comment]
Cool. For now, I'll add support for yats plugin. https://github.com/trevordmiller/nova-vim/pull/68
