### ISSUE TITLE
Broken highlighting on EJS template files

### ISSUE THREAD

**Issue by tpict** [pangloss/vim-javascript#930]
Using vim-javascript with either https://github.com/briancollins/vim-jst or https://github.com/nikvdp/ejs-syntax causes an issue where any HTML following an if statement is highlighted as JS:

![broken](https://cloud.githubusercontent.com/assets/12588098/25480416/98c38d58-2b40-11e7-8406-34c627177631.png)
vim-javascript

![notbroken](https://cloud.githubusercontent.com/assets/12588098/25480432/a38b0b58-2b40-11e7-9cca-e3fb657f4353.png)
https://github.com/jelera/vim-javascript-syntax

![default](https://cloud.githubusercontent.com/assets/12588098/25480452/ba06d542-2b40-11e7-80cb-688ad7cf0031.png)
default JS highlighting

**Comment by amadeus** [comment]
Unfortunately with the way out syntax matching works, there's no way we could support being used in EJS. We depend heavily on Vim's `nextgtoup` syntax which would completely break if the syntax chunks are broken up like this.

This is probably a `wontfix`
