### ISSUE TITLE
rest operator in function declaration breaks the highlighting

### ISSUE THREAD

**Issue by tinchoz49** [pangloss/vim-javascript#944]
Hi, how are you? I noticed that using the `...` operator as an argument in my function declarations breaks the highlighting for the rest of my JS file.

I'm using neovim v0.2.0 and I'm not using other plugins for JavaScript (like jsx) 

![screenshot_2017-05-10_00-09-41](https://cloud.githubusercontent.com/assets/819446/25881786/6352685e-3515-11e7-8561-0bd2e0b3c132.png)

**Comment by bounceme** [comment]
works for me. you could have a problem with your config, preventing this plugin's syntax stuff to apply

**Comment by tinchoz49** [comment]
hi @bounceme, thanks for the quick review of this issue. Yes, you're right it was a problem with my vim extra configuration. Sorry for had opened the issue without testing this thing isolated in my vim.
