### ISSUE TITLE
Segmentation Fault in neovim from 9ce4ea8

### ISSUE THREAD

**Issue by nicknisi** [pangloss/vim-javascript#950]
I am getting a segmentation fault in neovim 0.2.0 when working with JavaScript files. I believe this is caused by the changes in 9ce4ea8 and I tried to prove that using git bisect. I don't get the segfault with any previous commit (going back to 81166ac).
![may-15-2017 09-40-24](https://cloud.githubusercontent.com/assets/293805/26063224/feda1240-3952-11e7-818c-2a09288a9cb7.gif)

**Comment by bounceme** [comment]
sorry!! how is  #949

**Comment by bounceme** [comment]
and what is the output of `:version`

**Comment by nicknisi** [comment]
I'm still seeing the issue with #949 checked out. To reproduce this:

* open nvim
* run `:setf javascript`
* type some code, such as `const foo = 'hi';` and then add a newline (or hit `o` from normal mode)

Adding the newline immediately causes the segfault. Please let me know if there's any more information I can provide!

```
:version
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170502-32879-sv6zvp/neovim-0.2.0/build/config -I/tmp/neovim-20170502-32879-sv6zvp/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include
 -I/tmp/neovim-20170502-32879-sv6zvp/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170502-32879-sv6zvp/neovim-0.2.0/build/include
Compiled by nicknisi@rugen.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0/share/nvim"
```

**Comment by bounceme** [comment]
does #952 work?

**Comment by nicknisi** [comment]
Yes! I can't seem to reproduce the issue with #952 checked out!

**Comment by bounceme** [comment]
thanks, will merge #952 or make a revert
