### ISSUE TITLE
Can jsModuleGroup be foldable ?

### ISSUE THREAD

**Issue by thenewvu** [pangloss/vim-javascript#951]
Sir,

Please take a look at the below sample:

![](http://i.imgur.com/2fjlc6e.png)

Personally, I really want those import groups can be foldable, which helps the code be more compact and be verbose on demand, something like this:

![](http://i.imgur.com/WwwNgoC.png)

Please share your opinion about this.

**Comment by amadeus** [comment]
Just added this to master!
