### ISSUE TITLE
Mismatches jsOperator

### ISSUE THREAD

**Issue by davidosomething** [pangloss/vim-javascript#961]
For a php file, `a.php` containing:

```php
<?php ?>
<script></script>
```

Cursor on `<script>` matches as `jsOperator` instead of `htmlTagN htmlScriptTag`
suggests this plugin being too greedy.

**Comment by bounceme** [comment]
can't reproduce, maybe adding the type attribute will help?

**Comment by bounceme** [comment]
anyway, there really is nothing we can do here. p.r.s are accepted which demonstrate the bug and fix

**Comment by davidosomething** [comment]
never mind, it was vim-coffeescript
