### ISSUE TITLE
Syntax issue with Class fat-arrow functions

### ISSUE THREAD

**Issue by rafi** [pangloss/vim-javascript#975]
Fat-arrow class functions are matched as `jsClassProperty`. Shouldn't it be `jsClassFuncName` ?

For example:
![image](https://cloud.githubusercontent.com/assets/147918/26780120/df4231d4-49f0-11e7-9129-7f290bf92e08.png)

`firstMethod` and `thirdMethod` functions aren't matched correctly.

(Might relate to to #826 and/or #821.)

**Comment by amadeus** [comment]
yeaaaaaah, that's actually kinda hard to do and imo probably not worth the effort. Technically you are defining class expression value, so the value could theoretically be anything. You could even do an iife as well here, which could evaluate to anything. Probably gonna have to file this under `wontfix`

**Comment by bounceme** [comment]
https://github.com/tc39/proposal-class-public-fields/issues/63 see more here. classes are just filled with edge cases
