### ISSUE TITLE
Multiline template literals containing HTML are indented

### ISSUE THREAD

**Issue by matatk** [pangloss/vim-javascript#978]
I have a template literal that is multi-line and happens to contain HTML code.  This is indented by vim-javascript, but I would have expected the content of a template literal to remain unchanged. (I'm using a template literal as a means to store some example HTML code and need to preserve its layout.)

#314 appears to be related, and seems to imply that the indentation of the content of template literals may be by design.  I then wondered if it would be possible to disable indentation within template literals?  I did find #936, but am not sure how to use it (or if it's possible to use it in this situation).

Thanks for this tool!

**Comment by bounceme** [comment]
can you give some example code?

**Comment by matatk** [comment]
@bounceme thanks for the quick reply; here is the code I have been looking at...

```javascript
. . .
const htmlCode = `<html>
    <head>
        <title>Example Code</title>
    </head>
    <body>
        <h1>Example Code</h1>
        <p>This will be intended, even though it's part of a template literal.</p>
    </body>
</html>`
. . .
```

When I run `gg=G` to indent the whole file, the indentation affects the contents of the template literal (in the above snippet, the indentation is via spaces, though I've asked Vim to use tabs for indentation, and the spaces get converted to tabs).  My expectation was that the content of the template literal would be unchanged.  I am assuming that this related to vim-javascript, as it's the last thing to get loaded when Vim loads up (apologies if that is not a good thing to be doing).

I haven't specified any vim-javascript-specific settings in my `.vimrc`.

**Comment by bounceme** [comment]
cant reproduce, likely caused by conflicting plugin

**Comment by matatk** [comment]
I've just tried disabling all my Vundle plugins (except Vundle and vim-javascript) and I'm still getting this behaviour; is there anything else I can do to try to trace what is causing this? I assume that vim-javascript's indentation completely replaces Vim's own standard javascript indentation, so it's not a combination of those two?

**Comment by bounceme** [comment]
so indent levels dont change? if it just converts from tab to space it may be one of `ts sw expandtab :retab` related

**Comment by matatk** [comment]
Thanks for your reply.  The problem is that spaces are getting converted to tabs (normally I _do_ use tabs for indents, but in this template literal only, I need it to be using spaces).  The thing that I'm finding odd is that the contents of the template string are affected _at all_—I would've expected anything between the backticks to be ignored by the indentation algorithm, but perhaps that assumption is wrong?

Or maybe, from what you said above, it seems perhaps the editor is overriding the replacement of spaces with tabs, possibly according to settings elsewhere in my vimrc, so I will keep looking for the cause.

**Comment by bounceme** [comment]
`:h preserveindent` ?

**Comment by bounceme** [comment]
not related to this repo

**Comment by matatk** [comment]
@bounceme thanks—that may be of use (though I only want it to apply to the content of the template literal and not the rest of the file).  I'm still surprised that *any* changes are made to the content of the template literal, as I would've thought it was off limits to the indenting process, but it sounds from what you're saying like this is something Vim is doing (presumably because I've asked it to somehow), and not under the control of vim-javascript. Sorry for the spurious bug report, and thank you for your help!
