### ISSUE TITLE
Weird bug with arrow callback with glob and trailing comma, multiline comment

### ISSUE THREAD

**Issue by mnbroatch** [pangloss/vim-javascript#993]
```
ITakeACallback(() => {
        var IHaveATrailingComma = [
                `i/look/like/a/glob/*`,
        ];
});



/*
 *  I am a multi-line comment
 */
        IShouldntBeIndented();


```
This was the simplest way I could figure to reproduce this bug. It seems very weird. Apologies.

When a function call 
that takes an arrow function as a parameter
that has an array with a string that looks like a glob (asterisk seems important)
and a trailing comma

comes before a multi-line comment,
The next line will be indented improperly.

I'm using a pretty clean .vimrc and the latest vim-javascript. gg=G gives the above.

.vimrc: 
filetype off
execute pathogen#infect()
execute pathogen#helptags()
filetype plugin indent on
syntax on

Thanks!

**Comment by mnbroatch** [comment]
I noticed this was closed without comment. Was it not reproducable?

Thanks!

**Comment by bounceme** [comment]
i fixed it, very small and obvious in the code so i didnt think much of it

**Comment by mnbroatch** [comment]
Awesome! I was just worried I didn't present it right or it was too edge casey or something  haha. It was definitely a weird one user-side.

Thanks again!
