### ISSUE TITLE
Dot chain indentation inside objects

### ISSUE THREAD

**Issue by floscr** [pangloss/vim-javascript#995]
The indentation for dot chains is broken inside objects:

Example:

```javascript
const obj = {
  key: one()
  .then(two)
  .then(function() {

  })
}
```

should be:

```javascript
const obj = {
  key: one()
    .then(two)
    .then(function() {

    })
}
```

**Comment by bounceme** [comment]
this been debated before here. it is intended behaviour to have that inside objects, and that won't change

**Comment by floscr** [comment]
Ok, sorry, I did not know that :)
I'll try to give it a go on my own. 
Since it's opinion, maybe we could make it optional behind a variable.

**Comment by bounceme** [comment]
i could implement it, i don't like adding variables though. there are many more complications, for a perfect operator indentation within you may need an actual `ParseExpression` function, which would far eclipse the entirety of the current script, for something that from previous discussions is not even preferable by most. my recommendation is to indent them manually or just get used to it.
